incus-test: apply shfmt

diff --git a/systemtests/tests/py3plug-fd-incus/testrunner-ct b/systemtests/tests/py3plug-fd-incus/testrunner-ct
--- a/systemtests/tests/py3plug-fd-incus/testrunner-ct
+++ b/systemtests/tests/py3plug-fd-incus/testrunner-ct
@@ -19,19 +19,22 @@ JobName=backup-incus-ct
 INSTANCE=bareos-test-ct
 NEWINSTANCE=bareos-test-ct-2
 
-wait_for_network() {
-    while ! incus exec "$1" -- ping -c1 bareos.com 2>/dev/null; do
-        sleep 2
-    done
+wait_for_network()
+{
+  while ! incus exec "$1" -- ping -c1 bareos.com 2>/dev/null; do
+    sleep 2
+  done
 }
 
-sync_fs() {
-    incus exec "$INSTANCE" sync
+sync_fs()
+{
+  incus exec "$INSTANCE" sync
 }
 
-cleanup_instances() {
-    incus rm -f "$INSTANCE" 2>/dev/null || :
-    incus rm -f "$NEWINSTANCE" 2>/dev/null || :
+cleanup_instances()
+{
+  incus rm -f "$INSTANCE" 2>/dev/null || :
+  incus rm -f "$NEWINSTANCE" 2>/dev/null || :
 }
 
 trap cleanup_instances EXIT
@@ -40,11 +43,10 @@ cleanup_instances
 incus launch images:alpine/edge "$INSTANCE"
 wait_for_network "$INSTANCE"
 incus exec "$INSTANCE" apk add attr
-incus file push - "$INSTANCE/old-file" <<< foobar
+incus file push - "$INSTANCE/old-file" <<<foobar
 incus exec "$INSTANCE" -- ln -s /old-file /slinked-file
 incus exec "$INSTANCE" -- ln -s /etc /slinked-etc
 sync_fs
-
 
 start_test
 
@@ -67,7 +69,7 @@ END_OF_DATA
 run_bconsole "$@"
 check_log "$tmp/log1.out"
 
-incus file push - "$INSTANCE/new-file" <<< bazqux
+incus file push - "$INSTANCE/new-file" <<<bazqux
 incus exec "$INSTANCE" -- setfattr -n user.foobar -v bazqux /new-file
 incus exec "$INSTANCE" -- setfattr -n user.barqux -v foobar /etc
 incus exec "$INSTANCE" ln /new-file /hlinked-file
@@ -103,11 +105,11 @@ files="$(grep "^ @INCUS/instances/$INSTANCE/container/rootfs/" "$tmp/log2-list.o
 actualfiles=(etc hlinked-file new-file)
 expected="$(printf " @INCUS/instances/$INSTANCE/container/rootfs/%s\n" "${actualfiles[@]}")"
 if [ "$files" != "$expected" ]; then
-    echo "Unexpected list of modified files. Expected:"
-    echo "$expected"
-    echo "Got:"
-    echo "$files"
-    exit 1
+  echo "Unexpected list of modified files. Expected:"
+  echo "$expected"
+  echo "Got:"
+  echo "$files"
+  exit 1
 fi
 
 incus rm -f "$INSTANCE"
@@ -129,54 +131,54 @@ check_log "$tmp/log3.out"
 
 incus start "$NEWINSTANCE"
 
-if [ "$(incus file pull "$NEWINSTANCE/old-file" -)" = "foobar" ] &&
-   [ "$(incus file pull "$NEWINSTANCE/new-file" -)" = "bazqux" ]; then
-    echo "Restored file contents OK"
+if [ "$(incus file pull "$NEWINSTANCE/old-file" -)" = "foobar" ] \
+  && [ "$(incus file pull "$NEWINSTANCE/new-file" -)" = "bazqux" ]; then
+  echo "Restored file contents OK"
 else
-    echo "Restored files ERROR: files have changed"
-    dstat=1
-    exit 1
+  echo "Restored files ERROR: files have changed"
+  dstat=1
+  exit 1
 fi
 
 # We make extra sure that we didn't accidentally change file types
-if incus exec "$NEWINSTANCE" -- test -h /slinked-file &&
-   incus exec "$NEWINSTANCE" -- test -h /slinked-etc &&
-   incus exec "$NEWINSTANCE" -- test -d /etc; then
-    echo "Files kept their types"
+if incus exec "$NEWINSTANCE" -- test -h /slinked-file \
+  && incus exec "$NEWINSTANCE" -- test -h /slinked-etc \
+  && incus exec "$NEWINSTANCE" -- test -d /etc; then
+  echo "Files kept their types"
 else
-    echo "Files not restored properly"
-    dstat=1
-    exit 1
+  echo "Files not restored properly"
+  dstat=1
+  exit 1
 fi
 
 # We check extended attributes
-if [ "$(incus exec "$NEWINSTANCE" -- getfattr --only-values -n user.foobar /new-file)" = "bazqux" ] &&
-   [ "$(incus exec "$NEWINSTANCE" -- getfattr --only-values -n user.barqux /etc)" = "foobar" ]; then
-    echo "Extended attributes preserved"
+if [ "$(incus exec "$NEWINSTANCE" -- getfattr --only-values -n user.foobar /new-file)" = "bazqux" ] \
+  && [ "$(incus exec "$NEWINSTANCE" -- getfattr --only-values -n user.barqux /etc)" = "foobar" ]; then
+  echo "Extended attributes preserved"
 else
-    echo "Extended attributes lost"
-    dstat=1
-    exit 1
+  echo "Extended attributes lost"
+  dstat=1
+  exit 1
 fi
 
 # We check that hard links work
 if (("$(incus exec "$NEWINSTANCE" -- stat -c%h /new-file)" == 2)); then
-    echo "Hard links preserved"
+  echo "Hard links preserved"
 else
-    echo "Hard links broken"
-    dstat=1
-    exit 1
+  echo "Hard links broken"
+  dstat=1
+  exit 1
 fi
 
 # We check that configuration overrides work
-if [ "$(incus config get "$NEWINSTANCE" user.foo)" = "bar" ] &&
-   [ "$(incus config get "$NEWINSTANCE" user.baz)" = "qux" ] &&
-   [ "$(incus config device get "$NEWINSTANCE" root user.foo)" = "bar" ]; then
-    echo "Configuration override applied"
+if [ "$(incus config get "$NEWINSTANCE" user.foo)" = "bar" ] \
+  && [ "$(incus config get "$NEWINSTANCE" user.baz)" = "qux" ] \
+  && [ "$(incus config device get "$NEWINSTANCE" root user.foo)" = "bar" ]; then
+  echo "Configuration override applied"
 else
-    echo "Configuration override not applied"
-    dstat=1
-    exit 1
+  echo "Configuration override not applied"
+  dstat=1
+  exit 1
 fi
 
 incus rm -f "$NEWINSTANCE"
diff --git a/systemtests/tests/py3plug-fd-incus/testrunner-vm b/systemtests/tests/py3plug-fd-incus/testrunner-vm
--- a/systemtests/tests/py3plug-fd-incus/testrunner-vm
+++ b/systemtests/tests/py3plug-fd-incus/testrunner-vm
@@ -20,39 +20,43 @@ IMAGE=bareos-test-alpine
 INSTANCE=bareos-test-vm
 NEWINSTANCE=bareos-test-vm-2
 
-wait_for_agent() {
-    while ! incus exec "$1" true 2>/dev/null; do
-        sleep 2
-    done
+wait_for_agent()
+{
+  while ! incus exec "$1" true 2>/dev/null; do
+    sleep 2
+  done
 }
 
-sync_fs() {
-    incus exec "$INSTANCE" sync
+sync_fs()
+{
+  incus exec "$INSTANCE" sync
 }
 
-cleanup_instances() {
-    incus rm -f "$INSTANCE" 2>/dev/null || :
-    incus rm -f "$NEWINSTANCE" 2>/dev/null || :
+cleanup_instances()
+{
+  incus rm -f "$INSTANCE" 2>/dev/null || :
+  incus rm -f "$NEWINSTANCE" 2>/dev/null || :
 }
 
-check_chunks() {
-    grep -c "^ @INCUS/instances/$2" "$1" || :
+check_chunks()
+{
+  grep -c "^ @INCUS/instances/$2" "$1" || :
 }
 
 # Build a tiny Alpine image. This can be extremely slow, so we do not remove the image at the end,
 # to reproduce test results faster.
 if ! incus image info "$IMAGE" >/dev/null 2>&1; then
-    incus image export images:alpine/edge "$tmp" --vm
-    guestfish --rw -a "$tmp/disk.qcow2" <<EOF
+  incus image export images:alpine/edge "$tmp" --vm
+  guestfish --rw -a "$tmp/disk.qcow2" <<EOF
 run
 e2fsck-f /dev/sda2
 resize2fs-M /dev/sda2
 e2fsck-f /dev/sda2
 EOF
-    qemu-img create -f qcow2 -o preallocation=metadata "$tmp/disk.400M.qcow2" 400M
-    virt-resize --shrink /dev/sda2 "$tmp/disk.qcow2" "$tmp/disk.400M.qcow2"
-    incus image import "$tmp/incus.tar.xz" "$tmp/disk.400M.qcow2" --alias "$IMAGE"
-    rm "$tmp/incus.tar.xz" "$tmp/disk.qcow2" "$tmp/disk.400M.qcow2"
+  qemu-img create -f qcow2 -o preallocation=metadata "$tmp/disk.400M.qcow2" 400M
+  virt-resize --shrink /dev/sda2 "$tmp/disk.qcow2" "$tmp/disk.400M.qcow2"
+  incus image import "$tmp/incus.tar.xz" "$tmp/disk.400M.qcow2" --alias "$IMAGE"
+  rm "$tmp/incus.tar.xz" "$tmp/disk.qcow2" "$tmp/disk.400M.qcow2"
 fi
 
 trap cleanup_instances EXIT
@@ -60,9 +64,8 @@ trap cleanup_instances EXIT
 cleanup_instances
 incus launch "$IMAGE" "$INSTANCE" --vm -c security.secureboot=false -d root,size=400MiB
 wait_for_agent "$INSTANCE"
-incus file push - "$INSTANCE/old-file" <<< foobar
+incus file push - "$INSTANCE/old-file" <<<"foobar"
 sync_fs
-
 
 start_test
 
@@ -94,11 +97,11 @@ run_bconsole "$@"
 # 25 chunks should be created here
 chunks="$(check_chunks "$tmp/log4-list.out" "$INSTANCE/virtual-machine.img")"
 if ((chunks != 25)); then
-    echo "Error: expected 25 chunks, got $chunks"
-    exit 1
+  echo "Error: expected 25 chunks, got $chunks"
+  exit 1
 fi
 
-incus file push - "$INSTANCE/new-file" <<< bazqux
+incus file push - "$INSTANCE/new-file" <<<"bazqux"
 sync_fs
 
 cat <<END_OF_DATA >$tmp/bconcmds
@@ -127,8 +130,8 @@ run_bconsole "$@"
 # Modifying our single file should only modify ~4 chunks, but let's be safe
 chunks="$(check_chunks "$tmp/log5-list.out" "$INSTANCE/virtual-machine.img")"
 if ((chunks > 8)); then
-    echo "Error: too many chunks modified ($chunks)"
-    exit 1
+  echo "Error: too many chunks modified ($chunks)"
+  exit 1
 fi
 
 incus rm -f "$INSTANCE"
@@ -151,13 +154,13 @@ check_log "$tmp/log6.out"
 incus start "$NEWINSTANCE"
 wait_for_agent "$NEWINSTANCE"
 
-if [ "$(incus file pull "$NEWINSTANCE/old-file" -)" = "foobar" ] &&
-   [ "$(incus file pull "$NEWINSTANCE/new-file" -)" = "bazqux" ]; then
-    echo "Restored files OK"
+if [ "$(incus file pull "$NEWINSTANCE/old-file" -)" = "foobar" ] \
+  && [ "$(incus file pull "$NEWINSTANCE/new-file" -)" = "bazqux" ]; then
+  echo "Restored files OK"
 else
-    echo "Restored files ERROR: files have changed"
-    dstat=1
-    exit 1
+  echo "Restored files ERROR: files have changed"
+  dstat=1
+  exit 1
 fi
 
 incus rm -f "$NEWINSTANCE"
