Rebuild configure and config.h.in

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -631,6 +631,7 @@ ac_includes_default="\
 
 ac_header_list=
 ac_subst_vars='LTLIBOBJS
+BUILD_SD_BACKENDS
 BUILD_DIR_PLUGINS
 BUILD_SD_PLUGINS
 BUILD_FD_PLUGINS
@@ -649,6 +650,8 @@ DLIB
 DINCLUDE
 DEBUG
 CAP_LIBS
+CEPHFS_LIBS
+CEPHFS_INC
 RADOS_LIBS
 RADOS_INC
 DROPLET_LIBS
@@ -729,6 +732,7 @@ dump_email
 plugindir
 logdir
 bsrdir
+backenddir
 scriptdir
 hostname
 basename
@@ -747,6 +751,9 @@ CONS_LDFLAGS
 CONS_LIBS
 CONS_SRC
 CONS_INC
+SD_BACKENDS_DIR
+NEEDED_BACKEND_LIBS
+NEEDED_DEVICE_API_SRCS
 SD_PLUGIN_DIR
 STORED_DIR
 DIR_PLUGIN_DIR
@@ -900,6 +907,7 @@ CPPFLAGS
 LDFLAGS
 CFLAGS
 CC
+LIBBAREOSSD_LT_RELEASE
 LIBBAREOSLMDB_LT_RELEASE
 LIBBAREOSNDMP_LT_RELEASE
 LIBBAREOSFIND_LT_RELEASE
@@ -984,6 +992,7 @@ enable_static_cons
 enable_client_only
 enable_build_dird
 enable_build_stored
+enable_dynamic_storage_backends
 enable_conio
 enable_ipv6
 enable_readline
@@ -999,6 +1008,7 @@ with_archivedir
 with_basename
 with_hostname
 with_scriptdir
+with_backenddir
 with_bsrdir
 with_logdir
 with_plugindir
@@ -1047,6 +1057,7 @@ enable_scsi_crypto
 with_glusterfs
 with_droplet
 with_rados
+with_cephfs
 with_systemd
 '
       ac_precious_vars='build_alias
@@ -1702,6 +1713,9 @@ Optional Features:
   --enable-build-dird     enable building of dird (Director) [default=yes]
   --enable-build-stored   enable building of stored (Storage daemon)
                           [default=yes]
+  --enable-dynamic-storage-backends
+                          enable dynamic loading of storage backends
+                          [default=no]
   --disable-conio         disable conio support [default=no]
   --enable-ipv6           enable ipv6 support [default=yes]
   --disable-readline      disable readline support [default=yes]
@@ -1747,6 +1761,7 @@ Optional Packages:
   --with-basename=RESNAME specify base resource name for daemons
   --with-hostname=RESNAME specify host name for daemons
   --with-scriptdir=PATH   specify path of Bareos scripts directory
+  --with-backenddir=PATH  specify path of Bareos backends directory
   --with-bsrdir=PATH      specify path of Bareos bsrs directory
   --with-logdir=PATH      specify path of Bareos logs directory
   --with-plugindir=PATH   specify path of Bareos plugins directory
@@ -1800,6 +1815,7 @@ Optional Packages:
   --with-glusterfs[=DIR]  Directory holding GLUSTERFS includes/libs
   --with-droplet[=DIR]    Directory holding DROPLET includes/libs
   --with-rados[=DIR]      Directory holding RADOS includes/libs
+  --with-cephfs[=DIR]     Directory holding CEPHFS includes/libs
   --with-systemd[=UNITDIR]
                           Include systemd support. UNITDIR is where systemd
                           system .service files are located, default is to ask
@@ -3352,6 +3368,9 @@ LIBBAREOSNDMP_LT_RELEASE=${LIBBAREOSNDMP_LT_RELEASE:-$VERSION}
 
 LIBBAREOSLMDB_LT_RELEASE=`sed -n -e 's/^#.*LIBBAREOSLMDB_LT_RELEASE.*"\(.*\)"$/\1/p' ${srcdir}/src/include/version.h`
 LIBBAREOSLMDB_LT_RELEASE=${LIBBAREOSLMDB_LT_RELEASE:-$VERSION}
+
+LIBBAREOSSD_LT_RELEASE=`sed -n -e 's/^#.*LIBBAREOSCATS_LT_RELEASE.*"\(.*\)"$/\1/p' ${srcdir}/src/include/version.h`
+LIBBAREOSSD_LT_RELEASE=${LIBBAREOSLMDB_LT_RELEASE:-$VERSION}
 
 echo "configuring for ${BAREOS} $VERSION ($DATE)"
 
@@ -22208,6 +22227,45 @@ fi
 
 
 
+use_dynamic_storage_backends=no
+# Check whether --enable-dynamic-storage_backends was given.
+if test "${enable_dynamic_storage_backends+set}" = set; then :
+  enableval=$enable_dynamic_storage_backends;
+       if test x$enableval = xyes; then
+          use_dynamic_storage_backends=yes
+
+$as_echo "#define HAVE_DYNAMIC_SD_BACKENDS 1" >>confdefs.h
+
+       fi
+
+
+fi
+
+
+if test "x$use_libtool" != "xyes" -a "x$use_dynamic_storage_backends" = "xyes"; then
+   echo ""
+   echo "You specified --enable-dynamic-storage-plugins but disabled libtool with --disable-libtool"
+   echo "We only support dynamic loading using libtool so either disable dynamic loading or enable libtool"
+   echo ""
+   echo "Aborting the configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi
+
+if test x$use_dynamic_storage_backends = xyes; then
+   NEEDED_DEVICE_API_SRCS=""
+   NEEDED_BACKEND_LIBS=""
+   SD_BACKENDS_DIR="src/stored/backends"
+else
+   NEEDED_DEVICE_API_SRCS="\$(AVAILABLE_DEVICE_API_SRCS)"
+   NEEDED_BACKEND_LIBS="\$(AVAILABLE_BACKEND_LIBS)"
+   SD_BACKENDS_DIR=""
+fi
+
+
+
+
 # Check whether --enable-conio was given.
 if test "${enable_conio+set}" = set; then :
   enableval=$enable_conio;
@@ -22217,7 +22275,6 @@ if test "${enable_conio+set}" = set; then :
 
 
 fi
-
 
 
 support_ipv6=yes
@@ -23850,6 +23907,30 @@ if test "${with_scriptdir+set}" = set; then :
 
 fi
 
+
+
+
+
+# ------------------------------------------
+# Where to place backenddir (backend library files)
+# ------------------------------------------
+backenddir=`eval echo ${libdir}`
+
+# Check whether --with-backenddir was given.
+if test "${with_backenddir+set}" = set; then :
+  withval=$with_backenddir;
+       if test "x$withval" != "xno" ; then
+	  backenddir=$withval
+       fi
+
+
+fi
+
+
+
+cat >>confdefs.h <<_ACEOF
+#define _PATH_BAREOS_BACKENDDIR "$backenddir"
+_ACEOF
 
 
 
@@ -31468,7 +31549,7 @@ fi
 
 RADOS_LIBS="-lrados"
 RADOS_INC=""
-have_ceph=no
+have_ceph_rados=no
 
 # Check whether --with-rados was given.
 if test "${with_rados+set}" = set; then :
@@ -31501,8 +31582,8 @@ fi
 
 
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for glfs_init in gfapi library" >&5
-$as_echo_n "checking for glfs_init in gfapi library... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for rados_create in rados library" >&5
+$as_echo_n "checking for rados_create in rados library... " >&6; }
 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
 /* end confdefs.h.  */
 
@@ -31524,13 +31605,13 @@ if ac_fn_c_try_link "$LINENO"; then :
 
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
-       have_ceph="yes"
+       have_ceph_rados="yes"
 
 else
 
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-       have_ceph="no"
+       have_ceph_rados="no"
 
 
 fi
@@ -31541,13 +31622,113 @@ LIBS="${saved_LIBS}"
 CFLAGS="${saved_CFLAGS}"
 CPPFLAGS="${saved_CPPFLAGS}"
 
-if test "x${have_ceph}" = "xyes"; then
+if test "x${have_ceph_rados}" = "xyes"; then
 
 $as_echo "#define HAVE_RADOS 1" >>confdefs.h
 
 else
    RADOS_LIBS=""
    RADOS_INC=""
+fi
+
+
+
+
+CEPHFS_LIBS="-lcephfs"
+CEPHFS_INC=""
+have_cephfs=no
+
+# Check whether --with-cephfs was given.
+if test "${with_cephfs+set}" = set; then :
+  withval=$with_cephfs; with_cephfs_directory=$withval
+
+fi
+
+
+if test "x${with_cephfs_directory}" != "xyes" && test x"${with_cephfs_directory}" != "x"; then
+   #
+   # Make sure the $with_cephfs_directory also makes sense
+   #
+   if test -d "${with_cephfs_directory}/lib" -a -d "${with_cephfs_directory}/include"; then
+      CEPHFS_LIBS="-L${with_cephfs_directory}/lib ${CEPHFS_LIBS}"
+      CEPHFS_INC="-I${with_cephfs_directory}/include ${CEPHFS_INC}"
+   fi
+fi
+
+saved_LIBS="${LIBS}"
+saved_CFLAGS="${CFLAGS}"
+saved_CPPFLAGS="${CPPFLAGS}"
+LIBS="${saved_LIBS} ${CEPHFS_LIBS}"
+CFLAGS="${saved_CFLAGS} ${CEPHFS_INC}"
+CPPFLAGS="${saved_CPPFLAGS} ${CEPHFS_INC}"
+
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+ac_fn_cxx_check_header_mongrel "$LINENO" "cephfs/libcephfs.h" "ac_cv_header_cephfs_libcephfs_h" "$ac_includes_default"
+if test "x$ac_cv_header_cephfs_libcephfs_h" = xyes; then :
+
+fi
+
+
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for ceph_create in cephfs library" >&5
+$as_echo_n "checking for ceph_create in cephfs library... " >&6; }
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+       #include <stdio.h>
+       #include <cephfs/libcephfs.h>
+
+int
+main ()
+{
+
+      struct ceph_mount_info *cmount;
+
+      ceph_create(&cmount, NULL);
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_link "$LINENO"; then :
+
+       { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+       have_cephfs="yes"
+
+else
+
+       { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+       have_cephfs="no"
+
+
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+LIBS="${saved_LIBS}"
+CFLAGS="${saved_CFLAGS}"
+CPPFLAGS="${saved_CPPFLAGS}"
+
+if test "x${have_cephfs}" = "xyes"; then
+
+$as_echo "#define HAVE_CEPHFS 1" >>confdefs.h
+
+else
+   CEPHFS_LIBS=""
+   CEPHFS_INC=""
 fi
 
 
@@ -31853,12 +32034,52 @@ osx)
    PFILES="${PFILES} \
       platforms/osx/Makefile"
   ;;
-debian)
+debian|ubuntu|univention)
    TAPEDRIVE="/dev/nst0"
    PSCMD="ps -e -o pid,command"
    PFILES="${PFILES} \
-    platforms/debian/Makefile \
-    platforms/debian/set_dbconfig_vars.sh"
+      debian/bareos-bat.install \
+      debian/bareos-bconsole.install \
+      debian/bareos-common.install \
+      debian/bareos-common.preinst \
+      debian/bareos-database-common.config \
+      debian/bareos-database-common.install \
+      debian/bareos-database-common.postinst \
+      debian/bareos-database-mysql.install \
+      debian/bareos-database-postgresql.install \
+      debian/bareos-database-sqlite3.install \
+      debian/bareos-database-tools.install \
+      debian/bareos-devel.install \
+      debian/bareos-director-python-plugin.install \
+      debian/bareos-director.bareos-dir.init \
+      debian/bareos-director.install \
+      debian/bareos-director.preinst \
+      debian/bareos-filedaemon-python-plugin.install \
+      debian/bareos-filedaemon.bareos-fd.init \
+      debian/bareos-filedaemon.install \
+      debian/bareos-filedaemon.preinst \
+      debian/bareos-storage-fifo.install \
+      debian/bareos-storage-python-plugin.install \
+      debian/bareos-storage-tape.install \
+      debian/bareos-storage.bareos-sd.init \
+      debian/bareos-storage.install \
+      debian/bareos-storage.preinst \
+      debian/bareos-tools.install \
+      debian/bareos-traymonitor.install \
+      platforms/debian/Makefile \
+      platforms/debian/set_dbconfig_vars.sh"
+   case "$DISTNAME" in
+      ubuntu)
+         PFILES="${PFILES} \
+            platforms/ubuntu/Makefile"
+         ;;
+      univention)
+         PFILES="${PFILES} \
+            debian/univention-bareos-schema.install \
+            debian/univention-bareos.install \
+            platforms/univention/Makefile"
+         ;;
+   esac
   ;;
 freebsd)
    VER=`echo $DISTVER | cut -c 1`
@@ -32018,22 +32239,6 @@ suse)
        platforms/suse/bareos-dir \
        platforms/suse/bareos"
   ;;
-ubuntu)
-   TAPEDRIVE="/dev/nst0"
-   PSCMD="ps -e -o pid,command"
-   PFILES="${PFILES} \
-    platforms/ubuntu/Makefile \
-    platforms/debian/Makefile \
-    platforms/debian/set_dbconfig_vars.sh"
-  ;;
-univention)
-   TAPEDRIVE="/dev/nst0"
-   PSCMD="ps -e -o pid,command"
-   PFILES="${PFILES} \
-     platforms/univention/Makefile \
-     platforms/debian/Makefile \
-     platforms/debian/set_dbconfig_vars.sh"
-  ;;
 unknown)
    TAPEDRIVE="/dev/nst0"
   ;;
@@ -32119,7 +32324,7 @@ if test X"$support_python" = "Xyes" ; then
 fi
 
 if test X"$have_scsi_crypto" = "Xyes" ; then
-   BUILD_SD_PLUGINS="${BUILD_SD_PLUGINS} scsicrypto-sd.la"
+   BUILD_SD_PLUGINS="${BUILD_SD_PLUGINS} scsicrypto-sd.la scsitapealert-sd.la"
 fi
 
 if test X"$have_zlib" = "Xyes" -o \
@@ -32129,6 +32334,30 @@ if test X"$have_zlib" = "Xyes" -o \
 fi
 
 
+
+
+
+if test x$use_libtool != xno; then
+   BUILD_SD_BACKENDS="libbareossd-fifo.la libbareossd-gentape.la libbareossd-tape.la"
+
+   if test X"$have_glusterfs" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-gfapi.la"
+   fi
+
+   if test X"$have_droplet" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-object.la"
+   fi
+
+   if test X"$have_ceph_rados" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-rados.la"
+   fi
+
+   if test X"$have_cephfs" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-cephfs.la"
+   fi
+else
+   BUILD_SD_BACKENDS=""
+fi
 
 
 
@@ -32145,7 +32374,7 @@ if test "x${subsysdir}" = "x${sbindir}" ; then
    exit 1
 fi
 
-ac_config_files="$ac_config_files autoconf/Make.common Makefile manpages/Makefile debian/bareos-common.preinst debian/bareos-database-common.config debian/bareos-database-common.postinst debian/bareos-filedaemon.bareos-fd.init debian/bareos-filedaemon.preinst debian/bareos-director.bareos-dir.init debian/bareos-director.preinst debian/bareos-storage.bareos-sd.init debian/bareos-storage.preinst scripts/bareos-config scripts/bareos-config-lib.sh scripts/bareos-explorer scripts/btraceback scripts/bconsole scripts/bareos scripts/bareos-ctl-dir scripts/bareos-ctl-fd scripts/bareos-ctl-sd scripts/devel_bareos scripts/Makefile scripts/logrotate scripts/mtx-changer scripts/disk-changer scripts/logwatch/Makefile scripts/logwatch/logfile.bareos.conf scripts/bat.console_apps src/Makefile src/include/host.h src/console/Makefile src/console/bconsole.conf src/qt-tray-monitor/bareos-tray-monitor.desktop src/qt-tray-monitor/tray-monitor.conf src/qt-tray-monitor/tray-monitor.pro src/qt-console/bat.conf src/qt-console/bat.desktop src/qt-console/bat.pro src/qt-console/install_conf_file src/dird/Makefile src/dird/bareos-dir.conf src/lib/Makefile src/stored/Makefile src/stored/bareos-sd.conf src/filed/Makefile src/filed/bareos-fd.conf src/cats/Makefile src/cats/make_catalog_backup.pl src/cats/make_catalog_backup src/cats/delete_catalog_backup src/cats/create_bareos_database src/cats/update_bareos_tables src/cats/grant_bareos_privileges src/cats/make_bareos_tables src/cats/drop_bareos_tables src/cats/drop_bareos_database src/cats/install-default-backend src/cats/ddl/versions.map src/findlib/Makefile src/lmdb/Makefile src/ndmp/Makefile src/tests/Makefile src/tools/Makefile src/plugins/filed/Makefile src/plugins/stored/Makefile src/plugins/dird/Makefile po/Makefile.in src/defaultconfigs/diskonly/bareos-sd.conf src/defaultconfigs/diskonly/bareos-dir.conf $PFILES"
+ac_config_files="$ac_config_files autoconf/Make.common Makefile manpages/Makefile scripts/bareos-config scripts/bareos-config-lib.sh scripts/bareos-explorer scripts/btraceback scripts/bconsole scripts/bareos scripts/bareos-ctl-dir scripts/bareos-ctl-fd scripts/bareos-ctl-sd scripts/devel_bareos scripts/Makefile scripts/logrotate scripts/mtx-changer scripts/disk-changer scripts/logwatch/Makefile scripts/logwatch/logfile.bareos.conf scripts/bat.console_apps src/Makefile src/include/host.h src/console/Makefile src/console/bconsole.conf src/qt-tray-monitor/bareos-tray-monitor.desktop src/qt-tray-monitor/tray-monitor.conf src/qt-tray-monitor/tray-monitor.pro src/qt-console/bat.conf src/qt-console/bat.desktop src/qt-console/bat.pro src/qt-console/install_conf_file src/dird/Makefile src/dird/bareos-dir.conf src/lib/Makefile src/stored/Makefile src/stored/bareos-sd.conf src/stored/backends/Makefile src/filed/Makefile src/filed/bareos-fd.conf src/cats/Makefile src/cats/make_catalog_backup.pl src/cats/make_catalog_backup src/cats/delete_catalog_backup src/cats/create_bareos_database src/cats/update_bareos_tables src/cats/grant_bareos_privileges src/cats/make_bareos_tables src/cats/drop_bareos_tables src/cats/drop_bareos_database src/cats/install-default-backend src/cats/ddl/versions.map src/findlib/Makefile src/lmdb/Makefile src/ndmp/Makefile src/tests/Makefile src/tools/Makefile src/plugins/filed/Makefile src/plugins/stored/Makefile src/plugins/dird/Makefile po/Makefile.in src/defaultconfigs/diskonly/bareos-sd.conf src/defaultconfigs/diskonly/bareos-dir.conf $PFILES"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -33235,15 +33464,6 @@ do
     "autoconf/Make.common") CONFIG_FILES="$CONFIG_FILES autoconf/Make.common" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "manpages/Makefile") CONFIG_FILES="$CONFIG_FILES manpages/Makefile" ;;
-    "debian/bareos-common.preinst") CONFIG_FILES="$CONFIG_FILES debian/bareos-common.preinst" ;;
-    "debian/bareos-database-common.config") CONFIG_FILES="$CONFIG_FILES debian/bareos-database-common.config" ;;
-    "debian/bareos-database-common.postinst") CONFIG_FILES="$CONFIG_FILES debian/bareos-database-common.postinst" ;;
-    "debian/bareos-filedaemon.bareos-fd.init") CONFIG_FILES="$CONFIG_FILES debian/bareos-filedaemon.bareos-fd.init" ;;
-    "debian/bareos-filedaemon.preinst") CONFIG_FILES="$CONFIG_FILES debian/bareos-filedaemon.preinst" ;;
-    "debian/bareos-director.bareos-dir.init") CONFIG_FILES="$CONFIG_FILES debian/bareos-director.bareos-dir.init" ;;
-    "debian/bareos-director.preinst") CONFIG_FILES="$CONFIG_FILES debian/bareos-director.preinst" ;;
-    "debian/bareos-storage.bareos-sd.init") CONFIG_FILES="$CONFIG_FILES debian/bareos-storage.bareos-sd.init" ;;
-    "debian/bareos-storage.preinst") CONFIG_FILES="$CONFIG_FILES debian/bareos-storage.preinst" ;;
     "scripts/bareos-config") CONFIG_FILES="$CONFIG_FILES scripts/bareos-config" ;;
     "scripts/bareos-config-lib.sh") CONFIG_FILES="$CONFIG_FILES scripts/bareos-config-lib.sh" ;;
     "scripts/bareos-explorer") CONFIG_FILES="$CONFIG_FILES scripts/bareos-explorer" ;;
@@ -33277,6 +33497,7 @@ do
     "src/lib/Makefile") CONFIG_FILES="$CONFIG_FILES src/lib/Makefile" ;;
     "src/stored/Makefile") CONFIG_FILES="$CONFIG_FILES src/stored/Makefile" ;;
     "src/stored/bareos-sd.conf") CONFIG_FILES="$CONFIG_FILES src/stored/bareos-sd.conf" ;;
+    "src/stored/backends/Makefile") CONFIG_FILES="$CONFIG_FILES src/stored/backends/Makefile" ;;
     "src/filed/Makefile") CONFIG_FILES="$CONFIG_FILES src/filed/Makefile" ;;
     "src/filed/bareos-fd.conf") CONFIG_FILES="$CONFIG_FILES src/filed/bareos-fd.conf" ;;
     "src/cats/Makefile") CONFIG_FILES="$CONFIG_FILES src/cats/Makefile" ;;
@@ -34944,6 +35165,7 @@ Configuration on `date`:
    Subsys directory:        ${subsysdir}
    Man directory:           ${mandir}
    Data directory:          ${datarootdir}
+   Backend directory:       ${backenddir}
    Plugin directory:        ${plugindir}
    C Compiler:              ${CC} ${CCVERSION}
    C++ Compiler:            ${CXX} ${CXXVERSION}
@@ -35003,7 +35225,8 @@ Configuration on `date`:
    SCSI Crypto support:     ${have_scsi_crypto}
    GLUSTERFS support:       ${have_glusterfs}
    DROPLET support:         ${have_droplet}
-   CEPH support:            ${have_ceph}
+   CEPH RADOS support:      ${have_ceph_rados}
+   CEPHFS support:          ${have_cephfs}
    Python support:          ${support_python} ${PYTHON_LIBS}
    systemd support:         ${support_systemd} ${SYSTEMD_UNITDIR}
    Batch insert enabled:    ${batch_insert_db_backends}
