Rework database scripting.
Having the actual DDL (Data Definition Language) in scripts is not very
flexible so we move all DDL into seperate files. We also dropped all
database specific scripting and as such the generic script now knows
for all supported database types what to do on create/update/grant and
drop.

You can also have a read-only user on your database that is allowed
to select stuff but not anything else that might be interesting for
Management Queries.

The update script now can also upgrade from a database that is several
versions old. For now that means you can upgrade from a Bacula database
to the first Bareos database schema and also to the new Database schema
we are introducing with this patch. For the future it means the script
will perform all needed updates for you if its has the wanted so called
conversion available (e.g. the way to go from one version to an other.)

We also added more functionality to the bareos-config script and splitted
the function into a bareos-config-lib which can be included by scripts
so they can get config information like the working dir etc. This is
already used in all the new database scripts.

We also no longer use explicit absolute pathnames for database utilities
but make sure the utility can be found via the PATH, if your PATH already
provides the utility it will be used and otherwise the value will be used
that was determined at compile time.

Fixes #236: Hardcoded path for postgres (verison) in scripts

diff --git a/src/cats/drop_bareos_database.in b/src/cats/drop_bareos_database.in
--- a/src/cats/drop_bareos_database.in
+++ b/src/cats/drop_bareos_database.in
@@ -1,11 +1,37 @@
 #!/bin/sh
 #
-#  Drop Bareos database -- works for whatever is configured,
-#  MySQL, SQLite, PostgreSQL, Ingres
+# BAREOS® - Backup Archiving REcovery Open Sourced
+#
+# Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
+# Copyright (C) 2013-2014 Bareos GmbH & Co. KG
+#
+# This program is Free Software; you can redistribute it and/or
+# modify it under the terms of version three of the GNU Affero General Public
+# License as published by the Free Software Foundation and included
+# in the file LICENSE.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+# Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+#
+# This scripts drops the Bareos tables for PostgreSQL, Ingres, MySQL, or SQLite.
 #
 
-default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
+#
+# Source the Bareos config functions.
+#
+. @scriptdir@/bareos-config-lib.sh
 
+db_name="${db_name:-@db_name@}"
+db_user="${db_user:-@db_user@}"
+default_db_type=`get_database_driver_default`
+working_dir=`get_working_dir`
 
 #
 # See if the first argument is a valid backend name.
@@ -13,24 +39,24 @@ default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
 #
 if [ $# -gt 0 ]; then
    case $1 in
-     sqlite3)
-       db_type=$1
-       shift
-       ;;
-     mysql)
-       db_type=$1
-       shift
-       ;;
-     postgresql)
-       db_type=$1
-       shift
-       ;;
-     ingres)
-       db_type=$1
-       shift
-       ;;
-     *)
-       ;;
+      sqlite3)
+         db_type=$1
+         shift
+         ;;
+      mysql)
+         db_type=$1
+         shift
+         ;;
+      postgresql)
+         db_type=$1
+         shift
+         ;;
+      ingres)
+         db_type=$1
+         shift
+         ;;
+      *)
+         ;;
    esac
 fi
 
@@ -42,4 +68,36 @@ if [ -z "${db_type}" ]; then
 fi
 
 echo "Dropping ${db_type} database"
-@scriptdir@/drop_${db_type}_database $*
+
+bindir=`get_database_utility_path ${db_type}`
+if [ ! -z "${bindir}" ]; then
+   PATH="$bindir:$PATH"
+fi
+PATH="$bindir:$PATH"
+
+case ${db_type} in
+   sqlite3)
+      rm -f ${working_dir}/${db_name}.db
+      retval=0
+      ;;
+   mysql)
+      mysql $* -e "DROP DATABASE ${db_name};"
+      retval=$?
+      ;;
+   postgresql)
+      dropdb $* ${db_name}
+      retval=$?
+      ;;
+   ingres)
+      destroydb -u${db_user} ${db_name}
+      retval=$?
+      ;;
+esac
+
+if [ ${retval} = 0 ]; then
+   echo "Drop of ${db_name} database succeeded."
+else
+   echo "Drop of ${db_name} database failed."
+fi
+
+exit ${retval}
diff --git a/src/cats/make_bareos_tables.in b/src/cats/make_bareos_tables.in
--- a/src/cats/make_bareos_tables.in
+++ b/src/cats/make_bareos_tables.in
@@ -1,11 +1,41 @@
 #!/bin/sh
 #
+# BAREOS® - Backup Archiving REcovery Open Sourced
+#
+# Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
+# Copyright (C) 2013-2014 Bareos GmbH & Co. KG
+#
+# This program is Free Software; you can redistribute it and/or
+# modify it under the terms of version three of the GNU Affero General Public
+# License as published by the Free Software Foundation and included
+# in the file LICENSE.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+# Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+#
 # This routine makes the appropriately configured
 # Bareos tables for PostgreSQL, Ingres, MySQL, or SQLite.
 #
 
-default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
+#
+# Source the Bareos config functions.
+#
+. @scriptdir@/bareos-config-lib.sh
 
+db_name="${db_name:-@db_name@}"
+db_user="${db_user:-@db_user@}"
+db_version=`get_database_version`
+bareos_sql_ddl=`get_database_ddl_dir`
+temp_sql_schema="/tmp/creates.sql.$$"
+default_db_type=`get_database_driver_default`
+working_dir=`get_working_dir`
 
 #
 # See if the first argument is a valid backend name.
@@ -13,24 +43,24 @@ default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
 #
 if [ $# -gt 0 ]; then
    case $1 in
-     sqlite3)
-       db_type=$1
-       shift
-       ;;
-     mysql)
-       db_type=$1
-       shift
-       ;;
-     postgresql)
-       db_type=$1
-       shift
-       ;;
-     ingres)
-       db_type=$1
-       shift
-       ;;
-     *)
-       ;;
+      sqlite3)
+         db_type=$1
+         shift
+         ;;
+      mysql)
+         db_type=$1
+         shift
+         ;;
+      postgresql)
+         db_type=$1
+         shift
+         ;;
+      ingres)
+         db_type=$1
+         shift
+         ;;
+      *)
+         ;;
    esac
 fi
 
@@ -42,4 +72,79 @@ if [ -z "${db_type}" ]; then
 fi
 
 echo "Making ${db_type} tables"
-@scriptdir@/make_${db_type}_tables $*
+
+case ${db_type} in
+   sqlite3)
+      sql_definitions="${bareos_sql_ddl}/creates/sqlite3.sql"
+      ;;
+   mysql)
+      sql_definitions="${bareos_sql_ddl}/creates/mysql.sql"
+      ;;
+   postgresql)
+      sql_definitions="${bareos_sql_ddl}/creates/postgresql.sql"
+      ;;
+   ingres)
+      sql_definitions="${bareos_sql_ddl}/creates/ingres.sql"
+      ;;
+   *)
+      echo "Unknown database type $1"
+      exit 1
+      ;;
+esac
+
+if [ ! -z "${sql_definitions}" ]; then
+   if [ ! -f ${sql_definitions} ]; then
+      echo "Unable to open database table definitions in file ${sql_definitions}"
+      exit 1
+   fi
+
+   if ! get_translated_sql_file ${sql_definitions} > ${temp_sql_schema}; then
+        echo "Failed to translate SQL definitions in ${sql_definitions}"
+        exit 1
+   fi
+fi
+
+bindir=`get_database_utility_path ${db_type}`
+if [ ! -z "${bindir}" ]; then
+   PATH="$bindir:$PATH"
+fi
+
+case ${db_type} in
+   sqlite3)
+      sqlite3 $* ${working_dir}/${db_name}.db < ${temp_sql_schema}
+      chmod 640 ${working_dir}/${db_name}.db
+      retval=0
+      ;;
+   mysql)
+      mysql $* --database=${db_name} -f < ${temp_sql_schema}
+      retval=$?
+      if test $retval = 0; then
+         echo "Creation of Bareos MySQL tables succeeded."
+      else
+         echo "Creation of Bareos MySQL tables failed."
+      fi
+      ;;
+   postgresql)
+      psql -f ${temp_sql_schema} -d ${db_name} $*
+      retval=$?
+      if test $retval = 0; then
+         echo "Creation of Bareos PostgreSQL tables succeeded."
+      else
+         echo "Creation of Bareos PostgreSQL tables failed."
+      fi
+      ;;
+   ingres)
+      sql -u${db_user} $* ${db_name} < ${temp_sql_schema}
+
+      retval=$?
+      if test $retval = 0; then
+         echo "Creation of Bareos Ingres tables succeeded."
+      else
+         echo "Creation of Bareos Ingres tables failed."
+      fi
+      ;;
+esac
+
+rm -f ${temp_sql_schema}
+
+exit ${retval}
