adapted tls-passive-test to new structure.
Fixes problem with expired certicates.

diff --git a/tests/1-example-test b/tests/1-example-test
--- a/tests/1-example-test
+++ b/tests/1-example-test
@@ -45,6 +45,8 @@ start_test
 # ${tmp}/bconcmds lists the bconsole commands executed by "run_bareos"
 cat <<END_OF_DATA >${tmp}/bconcmds
 messages
+@$out ${tmp}/log-config.out
+show client=${Client}
 @$out ${tmp}/log1.out w
 label storage=File1 pool=Default volume=TestVolume001
 run job=$JobName storage=File1 yes
@@ -75,6 +77,10 @@ check_for_zombie_jobs storage=File1 client=${Client}
 # stop bareos
 stop_bareos
 
+# check log files for common error messages
+check_log ${tmp}/log1.out
+check_log ${tmp}/log2.out
+
 # check tmp/log1.out and tmp/log2.out for errors
 check_two_logs
 
@@ -84,6 +90,11 @@ check_restore_diff ${BackupDirectory}
 # do some manual testing
 if [ ! -d ${BackupDirectory} ]; then
     set_error "Directory ${BackupDirectory} does not exists any more."
+fi
+
+check_log ${tmp}/log-config.out
+if ! grep -qi "TlsRequire = yes" ${tmp}/log-config.out; then
+   set_error "client is not configured to use TLS."
 fi
 
 # end tests and check for error codes
diff --git a/tests/tls-passive-test b/tests/tls-passive-test
--- a/tests/tls-passive-test
+++ b/tests/tls-passive-test
@@ -1,44 +1,57 @@
 #!/bin/sh
-#
-# Run a simple backup of the Bareos build directory with TLS
-#   communications code enabled then restore it.
-#
-TestName="tls-passive-test"
-JobName=tls
+
 . scripts/functions
 
-scripts/cleanup
-#scripts/copy-tls-confs
+# Define the Name of the test as "TestName".
+# Should be the same as the filename, therefore we use the filename as default.
+TestName="`basename $0`"
+#TestName="1-example-test"
 
-/bin/cp -f scripts/tls-bareos-dir-passive.conf bin/bareos-dir.conf
-/bin/cp -f scripts/tls-bareos-sd.conf bin/bareos-sd.conf
-/bin/cp -f scripts/tls-bareos-fd-passive.conf bin/bareos-fd.conf
-/bin/cp -f scripts/test-console.conf bin/bconsole.conf
-/bin/cp -f scripts/test-console.conf bin/bat.conf
-/bin/cp -f scripts/tls-CA.pem bin/tls-CA.pem
-/bin/cp -f scripts/tls-cert.pem bin/tls-cert.pem
+# set other test specific variables
+Client=tls-passive-fd
+JobName=backup-bareos-fd
 
+# Directory to backup.
+# This example uses a subdirectory of the bareos source/build directory,
+# that contains some file but isn't to large.
+BackupDirectory="${cwd}/build/src/tests/"
 
-echo "${cwd}/build" >${cwd}/tmp/file-list
+# Remove old configuration, working and tmp files. Setup the database.
+cleanup
 
-change_jobname CompressedTest $JobName
+# Config files will be copied to required location.
+# Base configuration files come from the
+# configs/BASE/ directory, see
+# configs/BASE/README.txt for an overview of the provides resources.
+# Store your additonal resources to
+# configs/$TestName.
+# It is also possible to overwrite resources from configs/BASE.
+# If you define a full config file (instead of config files for individual resources),
+# only these will be taken.
+copy_configs
+
+# the default fileset FS_TESTJOB backups all file and directories defined in "${tmp}/file-list".
+echo "${BackupDirectory}" >${tmp}/file-list
+
+# start the test
 start_test
 
-cat <<END_OF_DATA >tmp/bconcmds
+# ${tmp}/bconcmds lists the bconsole commands executed by "run_bareos"
+cat <<END_OF_DATA >${tmp}/bconcmds
 messages
-@$out tmp/log1.out
+@$out ${tmp}/log-config.out
+show client=${Client}
+@$out ${tmp}/log1.out w
 status all
-status all
-messages
-label storage=File volume=TestVolume001 pool=Default
-run job=$JobName storage=File yes
+label storage=File1 pool=Default volume=TestVolume001
+run job=$JobName client=${Client} fileset=compression-fileset storage=File1 yes
 wait
 messages
 @#
 @# now do a restore
 @#
-@$out tmp/log2.out
-restore where=${cwd}/tmp/bareos-restores select storage=File
+@$out ${tmp}/log2.out w
+restore client=${Client} where=${tmp}/bareos-restores select storage=File1
 unmark *
 mark *
 done
@@ -48,10 +61,39 @@ messages
 quit
 END_OF_DATA
 
+# Start the bareos daemons
+# and run the bconsole commands from ${tmp}/bconcmds
+# Further bconsole commands can be executed by "run_bconsole".
 run_bareos
-check_for_zombie_jobs storage=File
+
+# verify that all are terminated
+check_for_zombie_jobs storage=File1 client=${Client}
+
+# stop bareos
 stop_bareos
 
+# check log files for common error messages
+check_log ${tmp}/log-config.out
+if ! grep -qi "Passive = yes"  ${tmp}/log-config.out; then
+   set_error "client is not configured as passive client."
+fi
+if ! grep -qi "TlsRequire = yes" ${tmp}/log-config.out; then
+   set_error "client is not configured to use TLS."
+fi
+
+check_log ${tmp}/log1.out
+check_log ${tmp}/log2.out
+
+# check tmp/log1.out and tmp/log2.out for errors
 check_two_logs
-check_restore_diff
+
+# check for differences between original files and restored files
+check_restore_diff ${BackupDirectory}
+
+# do some manual testing
+if [ ! -d ${BackupDirectory} ]; then
+    set_error "Directory ${BackupDirectory} does not exists any more."
+fi
+
+# end tests and check for error codes
 end_test
diff --git a/tests/tls-test b/tests/tls-test
--- a/tests/tls-test
+++ b/tests/tls-test
@@ -39,6 +39,8 @@ start_test
 # ${tmp}/bconcmds lists the bconsole commands executed by "run_bareos"
 cat <<END_OF_DATA >${tmp}/bconcmds
 messages
+@$out ${tmp}/log-config.out
+show client=${Client}
 @$out ${tmp}/log1.out w
 status all
 label storage=File1 pool=Default volume=TestVolume001
@@ -69,6 +71,15 @@ check_for_zombie_jobs storage=File1 client=${Client}
 
 # stop bareos
 stop_bareos
+
+# check log files for common error messages
+check_log ${tmp}/log-config.out
+if ! grep -qi "TlsRequire = yes" ${tmp}/log-config.out; then
+   set_error "client is not configured to use TLS."
+fi
+
+check_log ${tmp}/log1.out
+check_log ${tmp}/log2.out
 
 # check tmp/log1.out and tmp/log2.out for errors
 check_two_logs
