systemtests: fix shellcheck paths

diff --git a/systemtests/tests/checkpoints/testrunner-checkpoints-on-kill b/systemtests/tests/checkpoints/testrunner-checkpoints-on-kill
--- a/systemtests/tests/checkpoints/testrunner-checkpoints-on-kill
+++ b/systemtests/tests/checkpoints/testrunner-checkpoints-on-kill
@@ -9,10 +9,10 @@ set -u
 TestName="$(basename "$(pwd)")"
 export TestName
 
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
 
 start_test
@@ -21,15 +21,15 @@ slowjob="slow-backup-bareos-fd"
 
 for daemon in "dir" "sd" "fd"; do
 
-    backup_log="$tmp"/kill-"$daemon"-backup-checkpoints.out
-    restore_log="$tmp"/kill-"$daemon"-restore-checkpoints.out
-    restore_directory="$tmp"/kill-"$daemon"-checkpoint-restores
+  backup_log="$tmp"/kill-"$daemon"-backup-checkpoints.out
+  restore_log="$tmp"/kill-"$daemon"-restore-checkpoints.out
+  restore_directory="$tmp"/kill-"$daemon"-checkpoint-restores
 
-    rm -f "$backup_log"
-    rm -f "$restore_log"
-    rm -rf "$restore_directory"
+  rm -f "$backup_log"
+  rm -f "$restore_log"
+  rm -rf "$restore_directory"
 
-cat <<END_OF_DATA >"$tmp/bconcmds"
+  cat <<END_OF_DATA >"$tmp/bconcmds"
 @$out ${NULL_DEV}
 messages
 @$out $backup_log
@@ -37,58 +37,57 @@ run job=$slowjob fileset=bigfileset level=Full yes
 quit
 END_OF_DATA
 
-    run_bconsole
+  run_bconsole
 
-    timeout=0
-    timed_checkpoint=""
-    volume_checkpoint=""
+  timeout=0
+  timed_checkpoint=""
+  volume_checkpoint=""
 
-    while [[ ${timeout} -lt 30 ]] && [[ -z $timed_checkpoint || -z $volume_checkpoint ]]
-    do
+  while [[ ${timeout} -lt 30 ]] && [[ -z $timed_checkpoint || -z $volume_checkpoint ]]; do
 
-        timed_checkpoint=$(grep -m 1 'Doing timed backup checkpoint. Next checkpoint in 3 seconds' "$messagesfile" || : )
-        volume_checkpoint=$(grep -m 1 'Volume changed, doing checkpoint:' "$messagesfile" || : )
-        sleep 1
-        ((++timeout))
-    done #end while
+    timed_checkpoint=$(grep -m 1 'Doing timed backup checkpoint. Next checkpoint in 3 seconds' "$messagesfile" || :)
+    volume_checkpoint=$(grep -m 1 'Volume changed, doing checkpoint:' "$messagesfile" || :)
+    sleep 1
+    ((++timeout))
+  done #end while
 
-    # Check that a timed checkpoint was triggered
-    if [[ -z $timed_checkpoint ]]; then
-        echo "ERROR: Timed checkpoint was not triggered!"
-        estat=1;
-    fi
+  # Check that a timed checkpoint was triggered
+  if [[ -z $timed_checkpoint ]]; then
+    echo "ERROR: Timed checkpoint was not triggered!"
+    estat=1
+  fi
 
-    # Check that a checkpoint happened on a volume change
-    if [[ -z $volume_checkpoint ]]; then
-        echo "ERROR: Checkpoint was not triggered on volume changes!"
-        estat=2;
-    fi
+  # Check that a checkpoint happened on a volume change
+  if [[ -z $volume_checkpoint ]]; then
+    echo "ERROR: Checkpoint was not triggered on volume changes!"
+    estat=2
+  fi
 
-    slowjobid=$(grep 'Job queued. JobId=' "$backup_log" | sed -n -e 's/^.*JobId=//p')
+  slowjobid=$(grep 'Job queued. JobId=' "$backup_log" | sed -n -e 's/^.*JobId=//p')
 
-    if [ "$daemon" == "fd" ]; then
-        echo "Killing the FD"
-        pkill -KILL -f "${BAREOS_FILEDAEMON_BINARY}"
-        sleep 3
-        "${rscripts}"/bareos-ctl-fd start
-    fi
+  if [ "$daemon" == "fd" ]; then
+    echo "Killing the FD"
+    pkill -KILL -f "${BAREOS_FILEDAEMON_BINARY}"
+    sleep 3
+    "${rscripts}"/bareos-ctl-fd start
+  fi
 
-    if [ "$daemon" == "sd" ]; then
+  if [ "$daemon" == "sd" ]; then
 
-        echo "Killing the SD"
-        pkill -KILL -f "${BAREOS_STORAGEDAEMON_BINARY}"
-        sleep 3
-        "${rscripts}"/bareos-ctl-sd start
-    fi
-    if [ "$daemon" == "dir" ]; then
+    echo "Killing the SD"
+    pkill -KILL -f "${BAREOS_STORAGEDAEMON_BINARY}"
+    sleep 3
+    "${rscripts}"/bareos-ctl-sd start
+  fi
+  if [ "$daemon" == "dir" ]; then
 
-        echo "Killing the DIR"
-        pkill -KILL -f "${BAREOS_DIRECTOR_BINARY}"
-        sleep 3
-        "${rscripts}"/bareos-ctl-dir start
-    fi
+    echo "Killing the DIR"
+    pkill -KILL -f "${BAREOS_DIRECTOR_BINARY}"
+    sleep 3
+    "${rscripts}"/bareos-ctl-dir start
+  fi
 
-cat <<END_OF_DATA >"$tmp/bconcmds"
+  cat <<END_OF_DATA >"$tmp/bconcmds"
 @$out $backup_log
 wait
 messages
@@ -99,17 +98,17 @@ messages
 quit
 END_OF_DATA
 
-    run_bconsole
+  run_bconsole
 
-    # Check that the backup was halted
-    expect_not_grep "Termination:.*Backup OK" \
-                    "$backup_log"\
-                    "Backup was run successfully. The backup should fail."
+  # Check that the backup was halted
+  expect_not_grep "Termination:.*Backup OK" \
+    "$backup_log" \
+    "Backup was run successfully. The backup should fail."
 
-    # Check that the restore works fine
-    expect_grep "Termination:.*Restore OK" \
-                "$restore_log" \
-                "Restore job did not go well!"
+  # Check that the restore works fine
+  expect_grep "Termination:.*Restore OK" \
+    "$restore_log" \
+    "Restore job did not go well!"
 
 done #end for
 
diff --git a/systemtests/tests/gfapi-fd/testrunner b/systemtests/tests/gfapi-fd/testrunner
--- a/systemtests/tests/gfapi-fd/testrunner
+++ b/systemtests/tests/gfapi-fd/testrunner
@@ -2,56 +2,53 @@
 set -e
 set -u
 
-
 TestName="$(basename "$(pwd)")"
 export TestName
 
 JobName=backup-bareos-fd
 
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 
 CTEST_SKIP_RETURN_CODE=77
 
 # check if required sudo commands can be executed, otherwise skip test
 for SUDO_CMD in mount umount rm; do
-  if ! "${SUDO}" -l "${SUDO_CMD}" >/dev/null 2>&1 ; then
-  echo "cannot execute $SUDO_CMD via sudo" && exit "${CTEST_SKIP_RETURN_CODE}"
+  if ! "${SUDO}" -l "${SUDO_CMD}" >/dev/null 2>&1; then
+    echo "cannot execute $SUDO_CMD via sudo" && exit "${CTEST_SKIP_RETURN_CODE}"
   fi
 done
 
-umount_glusterfs(){
-#  make sure umount is successful
-tries=60
-echo "umounting glusterfs..."
-while "${SUDO}" mount | grep "${tmp}/data" >/dev/null 2>&1; do
-  [ $((tries-=1)) -eq 0 ] && {
-    echo "could not umount glustrfs ${tmp}/data"
-    exit 1
-  }
-  "${SUDO}" umount "${tmp}/data"
-  echo -n "."
-  sleep 1
-done
+umount_glusterfs()
+{
+  #  make sure umount is successful
+  tries=60
+  echo "umounting glusterfs..."
+  while "${SUDO}" mount | grep "${tmp}/data" >/dev/null 2>&1; do
+    [ $((tries -= 1)) -eq 0 ] && {
+      echo "could not umount glustrfs ${tmp}/data"
+      exit 1
+    }
+    "${SUDO}" umount "${tmp}/data"
+    echo -n "."
+    sleep 1
+  done
 }
 
 trap umount_glusterfs EXIT
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
-
 
 umount_glusterfs
 "${rscripts}"/cleanup
 "${rscripts}"/setup
 
-
 # Directory to backup.
 # This directory will be created by setup_data "$@"().
 BackupDirectory="${tmp}/data"
 
-
-[ -d "${tmp}/data" ] ||  mkdir -p "${tmp}/data"
+[ -d "${tmp}/data" ] || mkdir -p "${tmp}/data"
 "${SUDO}" mount -t glusterfs "${gfapi_fd_host}:/${gfapi_fd_testvolume}" "${tmp}/data"
 
 "${SUDO}" rm -Rvf "${tmp}/data"/*
@@ -108,7 +105,6 @@ run_bareos "$@"
 check_for_zombie_jobs storage=File
 stop_bareos
 
-
 #[ -d "${tmp}/bareos-restores" ] && rm -Rvf "${tmp}/bareos-restores"
 #mkdir -p "${tmp}"/bareos-restores/"${tmp}/data"
 #now move the data away from gluster volume, restore and compare to moved data
@@ -138,8 +134,8 @@ run_bareos "$@"
 check_for_zombie_jobs storage=File
 
 check_two_logs
-ln -s  "${tmp}" "${tmp}/bareos-restores"
-check_recursive_diff_of_dirs $tmp/data/weird-files  $tmp/data/$tmp/bareos-restores/data/weird-files
+ln -s "${tmp}" "${tmp}/bareos-restores"
+check_recursive_diff_of_dirs $tmp/data/weird-files $tmp/data/$tmp/bareos-restores/data/weird-files
 
 umount_glusterfs
 end_test
diff --git a/systemtests/tests/py3plug-fd-contrib-bareos_tasks_mariadb/testrunner-default b/systemtests/tests/py3plug-fd-contrib-bareos_tasks_mariadb/testrunner-default
--- a/systemtests/tests/py3plug-fd-contrib-bareos_tasks_mariadb/testrunner-default
+++ b/systemtests/tests/py3plug-fd-contrib-bareos_tasks_mariadb/testrunner-default
@@ -9,19 +9,19 @@ set -u
 TestName="$(basename "$(pwd)")"
 export TestName
 
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 
 JobName=backup-bareos-fd
 test_db_name="${db_name}_test"
 RESTORE_DIR="${tmp}/bareos-restores/@MARIADB/"
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
 
 skip_if_root
 
-#shellcheck source=../scripts/mariadb.sh
+#shellcheck source=../../scripts/mariadb.sh
 . "${rscripts}"/mariadb.sh
 
 start_test
@@ -29,11 +29,11 @@ start_test
 mariadb_init
 mariadb_server_start
 
-${MARIADB_CLIENT} <<< "create database ${test_db_name}"
-${MARIADB_CLIENT} "${test_db_name}" <<< "CREATE TABLE test ( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, data VARCHAR(100), created TIMESTAMP DEFAULT NOW())"
-${MARIADB_CLIENT} "${test_db_name}" <<< "insert into test (data) VALUES ('test entry 1') "
+${MARIADB_CLIENT} <<<"create database ${test_db_name}"
+${MARIADB_CLIENT} "${test_db_name}" <<<"CREATE TABLE test ( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, data VARCHAR(100), created TIMESTAMP DEFAULT NOW())"
+${MARIADB_CLIENT} "${test_db_name}" <<<"insert into test (data) VALUES ('test entry 1') "
 
-cat << END_OF_DATA > "${tmp}/bconcmds"
+cat <<END_OF_DATA >"${tmp}/bconcmds"
 @$out ${NULL_DEV}
 messages
 @$out ${tmp}/log1.out
@@ -50,11 +50,11 @@ echo "Run first full"
 run_bconsole
 expect_grep "Backup OK" "${tmp}/log1.out" "Full Backup not found!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # insert data and run another job
-${MARIADB_CLIENT} "${test_db_name}" <<< "insert into test (data) VALUES ('test entry 2') "
+${MARIADB_CLIENT} "${test_db_name}" <<<"insert into test (data) VALUES ('test entry 2') "
 
 cat <<END_OF_DATA2 >"${tmp}/bconcmds"
 @$out ${NULL_DEV}
@@ -93,26 +93,26 @@ expect_grep "Restore OK" "${tmp}/log3.out" "Restore OK not found!"
 # Check if some files are restored
 ls -lR "${RESTORE_DIR}"
 if [ -z "$(ls -A "${RESTORE_DIR}")" ]; then
-       echo "No restore data found"
-       estat=1
+  echo "No restore data found"
+  estat=1
 fi
 
 # delete database
 echo "drop database ${test_db_name}"
-${MARIADB_CLIENT} <<< "DROP DATABASE ${test_db_name};"
+${MARIADB_CLIENT} <<<"DROP DATABASE ${test_db_name};"
 
-if ${MARIADB_CLIENT} "${test_db_name}" <<< "SELECT * FROM test WHERE id=2;" 2>/dev/null; then
-    echo "database ${test_db_name} should be deleted and command should fail."
-    estat=2
+if ${MARIADB_CLIENT} "${test_db_name}" <<<"SELECT * FROM test WHERE id=2;" 2>/dev/null; then
+  echo "database ${test_db_name} should be deleted and command should fail."
+  estat=2
 fi
 
 # restore db
 echo "restore database ${test_db_name}"
-${MARIADB_CLIENT} < "${RESTORE_DIR}/dump-database-${test_db_name}.sql"
+${MARIADB_CLIENT} <"${RESTORE_DIR}/dump-database-${test_db_name}.sql"
 
-if ! ${MARIADB_CLIENT} "${test_db_name}" <<< "SELECT * FROM test WHERE id=2;" >/dev/null; then
-    echo "test entry not found after restore"
-    estat=3
+if ! ${MARIADB_CLIENT} "${test_db_name}" <<<"SELECT * FROM test WHERE id=2;" >/dev/null; then
+  echo "test entry not found after restore"
+  estat=3
 fi
 mariadb_server_stop
 
diff --git a/systemtests/tests/py3plug-fd-postgresql/testrunner-debian b/systemtests/tests/py3plug-fd-postgresql/testrunner-debian
--- a/systemtests/tests/py3plug-fd-postgresql/testrunner-debian
+++ b/systemtests/tests/py3plug-fd-postgresql/testrunner-debian
@@ -20,29 +20,29 @@ TestName="$(basename "$(pwd)")"
 export TestName
 
 JobName="backup-bareos-fd"
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 . /etc/os-release
-if ([ -z "${ID}" ] || [ "${ID}" != "debian" ] && [ "${ID}" != "ubuntu" ]);then
- echo "${TestName} test skipped: not debian/ubuntu"
- exit 77;
+if ([ -z "${ID}" ] || [ "${ID}" != "debian" ] && [ "${ID}" != "ubuntu" ]); then
+  echo "${TestName} test skipped: not debian/ubuntu"
+  exit 77
 fi
 if [ $UID -ne 0 ]; then
-# skip test
- echo "${TestName} test skipped: needs to be root to use pg_*cluster system tools"
- exit 77;
+  # skip test
+  echo "${TestName} test skipped: needs to be root to use pg_*cluster system tools"
+  exit 77
 fi
 
 # We need the server version that will be used
 PG_VERSION=$(pg_lsclusters --no-header | awk -F " " '{print $1}' | sort -n | head -n 1)
 if [ ${PG_VERSION} -lt 10 ]; then
-# skip test
- echo "${TestName} test skipped: not compatible with PG <= 10"
- exit 77;
+  # skip test
+  echo "${TestName} test skipped: not compatible with PG <= 10"
+  exit 77
 fi
-if [ $(pg_lsclusters ${PG_VERSION} regress | grep "regress" -c) -eq 1 ];then
-    pg_dropcluster ${PG_VERSION} regress --stop
-    rm -rf /var/tmp/postgresql/wal_archives
+if [ $(pg_lsclusters ${PG_VERSION} regress | grep "regress" -c) -eq 1 ]; then
+  pg_dropcluster ${PG_VERSION} regress --stop
+  rm -rf /var/tmp/postgresql/wal_archives
 fi
 
 pg_createcluster ${PG_VERSION} regress
@@ -61,7 +61,7 @@ chown postgres:postgres /var/tmp/postgresql/wal_archives
   echo "log_error_verbosity = verbose"
   echo "log_statement = 'all'"
   echo "log_temp_files = 0"
-} >> /etc/postgresql/${PG_VERSION}/regress/conf.d/regress.conf
+} >>/etc/postgresql/${PG_VERSION}/regress/conf.d/regress.conf
 pg_ctlcluster ${PG_VERSION} regress start
 
 # setup local database server
@@ -78,7 +78,7 @@ insert into t (text, created_on) values ('test for FULL backup', current_timesta
 select * from t;
 "
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
 
 start_test
@@ -106,7 +106,7 @@ run_bconsole
 expect_grep "Backup OK" "${tmp}/dlog1.out" "Full Backup not found!"
 
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 # Now add data to the database and run an incremental job
 ${PSQL} ${DBNAME} -c "insert into t (text, created_on) values ('test for INCR backup', current_timestamp)"
@@ -127,7 +127,7 @@ run_bconsole
 expect_grep "Backup OK" "${tmp}/dlog2.out" "First Incremental Backup not found!"
 
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # run another Incr without db changes - should result in empty backup job (only restore object)
@@ -146,7 +146,7 @@ run_bconsole
 expect_grep "Backup OK" "${tmp}/dlog3.out" "2nd Incremental Backup not found!"
 
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # Now stop database and try a restore
@@ -169,7 +169,7 @@ run_bconsole
 
 expect_grep "Restore OK" "${tmp}/dlog4.out" "Restore Backup not ok!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 check_for_zombie_jobs storage=File
 
@@ -180,7 +180,7 @@ check_two_logs "${tmp}/dlog1.out" "${tmp}/dlog4.out"
 # use either recovery.conf or recovery.signal
 # Those files should exist after restore, the plugin create them
 # postgres 11 and lower
-if (( ${PG_VERSION} < 12 )); then
+if ((${PG_VERSION} < 12)); then
   echo "PG_VERSION is ${PG_VERSION} so lower than 12, using recovery.conf"
   recovery_file="/var/lib/postgresql/${PG_VERSION}/regress/recovery.conf"
 else
@@ -188,15 +188,15 @@ else
   echo "PG_VERSION is ${PG_VERSION} so 12+, using postgresql.conf and recovery.signal"
   recovery_file="/var/lib/postgresql/${PG_VERSION}/regress/recovery.signal"
 fi
-if [ ! -f "${recovery_file}" ];then
- echo "${TestName} ${recovery_file} is missing from restore"
- exit 1;
+if [ ! -f "${recovery_file}" ]; then
+  echo "${TestName} ${recovery_file} is missing from restore"
+  exit 1
 fi
 restore_command="restore_command = 'cp /var/tmp/postgresql/wal_archives/%f %p'"
-if (( ${PG_VERSION} < 12 )); then
-  echo "${restore_command}" >> "${recovery_file}"
+if ((${PG_VERSION} < 12)); then
+  echo "${restore_command}" >>"${recovery_file}"
 else
-  echo "${restore_command}" >> "/etc/postgresql/${PG_VERSION}/regress/conf.d/restore.conf"
+  echo "${restore_command}" >>"/etc/postgresql/${PG_VERSION}/regress/conf.d/restore.conf"
 fi
 
 pg_lsclusters ${PG_VERSION} regress
@@ -204,31 +204,32 @@ pg_lsclusters ${PG_VERSION} regress
 echo ""
 echo "Restart restored pg_cluster"
 
-if ! pg_ctlcluster ${PG_VERSION} regress start;then
+if ! pg_ctlcluster ${PG_VERSION} regress start; then
   echo "cluster restart failed after restore"
-   estat=1
+  estat=1
 fi
 
 i=0
-until ${PSQL} ${DBNAME} -c "select * from t" | grep "for INCR"  > ${tmp}/sql.log  ; do
+until ${PSQL} ${DBNAME} -c "select * from t" | grep "for INCR" >${tmp}/sql.log; do
   echo "waiting for query to succeed"
   sleep 1
-  i=$((i+1))
-  if [ $i -gt 10 ]; then echo "timeout waiting for query after recovery"; exit 1; fi
+  i=$((i + 1))
+  if [ $i -gt 10 ]; then
+    echo "timeout waiting for query after recovery"
+    exit 1
+  fi
 done
-if (grep -q "for INCR" ${tmp}/sql.log)
-then
-   estat=0
+if (grep -q "for INCR" ${tmp}/sql.log); then
+  estat=0
 else
-   echo "Error: Database rows not found"
-   estat=1
+  echo "Error: Database rows not found"
+  estat=1
 fi
 
-if [ $(pg_lsclusters ${PG_VERSION} regress | grep "regress" -c) -eq 1 ];then
-    echo "cluster recovery completed"
-    pg_dropcluster ${PG_VERSION} regress --stop
-    rm -rf /var/tmp/postgresql/wal_archives
+if [ $(pg_lsclusters ${PG_VERSION} regress | grep "regress" -c) -eq 1 ]; then
+  echo "cluster recovery completed"
+  pg_dropcluster ${PG_VERSION} regress --stop
+  rm -rf /var/tmp/postgresql/wal_archives
 fi
-
 
 end_test
