systemtest: modified system:multiplied_device
system:multiplied_device now also tests the `delete storage` command

diff --git a/systemtests/tests/multiplied-device/testrunner b/systemtests/tests/multiplied-device/testrunner
--- a/systemtests/tests/multiplied-device/testrunner
+++ b/systemtests/tests/multiplied-device/testrunner
@@ -67,7 +67,30 @@ END_OF_DATA
 
 run_bareos "$@"
 check_for_zombie_jobs storage=File
+
+# rename the storages instead of deleting them
+mv ./etc/bareos/bareos-dir.d/storage/fakestorage1.conf ./etc/bareos/bareos-dir.d/storage/fakestorage1.conf_backup
+mv ./etc/bareos/bareos-dir.d/storage/fakestorage2.conf ./etc/bareos/bareos-dir.d/storage/fakestorage2.conf_backup
+
+cat <<END_OF_DATA >"$tmp/bconcmds"
+@$out $tmp/log4.out
+label volume=fakevolume storage=fakestorage1 pool=Full
+reload
+delete storage=File
+delete storage=fakestorage1
+messages
+delete storage=fakestorage2
+messages
+quit
+END_OF_DATA
+
+run_bconsole
 stop_bareos
+
+# rename files to be able to run the test again later
+mv ./etc/bareos/bareos-dir.d/storage/fakestorage1.conf_backup ./etc/bareos/bareos-dir.d/storage/fakestorage1.conf
+mv ./etc/bareos/bareos-dir.d/storage/fakestorage2.conf_backup ./etc/bareos/bareos-dir.d/storage/fakestorage2.conf
+
 
 check_two_logs
 check_restore_diff ${BackupDirectory}
@@ -122,4 +145,34 @@ for i in 1 2 3; do
     estat=3
   fi
 done
+
+# check if the relabel went correctly
+grep "3000 OK label. VolBytes=... Volume=\"fakevolume\" Device=\"FileStorage\" (storage)" "${tmp}"/log4.out >/dev/null 2>&1
+if test $? -ne 0 ; then
+  echo "The fakevolume relabel failed."
+  estat=1;
+fi
+
+# make sure exact number of orphaned storages is found
+grep "Found 2 orphaned Storage records" "${tmp}"/log4.out >/dev/null 2>&1
+if test $? -ne 0 ; then
+  echo "The delete command failed to find the exact number of fakestorages."
+  estat=1;
+fi
+
+# make sure storage 'File' cannot be deleted
+grep "The given storage name 'File' either does not exist at all, or exists but the matching configuration file is not yet deleted" "${tmp}"/log4.out >/dev/null 2>&1
+if test $? -ne 0 ; then
+  echo "The delete command failed for an existing storage."
+  estat=1;
+fi
+
+
+# make sure extra storages fakestorage1 cannot be deleted
+grep "Orphaned storage 'fakestorage1' with id '.' is being used by Media with volumename 'fakevolume'" "${tmp}"/log4.out >/dev/null 2>&1
+if test $? -ne 0 ; then
+  echo "The delete command failed to detect fakestorages related to other medias."
+  estat=1;
+fi
+
 end_test
