core/scripts sanitize and cleanup code
- Remove obosolete or non used functions
- Remove multiple database items
- Use shellcheck -s sh to sanitize code

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

diff --git a/core/src/cats/create_bareos_database.in b/core/src/cats/create_bareos_database.in
--- a/core/src/cats/create_bareos_database.in
+++ b/core/src/cats/create_bareos_database.in
@@ -3,7 +3,7 @@
 # BAREOS® - Backup Archiving REcovery Open Sourced
 #
 # Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
-# Copyright (C) 2013-2021 Bareos GmbH & Co. KG
+# Copyright (C) 2013-2022 Bareos GmbH & Co. KG
 #
 # This program is Free Software; you can redistribute it and/or
 # modify it under the terms of version three of the GNU Affero General Public
@@ -31,104 +31,36 @@
 # change to root dir
 cd /
 
+. "@scriptdir@"/bareos-config-lib.sh
 
-. @scriptdir@/bareos-config-lib.sh
+db_name="${db_name:-$(get_database_name @db_name@)}"
+db_type="$(get_database_driver_default)"
 
-db_name="${db_name:-`get_database_name @db_name@`}"
-db_user="${db_user:-`get_database_user @db_user@`}"
-dir_user=`get_user_dir`
-dir_group=`get_group_dir`
-default_db_type=`get_database_driver_default`
-working_dir=`get_working_dir`
+info "Creating ${db_type} database"
 
-
-#
-# See if the first argument is a valid backend name.
-# If so the user overrides the default database backend.
-#
-if [ $# -gt 0 ]; then
-   case $1 in
-      sqlite3)
-         db_type=$1
-         shift
-         ;;
-      mysql)
-         db_type=$1
-         shift
-         ;;
-      postgresql)
-         db_type=$1
-         shift
-         ;;
-      *)
-         ;;
-   esac
-fi
-
-#
-# If no new db_type is gives use the default db_type.
-#
-if [ -z "${db_type}" ]; then
-   db_type="${default_db_type}"
-fi
-
-echo "Creating ${db_type} database"
-
-bindir=`get_database_utility_path ${db_type}`
-if [ ! -z "${bindir}" ]; then
-   PATH="$bindir:$PATH"
-fi
-
-case ${db_type} in
-   sqlite3)
-      if [ -n "$BAREOS_TEST_RUNNING" ]; then
-         sqlite3 $* ${working_dir}/${db_name}.db ".tables"
-         # Allow non root access
-         chown ${dir_user}:${dir_group} ${working_dir}/${db_name}.db
-         chmod 0640 ${working_dir}/${db_name}.db
-         retval=0
-      else
-         echo "The SQLite database backend is deprecated. Please use PostgreSQL instead."
-         retval=1
-      fi
-      ;;
-   mysql)
-      if [ -n "$BAREOS_TEST_RUNNING" ]; then
-         mysql $* -e "CREATE DATABASE ${db_name};"
-         retval=$?
-      else
-         echo "The MySQL database backend is deprecated. Please use PostgreSQL instead."
-         retval=1
-      fi
-      ;;
-   postgresql)
-      # use SQL_ASCII to be able to put any filename into
-      # the database even those created with unusual character sets
-      PGOPTIONS='--client-min-messages=warning' psql -f - -d template1 $* << END-OF-DATA
+# use SQL_ASCII to be able to put any filename into
+# the database even those created with unusual character sets
+PGOPTIONS='--client-min-messages=warning' psql -f - -d template1 "$*" << END-OF-DATA
 \set ON_ERROR_STOP on
 CREATE DATABASE ${db_name} ENCODING 'SQL_ASCII' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
 ALTER DATABASE ${db_name} SET datestyle TO 'ISO, YMD';
 END-OF-DATA
-      retval=$?
+retval=$?
 
-      if PGOPTIONS='--client-min-messages=warning' psql --list --tuples-only --no-align $* | grep "^${db_name}|.*|SQL_ASCII|C|C" >/dev/null; then
-         echo "Database encoding OK"
-      else
-         echo " "
-         echo "Database encoding bad. Do not use this database"
-         echo " "
-      fi
-      ;;
-   *)
-      echo "Unknown database type $1"
-      exit 1
-      ;;
-esac
-
-if [ "${retval}" = 0 ]; then
-   echo "Creating of ${db_name} database succeeded."
+if PGOPTIONS='--client-min-messages=warning' psql --list --tuples-only --no-align "$*" | grep "^${db_name}|.*|SQL_ASCII|C|C" >/dev/null
+then
+    info "Database encoding OK"
 else
-   echo "Creating of ${db_name} database failed."
+    warn " "
+    warn "Database encoding not conform. Do not use this database"
+    warn " "
+    retval=2
+fi
+
+if [ ${retval} -eq 0 ]; then
+   info "Creating of ${db_name} database succeeded."
+else
+   error "Creating of ${db_name} database failed."
 fi
 
 exit ${retval}
diff --git a/core/src/cats/drop_bareos_database.in b/core/src/cats/drop_bareos_database.in
--- a/core/src/cats/drop_bareos_database.in
+++ b/core/src/cats/drop_bareos_database.in
@@ -3,7 +3,7 @@
 # BAREOS® - Backup Archiving REcovery Open Sourced
 #
 # Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
-# Copyright (C) 2013-2019 Bareos GmbH & Co. KG
+# Copyright (C) 2013-2022 Bareos GmbH & Co. KG
 #
 # This program is Free Software; you can redistribute it and/or
 # modify it under the terms of version three of the GNU Affero General Public
@@ -30,71 +30,20 @@
 # change to root dir
 cd /
 
+. "@scriptdir@"/bareos-config-lib.sh
 
-. @scriptdir@/bareos-config-lib.sh
+db_name="${db_name:-$(get_database_name @db_name@)}"
+db_type="$(get_database_driver_default)"
 
-db_name="${db_name:-`get_database_name @db_name@`}"
-db_user="${db_user:-`get_database_user @db_user@`}"
-default_db_type=`get_database_driver_default`
-working_dir=`get_working_dir`
+info "Dropping ${db_type} database"
 
-#
-# See if the first argument is a valid backend name.
-# If so the user overrides the default database backend.
-#
-if [ $# -gt 0 ]; then
-   case $1 in
-      sqlite3)
-         db_type=$1
-         shift
-         ;;
-      mysql)
-         db_type=$1
-         shift
-         ;;
-      postgresql)
-         db_type=$1
-         shift
-         ;;
-      *)
-         ;;
-   esac
-fi
+dropdb "$*" "${db_name}"
+retval=$?
 
-#
-# If no new db_type is gives use the default db_type.
-#
-if [ -z "${db_type}" ]; then
-   db_type="${default_db_type}"
-fi
-
-echo "Dropping ${db_type} database"
-
-bindir=`get_database_utility_path ${db_type}`
-if [ ! -z "${bindir}" ]; then
-   PATH="$bindir:$PATH"
-fi
-PATH="$bindir:$PATH"
-
-case ${db_type} in
-   sqlite3)
-      rm -f ${working_dir}/${db_name}.db
-      retval=0
-      ;;
-   mysql)
-      mysql $* -e "DROP DATABASE ${db_name};"
-      retval=$?
-      ;;
-   postgresql)
-      dropdb $* ${db_name}
-      retval=$?
-      ;;
-esac
-
-if [ ${retval} = 0 ]; then
-   echo "Drop of ${db_name} database succeeded."
+if [ ${retval} -eq 0 ]; then
+   info "Drop of ${db_name} database succeeded."
 else
-   echo "Drop of ${db_name} database failed."
+   error "Drop of ${db_name} database failed."
 fi
 
 exit ${retval}
diff --git a/core/src/cats/update_bareos_tables.in b/core/src/cats/update_bareos_tables.in
--- a/core/src/cats/update_bareos_tables.in
+++ b/core/src/cats/update_bareos_tables.in
@@ -3,7 +3,7 @@
 # BAREOS® - Backup Archiving REcovery Open Sourced
 #
 # Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
-# Copyright (C) 2013-2020 Bareos GmbH & Co. KG
+# Copyright (C) 2013-2022 Bareos GmbH & Co. KG
 #
 # This program is Free Software; you can redistribute it and/or
 # modify it under the terms of version three of the GNU Affero General Public
@@ -26,15 +26,14 @@
 #
 # Source the Bareos config functions.
 #
-. @scriptdir@/bareos-config-lib.sh
+. "@scriptdir@"/bareos-config-lib.sh
 
-db_name="${db_name:-`get_database_name @db_name@`}"
-db_user="${db_user:-`get_database_user @db_user@`}"
-db_version=`get_database_version`
-bareos_sql_ddl=`get_database_ddl_dir`
+db_type="$(get_database_driver_default)"
+db_name="${db_name:-$(get_database_name @db_name@)}"
+db_user="${db_user:-$(get_database_user @db_user@)}"
+db_version=$(get_database_version)
+bareos_sql_ddl="$(get_database_ddl_dir)"
 temp_sql_schema="/tmp/tables.sql.$$"
-default_db_type=`get_database_driver_default`
-working_dir=`get_working_dir`
 
 SHOW_WARNING="yes"
 
@@ -43,103 +42,49 @@ if [ "$1" = "-f" ]; then
    shift || true
 fi
 
-#
-# See if the first argument is a valid backend name.
-# If so the user overrides the default database backend.
-#
-if [ $# -gt 0 ]; then
-   case $1 in
-      sqlite3)
-         db_type=$1
-         shift
-         ;;
-      mysql)
-         db_type=$1
-         shift
-         ;;
-      postgresql)
-         db_type=$1
-         shift
-         ;;
-      *)
-         ;;
-   esac
-fi
+info "Updating ${db_type} tables"
 
-#
-# If no new db_type is gives use the default db_type.
-#
-if [ -z "${db_type}" ]; then
-   db_type="${default_db_type}"
-fi
-
-echo "Updating ${db_type} tables"
-
-bindir=`get_database_utility_path ${db_type}`
-if [ ! -z "${bindir}" ]; then
-   PATH="$bindir:$PATH"
-fi
-
-while [ 1 ]
+while true
 do
-   #
-   # Figure out what the current version of the database is.
-   #
-   case ${db_type} in
-      sqlite3)
-         DBVERSION=`echo 'SELECT MAX(VersionId) FROM Version;' | sqlite3 ${working_dir}/${db_name}.db`
-         ;;
-      mysql)
-         DBVERSION=`mysql -D ${db_name} $* -e "SELECT MAX(VersionId) FROM Version\G" | \
-                    sed -n -e 's/^.*VersionId.*: \(.*\)$/\1/p'`
-         ;;
-      postgresql)
-         DBVERSION=`PGOPTIONS='--client-min-messages=warning' psql -d ${db_name} -t --pset format=unaligned -c "SELECT MAX(VersionId) FROM Version;" $*`
-         ;;
-      *)
-         echo "Unknown database type ${db_type}"
-         exit 1
-         ;;
-   esac
+    DBVERSION=$(PGOPTIONS='--client-min-messages=warning' psql -d "${db_name}" -t --pset format=unaligned -c "SELECT MAX(VersionId) FROM Version;" "$@")
+    if [ -z "${DBVERSION}" ]; then
+        error "Unable to determine version of Bareos ${db_type} database"
+        exit 1
+    fi
 
-   if [ -z "${DBVERSION}" ]; then
-      echo "Unable to determine version of Bareos ${db_type} database"
-      exit 1
-   fi
-
-   if [ ${DBVERSION} = ${db_version} ]; then
-      echo "Finished upgrading database to version ${db_version}"
+    if [ "${DBVERSION}" -eq "${db_version}" ]; then
+      info "Finished upgrading database to version ${db_version}"
       exit 0
-   fi
+    fi
 
-   #
-   # See if its a known conversion.
-   #
-   found=0
-   known_conversions=`ls ${bareos_sql_ddl}/updates/${db_type}* 2>/dev/null| \
+    #
+    # See if its a known conversion.
+    #
+    found=0
+    known_conversions=$(ls "${bareos_sql_ddl}"/updates/"${db_type}"* 2>/dev/null| \
                       sed -e 's#.*/##' | \
-                      cut -d'.' -f2`
+                      cut -d'.' -f2)
    for conversion in ${known_conversions}; do
-      start_version=`echo ${conversion} | cut -d_ -f1`
-      end_version=`echo ${conversion} | cut -d_ -f2`
+      start_version=$(echo "${conversion}" | cut -d_ -f1)
+      end_version=$(echo "${conversion}" | cut -d_ -f2)
 
-      if [ ${start_version} = ${DBVERSION} ]; then
+      if [ "${start_version}" -eq "${DBVERSION}" ]; then
          found=1
          break
       fi
    done
 
-   if [ ${found} = 0 ]; then
-      echo "Don't know how to upgrade from version ${DBVERSION} to ${db_version}"
+   if [ "${found}" -eq 0 ]; then
+      error "Don't know how to upgrade from version ${DBVERSION} to ${db_version}"
       exit 1
    fi
 
-   if [ "${SHOW_WARNING}" = "yes" -a ${DBVERSION} -lt 2171 ]; then
-      echo "WARNING:"
-      echo "  Updating the database to schema version 2171 will increase the required disk space."
-      echo "  Especially it will require around twice the amount of disk space, during the migration."
-      if [ "$FORCE" != "yes" ]; then
-         echo "  Please verify you got enough disk space available and confirm by pressing <ENTER>."
+   if [ "${SHOW_WARNING}" = "yes" ] && [ "${DBVERSION}" -lt 2171 ]; then
+      warm "WARNING:"
+      warn "  Updating the database to schema version 2171 will increase the required disk space."
+      warn "  Especially it will require around twice the amount of disk space, during the migration."
+      if [ "${FORCE}" != "yes" ]; then
+         info "  Please verify you got enough disk space available and confirm by pressing <ENTER>."
          read input
          # warning already shown and confirmed. No need to show it again.
          SHOW_WARNING="no"
@@ -147,50 +92,29 @@ do
    fi
 
    sql_definitions="${bareos_sql_ddl}/updates/${db_type}.${conversion}.sql"
-   if [ ! -f ${sql_definitions} ]; then
-      echo "Unable to open database update definitions in file ${sql_definitions}"
+   if [ ! -f "${sql_definitions}" ]; then
+      error "Unable to open database update definitions in file ${sql_definitions}"
       exit 1
    fi
 
    sed -e "s/@DB_NAME@/${db_name}/" \
        -e "s/@DB_USER@/${db_user}/" \
-       ${sql_definitions} > ${temp_sql_schema}
+       "${sql_definitions}" > "${temp_sql_schema}"
 
-   echo "Upgrading database schema from version ${start_version} to ${end_version}"
+    info "Upgrading database schema from version ${start_version} to ${end_version}"
 
-   case ${db_type} in
-      sqlite3)
-         sqlite3 $* ${working_dir}/${db_name}.db < ${temp_sql_schema}
-         retval=$?
-         ;;
-      mysql)
-         mysql -D ${db_name} $* < ${temp_sql_schema}
-         retval=$?
-         ;;
-      postgresql)
-         PGOPTIONS='--client-min-messages=warning' psql -f ${temp_sql_schema} -d ${db_name} $*
-         retval=$?
-         if [ $retval -eq 0 ] && [ ${end_version} -eq 2210 ]; then
-             PGSQLVERSION=`PGOPTIONS='--client-min-messages=warning' psql -d template1 -c 'SELECT version()' $* 2>/dev/null | \
-                    awk '/PostgreSQL/ { print $2 }' | \
-                    cut -d '.' -f 1,2`
-             case ${PGSQLVERSION} in
-                 10.*|11.*|12.*)
-                     PGOPTIONS='--client-min-messages=warning' psql -d ${db_name} -c 'ALTER SEQUENCE basefiles_baseid_seq AS BIGINT'
-                     result=$?
-                     if [ $result -ne 0 ]; then
-                         echo "WARNING: Failed to update sequence basefiles_baseid_seq"
-                     fi
-                     ;;
-             esac
-         fi
-         ;;
-   esac
+    PGOPTIONS='--client-min-messages=warning' psql -f "${temp_sql_schema}" -d "${db_name}" "$*"
+    retval=$?
+    if [ "${retval}" -eq 0 ] && [ "${end_version}" -eq 2210 ]; then
+        if ! r="$(PGOPTIONS='--client-min-messages=warning' psql -d "${db_name}" -c 'ALTER SEQUENCE basefiles_baseid_seq AS BIGINT')" ; then
+            warn "WARNING: Failed to update sequence basefiles_baseid_seq ${r}"
+        fi
+    fi
 
-   rm -f ${temp_sql_schema}
+   rm -f "${temp_sql_schema}"
 
-   if [ ${retval} != 0 ]; then
-      echo "Failed to upgrade database schema from version ${start_version} to ${end_version}"
+   if [ ${retval} -ne 0 ]; then
+      error "Failed to upgrade database schema from version ${start_version} to ${end_version}"
       exit ${retval}
    fi
 done
