core/scripts sanitize and cleanup code
- Remove obosolete or non used functions
- Remove multiple database items
- Use shellcheck -s sh to sanitize code

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

diff --git a/core/src/cats/drop_bareos_tables.in b/core/src/cats/drop_bareos_tables.in
--- a/core/src/cats/drop_bareos_tables.in
+++ b/core/src/cats/drop_bareos_tables.in
@@ -3,7 +3,7 @@
 # BAREOS® - Backup Archiving REcovery Open Sourced
 #
 # Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
-# Copyright (C) 2013-2020 Bareos GmbH & Co. KG
+# Copyright (C) 2013-2022 Bareos GmbH & Co. KG
 #
 # This program is Free Software; you can redistribute it and/or
 # modify it under the terms of version three of the GNU Affero General Public
@@ -31,109 +31,39 @@
 # change to root dir
 cd /
 
+. "@scriptdir@"/bareos-config-lib.sh
 
-. @scriptdir@/bareos-config-lib.sh
-
-db_name="${db_name:-`get_database_name @db_name@`}"
-db_user="${db_user:-`get_database_user @db_user@`}"
-db_version=`get_database_version`
-bareos_sql_ddl=`get_database_ddl_dir`
+db_type=$(get_database_driver_default)
+db_name="${db_name:-$(get_database_name @db_name@)}"
+bareos_sql_ddl="$(get_database_ddl_dir)"
 temp_sql_schema="/tmp/drops.sql.$$"
-default_db_type=`get_database_driver_default`
-working_dir=`get_working_dir`
 
-#
-# See if the first argument is a valid backend name.
-# If so the user overrides the default database backend.
-#
-if [ $# -gt 0 ]; then
-   case $1 in
-      sqlite3)
-         db_type=$1
-         shift
-         ;;
-      mysql)
-         db_type=$1
-         shift
-         ;;
-      postgresql)
-         db_type=$1
-         shift
-         ;;
-      *)
-         ;;
-   esac
-fi
+info "Dropping ${db_type} tables"
 
-#
-# If no new db_type is gives use the default db_type.
-#
-if [ -z "${db_type}" ]; then
-   db_type="${default_db_type}"
-fi
+sql_definitions="${bareos_sql_ddl}/drops/postgresql.sql"
 
-echo "Dropping ${db_type} tables"
-
-case ${db_type} in
-   sqlite3)
-      ;;
-   mysql)
-      sql_definitions="${bareos_sql_ddl}/drops/mysql.sql"
-      ;;
-   postgresql)
-      sql_definitions="${bareos_sql_ddl}/drops/postgresql.sql"
-      ;;
-   *)
-      echo "Unknown database type $1"
-      exit 1
-      ;;
-esac
-
-if [ ! -z "${sql_definitions}" ]; then
-   if [ ! -f ${sql_definitions} ]; then
-      echo "Unable to open database table definitions in file ${sql_definitions}"
+if [ -n "${sql_definitions}" ]; then
+   if [ ! -f "${sql_definitions}" ]; then
+      error "Unable to open database table definitions in file ${sql_definitions}"
       exit 1
    fi
 
-   get_translated_sql_file ${sql_definitions} > ${temp_sql_schema}
-   if [ $? != 0 ]; then
-        echo "Failed to translate SQL definitions in ${sql_definitions}"
-        exit 1
+   if ! get_translated_sql_file "${sql_definitions}" > "${temp_sql_schema}"
+   then
+       error "Failed to translate SQL definitions in ${sql_definitions}"
+       exit 1
    fi
 fi
 
-bindir=`get_database_utility_path ${db_type}`
-if [ ! -z "${bindir}" ]; then
-   PATH="$bindir:$PATH"
+PGOPTIONS='--client-min-messages=warning' psql -f "${temp_sql_schema}" -d "${db_name}" "$*"
+retval=$?
+
+if [ $retval -eq 0 ]; then
+    info "Dropping of Bareos PostgreSQL tables succeeded."
+else
+    error "Dropping of Bareos PostgreSQL tables failed."
 fi
 
-case ${db_type} in
-   sqlite3)
-      rm -f ${working_dir}/${db_name}.db
-      retval=0
-      ;;
-   mysql)
-      mysql $* --database=${db_name} -f < ${temp_sql_schema}
-
-      retval=$?
-      if test $retval = 0; then
-         echo "Dropping of Bareos MySQL tables succeeded."
-      else
-         echo "Dropping of Bareos MySQL tables failed."
-      fi
-      ;;
-   postgresql)
-      PGOPTIONS='--client-min-messages=warning' psql -f ${temp_sql_schema} -d ${db_name} $*
-
-      retval=$?
-      if test $retval = 0; then
-         echo "Dropping of Bareos PostgreSQL tables succeeded."
-      else
-         echo "Dropping of Bareos PostgreSQL tables failed."
-      fi
-      ;;
-esac
-
-rm -f ${temp_sql_schema}
+rm -f "${temp_sql_schema}"
 
 exit ${retval}
