cats: allow MySQL/SQLite db create and make tables during tests
In order to still allow creation of MySQL and SQlite databases when
running tests but forbid it otherwise, the environment variable
BAREOS_TEST_RUNNING is defined in all tests.

When this variable is undefined, creating databases and making tables of
MySQL and SQLite is forbidden.

diff --git a/core/src/cats/make_bareos_tables.in b/core/src/cats/make_bareos_tables.in
--- a/core/src/cats/make_bareos_tables.in
+++ b/core/src/cats/make_bareos_tables.in
@@ -110,14 +110,30 @@ fi
 
 case ${db_type} in
    sqlite3)
-      echo "The SQLite database backend is deprecated. Please use PostgreSQL instead."
-      echo "Creation of Bareos SQLite tables aborted."
-      retval=1
+      if [ -n "$BAREOS_TEST_RUNNING" ]; then
+         sqlite3 $* ${working_dir}/${db_name}.db < ${temp_sql_schema}
+         chmod 640 ${working_dir}/${db_name}.db
+         retval=0
+      else
+         echo "The SQLite database backend is deprecated. Please use PostgreSQL instead."
+         echo "Creation of Bareos SQLite tables aborted."
+         retval=1
+      fi
       ;;
    mysql)
-      echo "The MySQL database backend is deprecated. Please use PostgreSQL instead."
-      echo "Creation of Bareos MySQL tables aborted."
-      retval=1
+      if [ -n "$BAREOS_TEST_RUNNING" ]; then
+         mysql $* --database=${db_name} -f < ${temp_sql_schema}
+         retval=$?
+         if test $retval = 0; then
+            echo "Creation of Bareos MySQL tables succeeded."
+         else
+            echo "Creation of Bareos MySQL tables failed."
+         fi
+      else
+         echo "The MySQL database backend is deprecated. Please use PostgreSQL instead."
+         echo "Creation of Bareos MySQL tables aborted."
+         retval=1
+      fi
       ;;
    postgresql)
       PGOPTIONS='--client-min-messages=warning' psql -f ${temp_sql_schema} -d ${db_name} $*
