cats: Update DB schema from 2171 to 2192
- Add an INDEX on Job.JobTDate to improve performance (MySQL only)
- Fix integer out of range error by changing BaseFiles.BaseId to
  BIGINT/BIGSERIAL
- Add new DDL update scripts for each supported DB backend
- Set BDB_VERSION in cats.h
- Remove unnecessary INDEX pathvisibility_jobid
- Collation handling PostgreSQL >= 10
- Update basefiles sequence PostgreSQL >= 10

Fixes #1088: Integer out of range when using large amounts of files with Base Jobs
Fixes #1061: Tremendous MySQL load

diff --git a/core/src/cats/update_bareos_tables.in b/core/src/cats/update_bareos_tables.in
--- a/core/src/cats/update_bareos_tables.in
+++ b/core/src/cats/update_bareos_tables.in
@@ -170,6 +170,20 @@ do
       postgresql)
          psql -f ${temp_sql_schema} -d ${db_name} $*
          retval=$?
+         if [ $retval -eq 0 ] && [ ${end_version} -eq 2192 ]; then
+             PGSQLVERSION=`psql -d template1 -c 'SELECT version()' $* 2>/dev/null | \
+                    awk '/PostgreSQL/ { print $2 }' | \
+                    cut -d '.' -f 1,2`
+             case ${PGSQLVERSION} in
+                 10.*|11.*|12.*)
+                     psql -d ${db_name} -c 'ALTER SEQUENCE basefiles_baseid_seq AS BIGINT'
+                     result=$?
+                     if [ $result -ne 0 ]; then
+                         echo "WARNING: Failed to update sequence basefiles_baseid_seq"
+                     fi
+                     ;;
+             esac
+         fi
          ;;
    esac
 
