python-fd-percona-plugin-test/testrunner: use run_bareos

diff --git a/systemtests/tests/python-fd-percona-plugin-test/testrunner b/systemtests/tests/python-fd-percona-plugin-test/testrunner
--- a/systemtests/tests/python-fd-percona-plugin-test/testrunner
+++ b/systemtests/tests/python-fd-percona-plugin-test/testrunner
@@ -14,9 +14,6 @@ JobName=backup-bareos-fd
 ${scripts}/cleanup
 ${scripts}/setup
 
-BCONSOLE="${current_test_directory}/bin/bconsole"
-
-
 start_test
 
 echo "------ running PERCONA tests"
@@ -26,63 +23,62 @@ echo "CREATE TABLE test ( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, data VARCH
 echo "insert into test (data) VALUES ('test eintrag 1') " | mysql ${db_name}_percona
 
 
+BCONSOLE="${current_test_directory}/bin/bconsole"
 
-#cat <<END_OF_DATA >$tmp/bconcmds
-#@$out /dev/null
-#messages
-#@$out $tmp/log1.out
-#setdebug level=100 storage=File
-#label volume=TestVolume001 storage=File pool=Full
-#run job=$JobName level=Full yes
-#status director
-#status client
-#status storage=File
-#wait
-#messages
-#@#
-#@# now do a restore
-#@#
-#@$out $tmp/log2.out
-#wait
-#restore client=bareos-fd fileset=PerconaTest where=$tmp/bareos-restores pluginoptions=python:local=yes select all done
-#yes
-#wait
-#messages
-#quit
-#END_OF_DATA
-
-
-cat <<END_OF_DATA >$tmp/bconcmds
-@$out $tmp/log1.out
-run job=$JobName
-wait JobName=$JobName
-status dir
-END_OF_DATA
 run_bareos
 
+echo "@$out $tmp/log1.out"  | $BCONSOLE
+
+COMMAND="run job=$JobName"
+echo -e "$COMMAND \ryes\rwait" | $BCONSOLE #| grep "Job queued. JobId="
+#sleep 5
+echo -e "wait JobName=$JobName" | $BCONSOLE
+#sleep 2
+echo "status dir" | $BCONSOLE
+# insert data and run incremental
 echo "insert into test (data) VALUES ('test eintrag 2') " | mysql ${db_name}_percona
+touch /root/testfile
 
-cat <<END_OF_DATA >$tmp/bconcmds
-@$out $tmp/log1.out
-run job=$JobName
-wait JobName=$JobName
-status dir
-END_OF_DATA
-run_bareos
+COMMAND="$COMMAND level=Incremental"
+echo -e "$COMMAND \ryes\rwait" | $BCONSOLE #| grep "Job queued. JobId="
+#sleep 5
+echo -e "wait JobName=$JobName" | $BCONSOLE
+#sleep 2
+echo "status dir" | $BCONSOLE
 
-cat <<END_OF_DATA >$tmp/bconcmds
-@$out $tmp/log2.out
+
+# run incremental again without any new data
+echo -e "$COMMAND \ryes\rwait" | $BCONSOLE #| grep "Job queued. JobId="
+#sleep 5
+echo -e "wait JobName=$JobName" | $BCONSOLE
+#sleep 2
+echo "status dir" | $BCONSOLE
+
+
+# run restore
 RESTORECMD="restore client=bareos-fd fileset=PerconaTest yes restorejob=RestoreFile select all\rdone\r"
-wait JobName=RestoreFile
-END_OF_DATA
 
-# Check if xtrabackup has extracted some files at least
+echo "@$out $tmp/log2.out"  | $BCONSOLE
+
+JOBID=`echo -e "$RESTORECMD" | $BCONSOLE | grep "Job queued. JobId=" | sed s'/.*=//' `
+
+echo -e "wait jobid=$JOBID" | $BCONSOLE | grep -q "JobStatus=OK"
+if [[ $? != 0 ]]; then
+    echo "Restore Job $JOBID failed"
+    estat=1
+fi
+
+# Check, if xtrabackup has extracted some files at least
 # TODO: verify that xtrabackup --prepare works and eventually do complete datbase restore
 ls -lR  $tmp/bareos-restores/_percona/
 if [ -z "$(ls -A $tmp/bareos-restores/_percona/)" ]; then
        echo "No restore data found"
        estat=1
 fi
+
+
+
+
 
 check_for_zombie_jobs storage=File
 stop_bareos
