python-fd-percona-test: clean up testrunner

diff --git a/systemtests/tests/pyplug-fd-percona-xtrabackup/testrunner b/systemtests/tests/pyplug-fd-percona-xtrabackup/testrunner
--- a/systemtests/tests/pyplug-fd-percona-xtrabackup/testrunner
+++ b/systemtests/tests/pyplug-fd-percona-xtrabackup/testrunner
@@ -38,44 +38,52 @@ echo "create database ${xtrabackup_test_db}" | $MYSQL
 echo "CREATE TABLE test ( id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, data VARCHAR(100), created TIMESTAMP DEFAULT NOW())  " | $MYSQL ${xtrabackup_test_db}
 echo "insert into test (data) VALUES ('test entry 1') " | $MYSQL ${xtrabackup_test_db}
 
+cat <<END_OF_DATA >$tmp/bconcmds
+@$out $tmp/log1.out
+run job=$JobName yes
+wait JobName=$JobName
+status dir
+
+run job=$JobName level=Incremental yes
+wait JobName=$JobName
+status dir
+
+# insert data and run incremental
+insert into test (data) VALUES ('test entry 2')
+
+END_OF_DATA
+run_bareos "$@"
+
+cat <<END_OF_DATA2 >"$tmp/bconcmds"
+# run incremental again without any new data
+run job=$JobName yes
+wait JobName=$JobName
+status dir
+wait
+messages
+quit
+END_OF_DATA2
+run_bareos "$@"
+
+cat <<END_OF_DATA3 >"$tmp/bconcmds"
+restore client=bareos-fd fileset=PerconaXtraBackupTest yes restorejob=RestoreFile select all done
+@$out $tmp/log2.out
+wait
+END_OF_DATA3
 
 run_bareos "$@"
 
-echo "@$out $tmp/log1.out"  | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-
-COMMAND="run job=$JobName"
-echo "$COMMAND yes" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-echo "wait JobName=$JobName" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-echo "status dir" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-# insert data and run incremental
-echo "insert into test (data) VALUES ('test entry 2') " | $MYSQL ${xtrabackup_test_db}
-
-COMMAND="$COMMAND level=Incremental"
-echo "$COMMAND yes" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf #| grep "Job queued. JobId="
-echo "wait JobName=$JobName" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-echo "status dir" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
+#JOBID=$(echo "$RESTORECMD" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf | grep "Job queued. JobId=" | sed s'/.*=//')
+#
+#if ! echo "wait jobid=$JOBID" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf | grep -q "JobStatus=OK";
+#then
+#    echo "Restore Job $JOBID failed"
+#    estat=1
+#fi
 
 
-# run incremental again without any new data
-echo "$COMMAND yes" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf #| grep "Job queued. JobId="
-echo "wait JobName=$JobName" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-echo "status dir" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
 
-
-# run restore
-RESTORECMD="restore client=bareos-fd fileset=PerconaXtraBackupTest yes restorejob=RestoreFile select all done"
-
-echo "@$out $tmp/log2.out"  | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf
-
-JOBID=$(echo "$RESTORECMD" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf | grep "Job queued. JobId=" | sed s'/.*=//')
-
-if ! echo "wait jobid=$JOBID" | $BAREOS_BCONSOLE_BINARY -c "$conf"/bconsole.conf | grep -q "JobStatus=OK";
-then
-    echo "Restore Job $JOBID failed"
-    estat=1
-fi
-
-# Check, if xtrabackup has extracted some files at least
+# Check if xtrabackup has extracted some files at least
 # TODO: verify that xtrabackup --prepare works and eventually do complete datbase restore
 ls -lR  $tmp/bareos-restores/_percona/
 if [ -z "$(ls -A $tmp/bareos-restores/_percona/)" ]; then
