systemtests: fix systemtest-fd-plugin-postgresql

diff --git a/systemtests/tests/python-fd-plugin-postgres-test/testrunner b/systemtests/tests/python-fd-plugin-postgres-test/testrunner
--- a/systemtests/tests/python-fd-plugin-postgres-test/testrunner
+++ b/systemtests/tests/python-fd-plugin-postgres-test/testrunner
@@ -16,24 +16,23 @@ export TestName
 JobName=backup-bareos-fd
 #shellcheck source=../environment.in
 . ./environment
-
-JobName=backup-bareos-fd
+. ./database/setup_local_db.sh
 
 # setup local database server
-pushd "$current_test_directory"/database || exit 1
-sh -x setup_local_db.sh
-popd
-
-TESTPGHOST="$current_test_directory"/database/tmp
-PSQL="psql -h $TESTPGHOST"
 DBNAME="backuptest"
+TESTPGHOST="/tmp/${TestName}"
+PSQL="psql --host $TESTPGHOST"
+
+[ -d "$TESTPGHOST" ] || mkdir -p "$TESTPGHOST"
+
+pushd database > /dev/null || exit 1
+setup_local_db "$TESTPGHOST" || exit
+popd > /dev/null
 
 #shellcheck source=../scripts/functions
 . "${rscripts}"/functions
 "${rscripts}"/cleanup
 "${rscripts}"/setup
-
-
 
 # Directory to backup.
 # This directory will be created by setup_data "$@"().
@@ -93,9 +92,13 @@ run_bconsole
 # Now stop database and try a restore
 # ...
 # shut down database and delete directories
-pg_ctl -D database/data stop
-rm -Rf database/data
-rm -Rf database/wal_archive
+pushd database/ > /dev/null
+local_db_stop_server "$TESTPGHOST"
+rm -Rf data
+rm -Rf wal_archive
+echo "------------ stopped"
+ps -e | grep postgres
+popd > /dev/null
 
 cat <<END_OF_DATA >$tmp/bconcmds
 @$out /dev/null
@@ -109,21 +112,29 @@ run_bconsole
 
 check_for_zombie_jobs storage=File
 stop_bareos
+sleep 1
+
+#sometimes the pid file remains
+rm -f database/data/postmaster.pid
 
 # Create a recovery.conf
 # This may become a plugin feature later on
 echo "restore_command = 'cp $current_test_directory/database/wal_archive/%f %p'" > $current_test_directory/database/data/recovery.conf
 
 # start DB again - shall recover to latest possible state
-pg_ctl -D database/data -l database/log/logfile start
-sleep 10
+pushd database > /dev/null
+echo "------------ to be started"
+ps -e | grep postgres
+local_db_start_server "$TESTPGHOST" || exit 1
+popd > /dev/null
 echo "SELECT * FROM t" | ${PSQL} ${DBNAME} > $tmp/sql.log
 
 check_two_logs
 if (grep -q "for INCR" $tmp/sql.log)
-then 
+then
    estat=0
 else
+   echo "key not found"
    estat=1
 fi
 
