systemtest: updated autochanger test to have subtests

diff --git a/systemtests/tests/autochanger/test-setup b/systemtests/tests/autochanger/test-setup
--- a/systemtests/tests/autochanger/test-setup
+++ b/systemtests/tests/autochanger/test-setup
@@ -1,6 +1,8 @@
+#!/bin/bash
+
 #   BAREOS® - Backup Archiving REcovery Open Sourced
 #
-#   Copyright (C) 2021-2021 Bareos GmbH & Co. KG
+#   Copyright (C) 2022-2022 Bareos GmbH & Co. KG
 #
 #   This program is Free Software; you can redistribute it and/or
 #   modify it under the terms of version three of the GNU Affero General Public
@@ -17,18 +19,35 @@
 #   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 #   02110-1301, USA.
 
-get_filename_component(BASENAME ${CMAKE_CURRENT_BINARY_DIR} NAME)
-if(AUTOCHANGER_TEST_ENABLED)
-  create_systemtest(${SYSTEMTEST_PREFIX} ${BASENAME})
-  # Make sure these tests run sequentially.
-  set_tests_properties(
-    ${SYSTEMTEST_PREFIX}autochanger:backup-restore PROPERTIES RESOURCE_LOCK
-                                               autochanger_resource
-  )
-set_tests_properties(
-  ${SYSTEMTEST_PREFIX}autochanger:label-release-autoselect PROPERTIES RESOURCE_LOCK
-                                             autochanger_resource
-)
-else()
-  create_systemtest(${SYSTEMTEST_PREFIX} ${BASENAME} DISABLED)
-endif()
+set -e
+set -o pipefail
+set -u
+
+#shellcheck source=../environment.in
+. ./environment
+
+#shellcheck source=../scripts/functions
+. "${rscripts}"/functions
+"${rscripts}"/cleanup
+"${rscripts}"/setup
+
+
+if ! ./invalidate_tapes.sh ${1:-}
+then
+  echo "Could not invalidate tapes"
+  exit 1
+fi
+
+if ! ./create_autochanger_configs.sh ${1:-}
+then
+  echo "Could not create autochanger configs"
+  exit 1
+fi
+
+# Fill ${BackupDirectory} with data.
+setup_data
+
+bin/bareos start
+
+# make sure, director is up and running.
+print_debug "$(bin/bconsole <<< "status dir")"
