apply shfmt to updated scripts

diff --git a/core/platforms/redhat/bareos-dir.in b/core/platforms/redhat/bareos-dir.in
--- a/core/platforms/redhat/bareos-dir.in
+++ b/core/platforms/redhat/bareos-dir.in
@@ -14,11 +14,11 @@
 DIR_USER=@dir_user@
 DIR_GROUP=@dir_group@
 DIR_OPTIONS=''
-OS=`uname -s`
+OS=$(uname -s)
 
 # if /lib/tls exists, force Bareos to use the glibc pthreads instead
-if [ -d "/lib/tls" -a $OS = "Linux" -a `uname -r | cut -c1-3` = "2.4" ] ; then
-     export LD_ASSUME_KERNEL=2.4.19
+if [ -d "/lib/tls" -a $OS = "Linux" -a $(uname -r | cut -c1-3) = "2.4" ]; then
+  export LD_ASSUME_KERNEL=2.4.19
 fi
 
 # pull in any user defined DIR_DIR_OPTIONS, DIR_USER, or DIR_GROUP
@@ -30,52 +30,53 @@ fi
 MALLOC_CHECK_=0
 export MALLOC_CHECK_
 
-function checkcfg () {
-   echo "Checking Configuration and Database connection ... "
-   su -s /bin/sh ${DIR_USER} -c "@sbindir@/bareos-dir -f -t"
-   if [ $? -eq 0 ]; then
-      return 0
-   else
-      return 1
-   fi
+function checkcfg()
+{
+  echo "Checking Configuration and Database connection ... "
+  su -s /bin/sh ${DIR_USER} -c "@sbindir@/bareos-dir -f -t"
+  if [ $? -eq 0 ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 RETVAL=0
 case "$1" in
-    start)
-       checkcfg
-       if [ $? -eq 0 ]; then
-          if [ "${DIR_GROUP}" != '' ]; then
-             DIR_OPTIONS="${DIR_OPTIONS} -g ${DIR_GROUP}"
-          fi
-          echo -n "Starting Bareos Director services: "
-          daemon --user ${DIR_USER} @sbindir@/bareos-dir $2 ${DIR_OPTIONS}
-          RETVAL=$?
-          echo
-          [ $RETVAL -eq 0 ] && touch @subsysdir@/bareos-dir
-       else
-          echo "Configuration check failed, please check log file for errors"
-       fi
-       ;;
-    stop)
-       echo -n "Stopping Bareos Director services: "
-       killproc @sbindir@/bareos-dir
-       RETVAL=$?
-       echo
-       [ $RETVAL -eq 0 ] && rm -f @subsysdir@/bareos-dir
-       ;;
-    restart)
-       $0 stop
-       sleep 5
-       $0 start
-       ;;
-    status)
-       status @sbindir@/bareos-dir
-       RETVAL=$?
-       ;;
-    *)
-       echo "Usage: $0 {start|stop|restart|status}"
-       exit 1
-       ;;
+  start)
+    checkcfg
+    if [ $? -eq 0 ]; then
+      if [ "${DIR_GROUP}" != '' ]; then
+        DIR_OPTIONS="${DIR_OPTIONS} -g ${DIR_GROUP}"
+      fi
+      echo -n "Starting Bareos Director services: "
+      daemon --user ${DIR_USER} @sbindir@/bareos-dir $2 ${DIR_OPTIONS}
+      RETVAL=$?
+      echo
+      [ $RETVAL -eq 0 ] && touch @subsysdir@/bareos-dir
+    else
+      echo "Configuration check failed, please check log file for errors"
+    fi
+    ;;
+  stop)
+    echo -n "Stopping Bareos Director services: "
+    killproc @sbindir@/bareos-dir
+    RETVAL=$?
+    echo
+    [ $RETVAL -eq 0 ] && rm -f @subsysdir@/bareos-dir
+    ;;
+  restart)
+    $0 stop
+    sleep 5
+    $0 start
+    ;;
+  status)
+    status @sbindir@/bareos-dir
+    RETVAL=$?
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
+    ;;
 esac
 exit $RETVAL
diff --git a/core/platforms/suse/bareos-dir.in b/core/platforms/suse/bareos-dir.in
--- a/core/platforms/suse/bareos-dir.in
+++ b/core/platforms/suse/bareos-dir.in
@@ -29,47 +29,48 @@
 # this gives us funtion rc_status -v to tell us if we succeed or fail
 . /etc/rc.status
 
-function checkcfg () {
-   echo "Checking Configuration and Database connection ... "
-   su -s /bin/sh @dir_user@ -c "@sbindir@/bareos-dir -f -t"
-   if [ $? -eq 0 ]; then
-      return 0
-   else
-      return 1
-   fi
+function checkcfg()
+{
+  echo "Checking Configuration and Database connection ... "
+  su -s /bin/sh @dir_user@ -c "@sbindir@/bareos-dir -f -t"
+  if [ $? -eq 0 ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 RETVAL=0
 case "$1" in
-    start)
-       checkcfg
-       if [ $? -eq 0 ]; then
-          echo -n "Starting the Bareos Director: "
-          /sbin/startproc -u @dir_user@ -g @dir_group@ @sbindir@/bareos-dir $2
-          rc_status -v && touch @subsysdir@/bareos-dir
-       else
-          echo "Configuration check failed, please check log file for errors"
-          rc_failed
-       fi
-       ;;
-    stop)
-       echo -n "Stopping the Director daemon: "
-       /sbin/killproc @sbindir@/bareos-dir
-       rc_status -v && rm -f @subsysdir@/bareos-dir
-       ;;
-    restart)
-       $0 stop
-       sleep 5
-       $0 start
-       ;;
-    status)
-       echo -n "Checking for Bareos director "
-       /sbin/checkproc @sbindir@/bareos-dir
-       rc_status -v
-       ;;
-    *)
-       echo "Usage: $0 {start|stop|restart|status}"
-       exit 1
-       ;;
+  start)
+    checkcfg
+    if [ $? -eq 0 ]; then
+      echo -n "Starting the Bareos Director: "
+      /sbin/startproc -u @dir_user@ -g @dir_group@ @sbindir@/bareos-dir $2
+      rc_status -v && touch @subsysdir@/bareos-dir
+    else
+      echo "Configuration check failed, please check log file for errors"
+      rc_failed
+    fi
+    ;;
+  stop)
+    echo -n "Stopping the Director daemon: "
+    /sbin/killproc @sbindir@/bareos-dir
+    rc_status -v && rm -f @subsysdir@/bareos-dir
+    ;;
+  restart)
+    $0 stop
+    sleep 5
+    $0 start
+    ;;
+  status)
+    echo -n "Checking for Bareos director "
+    /sbin/checkproc @sbindir@/bareos-dir
+    rc_status -v
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
+    ;;
 esac
 rc_exit
