check cfg and db conn before startup of director
We now use the possibilty to check the configuration
and database connection on startup of the director before
we really startup the daemon so that we get direct
feedback if something is wrong.

Before, we did not get any feedback because the director
forked so problems only were visible in the logfile.

Without systemd, we get the output directly, with systemd we
need to call "systemctl status bareos-dir.service"

Fixes #286: Alter the startscripts to run the daemons with -t before starting them

Signed-off-by: Marco van Wieringen <marco.van.wieringen@bareos.com>

diff --git a/platforms/redhat/bareos-dir.in b/platforms/redhat/bareos-dir.in
--- a/platforms/redhat/bareos-dir.in
+++ b/platforms/redhat/bareos-dir.in
@@ -31,17 +31,32 @@ fi
 MALLOC_CHECK_=0
 export MALLOC_CHECK_
 
+function checkcfg () {
+   echo "Checking Configuration and Database connection ... "
+   su -s /bin/sh ${DIR_USER} -c "@sbindir@/bareos-dir -f -t -c @sysconfdir@/bareos-dir.conf"
+   if [ $? -eq 0 ]; then
+      return 0
+   else
+      return 1
+   fi
+}
+
 RETVAL=0
 case "$1" in
     start)
-       if [ "${DIR_GROUP}" != '' ]; then
-	  DIR_OPTIONS="${DIR_OPTIONS} -g ${DIR_GROUP}"
+       checkcfg
+       if [ $? -eq 0 ]; then
+          if [ "${DIR_GROUP}" != '' ]; then
+             DIR_OPTIONS="${DIR_OPTIONS} -g ${DIR_GROUP}"
+          fi
+          echo -n "Starting Bareos Director services: "
+          daemon --user ${DIR_USER} @sbindir@/bareos-dir $2 ${DIR_OPTIONS} -c @sysconfdir@/bareos-dir.conf
+          RETVAL=$?
+          echo
+          [ $RETVAL -eq 0 ] && touch @subsysdir@/bareos-dira
+       else
+          echo "Configuration check failed, please check log file for errors"
        fi
-       echo -n "Starting Bareos Director services: "
-       daemon --user ${DIR_USER} @sbindir@/bareos-dir $2 ${DIR_OPTIONS} -c @sysconfdir@/bareos-dir.conf
-       RETVAL=$?
-       echo
-       [ $RETVAL -eq 0 ] && touch @subsysdir@/bareos-dir
        ;;
     stop)
        echo -n "Stopping Bareos Director services: "
