systemtest: extended `volume-pruning` test

diff --git a/systemtests/tests/volume-pruning/testrunner b/systemtests/tests/volume-pruning/testrunner
--- a/systemtests/tests/volume-pruning/testrunner
+++ b/systemtests/tests/volume-pruning/testrunner
@@ -33,7 +33,10 @@ messages
 @$out $tmp/log1.out
 setdebug level=100 storage=File
 label volume=TestVolume001 storage=File pool=Full
-run job=$JobName yes
+label volume=TestVolume002 storage=File pool=Full
+label volume=TestVolume003 storage=File pool=Full
+label volume=TestVolume004 storage=File pool=Full
+label volume=TestVolumeIncremental storage=File pool=Incremental
 status director
 status client
 status storage=File
@@ -42,13 +45,6 @@ messages
 
 run job=$JobName Level=Full yes
 run job=$JobName Level=Full yes
-run job=$JobName Level=Full yes
-run job=$JobName Level=Full yes
-run job=$JobName Level=Full yes
-wait
-@sleep 10
-run job=$JobName Level=Full yes
-
 @#
 @# now do a restore
 @#
@@ -65,25 +61,120 @@ messages
 @sleep 6
 update volume=TestVolume001 volstatus=Used
 prune volume=TestVolume001 yes
+wait
 messages
+
+@$out $tmp/log3.out
+@#
+@# now do the same but using the prune all command
+@#
+@#
+
+run job=$JobName Level=Full yes
+run job=$JobName Level=Full yes
+wait
+update volume=TestVolume002 volstatus=Used
+
+run job=$JobName Level=Full yes
+run job=$JobName Level=Full yes
+wait
+update volume=TestVolume003 volstatus=Used
+
+@sleep 6
+
+prune all volumes yes
+wait
+messages
+
+
+run job=$JobName Level=Full yes
+wait
+
 quit
 END_OF_DATA
 
 run_bareos "$@"
+
+touch $tmp/data/weird-files/newfilecreatedjustforthistest
+
+cat <<END_OF_DATA >"$tmp/bconcmds"
+@$out $tmp/log4.out
+@#
+@# Prune all volumes of a given pool
+@#
+@#
+
+run job=$JobName Level=Incremental yes
+wait
+
+@sleep 6
+
+update volume=TestVolume004 volstatus=Used
+update volume=TestVolumeIncremental volstatus=Used
+
+prune all volumes pool=Incremental yes
+
+wait
+messages
+quit
+END_OF_DATA
+
+run_bconsole
+
 check_for_zombie_jobs storage=File
 stop_bareos
 
 check_two_logs
 
-if ! grep "Purging the following JobIds: 1,2,3,4,5,6" "$tmp"/log1.out; then
-  echo "'Purging the following JobIds: 1,2,3,4,5,6' not found in $tmp/log1.out" >&2
-  grep 'Purging the' "$tmp"/log1.out >&2 || :
+if ! grep "Purging the following JobIds: 1,2" "$tmp"/log2.out; then
+  echo "'Purging the following JobIds: 1,2' not found in $tmp/log2.out" >&2
+  grep 'Purging the' "$tmp"/log2.out >&2 || :
   estat=1
 fi
 
 if ! grep -F 'Volume "TestVolume001" contains no jobs after pruning.' $tmp/log2.out; then
   echo "'Volume \"TestVolume001\" contains no jobs after pruning.' not found in $tmp/log2.out" >&2
   grep 'Volume.*contains no jobs after pruning.' $tmp/log2.out >&2 || :
+  estat=1
+fi
+
+## prune all volumes checks
+
+if ! grep "Purging the following JobIds: 4,5" "$tmp"/log3.out; then
+  echo "'Purging the following JobIds: 4,5' not found in $tmp/log3.out" >&2
+  grep 'Purging the' "$tmp"/log3.out >&2 || :
+  estat=1
+fi
+
+if ! grep -F 'Volume "TestVolume002" contains no jobs after pruning.' $tmp/log3.out; then
+  echo "'Volume \"TestVolume002\" contains no jobs after pruning.' not found in $tmp/log3.out" >&2
+  grep 'Volume.*contains no jobs after pruning.' $tmp/log3.out >&2 || :
+  estat=1
+fi
+
+if ! grep "Purging the following JobIds: 6,7" "$tmp"/log3.out; then
+  echo "'Purging the following JobIds: 6,7' not found in $tmp/log3.out" >&2
+  grep 'Purging the' "$tmp"/log3.out >&2 || :
+  estat=1
+fi
+
+if ! grep -F 'Volume "TestVolume003" contains no jobs after pruning.' $tmp/log3.out; then
+  echo "'Volume \"TestVolume003\" contains no jobs after pruning.' not found in $tmp/log3.out" >&2
+  grep 'Volume.*contains no jobs after pruning.' $tmp/log3.out >&2 || :
+  estat=1
+fi
+
+# Prune all volumes of specific pool
+
+if ! grep "Purging the following JobIds: 9" "$tmp"/log4.out; then
+  echo "'Purging the following JobIds: 9' not found in $tmp/log4.out" >&2
+  grep 'Purging the' "$tmp"/log3.out >&2 || :
+  estat=1
+fi
+
+if ! grep -F 'Volume "TestVolumeIncremental" contains no jobs after pruning.' $tmp/log4.out; then
+  echo "'Volume \"TestVolumeIncremental\" contains no jobs after pruning.' not found in $tmp/log4.out" >&2
+  grep 'Volume.*contains no jobs after pruning.' $tmp/log3.out >&2 || :
   estat=1
 fi
 
