First prototype dynamic loading SD backends.
We now store all shared objects used in all SD programs
(stored, btape, bls ...) in a shared library named
libbareossd-<version>.so so the final binaries get much
smaller and share the same code. Next to that we started
the first work on making tape specific code abstracted in
the tape_device class and no longer in the generic device
code. Now we implement the different methods of the different
device classes using virtual methods some are pure virtual
which means that the derived class needs to implement this
method itself and some have a default implementation which the
class can override.

This also contains the first try at making it possible to
dynamically load the different SD backends. The file backend
will always be part of the libbareossd.so but the tape and
the different cloud storage backends are dynamically loadable
using the same technique as what is used for loading the
different catalog backends. This means that we can distribute
the different storage programs without the need to have all
kind of dependencies on the different cloud backend we support
now.

As part of this big refactoring we removed the vtape code which
doesn't serve a real purpose anymore in Bareos as there are much
better alternatives (MHVTL and QuadstorVTL) nowadays and we should
carry on unmaintained code. The alternatives also see steady
development while vtape hasn't been updates in ages. Also these
alternative VTL emulators implement a true autochanger, encryption
and much more like personality support for all major brands in
real tape hardware which also means we test our tape code much
more thoroughly.

diff --git a/autoconf/configure.in b/autoconf/configure.in
--- a/autoconf/configure.in
+++ b/autoconf/configure.in
@@ -72,6 +72,12 @@ LIBBAREOSLMDB_LT_RELEASE=`sed -n -e 's/^#.*LIBBAREOSLMDB_LT_RELEASE.*"\(.*\)"$/\
 LIBBAREOSLMDB_LT_RELEASE=${LIBBAREOSLMDB_LT_RELEASE:-$VERSION}
 AC_SUBST(LIBBAREOSLMDB_LT_RELEASE)dnl
 
+dnl src/stored/backends
+dnl can be overwritten by specific values from version.h
+LIBBAREOSSD_LT_RELEASE=`sed -n -e 's/^#.*LIBBAREOSCATS_LT_RELEASE.*"\(.*\)"$/\1/p' ${srcdir}/src/include/version.h`
+LIBBAREOSSD_LT_RELEASE=${LIBBAREOSLMDB_LT_RELEASE:-$VERSION}
+AC_SUBST(LIBBAREOSSD_LT_RELEASE)dnl
+
 echo "configuring for ${BAREOS} $VERSION ($DATE)"
 
 dnl -------------------------------------------------------
@@ -637,6 +643,44 @@ fi
 AC_SUBST(STORED_DIR)
 AC_SUBST(SD_PLUGIN_DIR)
 
+dnl --------------------------------------------------
+dnl dynamic loading of storage backends
+dnl --------------------------------------------------
+use_dynamic_storage_backends=no
+AC_ARG_ENABLE(dynamic-storage_backends,
+   AC_HELP_STRING([--enable-dynamic-storage-backends], [enable dynamic loading of storage backends @<:@default=no@:>@]),
+   [
+       if test x$enableval = xyes; then
+          use_dynamic_storage_backends=yes
+          AC_DEFINE(HAVE_DYNAMIC_SD_BACKENDS, 1, [Define to 1 if dynamic loading of storage backends is enabled])
+       fi
+   ]
+)
+
+if test "x$use_libtool" != "xyes" -a "x$use_dynamic_storage_backends" = "xyes"; then
+   echo ""
+   echo "You specified --enable-dynamic-storage-plugins but disabled libtool with --disable-libtool"
+   echo "We only support dynamic loading using libtool so either disable dynamic loading or enable libtool"
+   echo ""
+   echo "Aborting the configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi
+
+if test x$use_dynamic_storage_backends = xyes; then
+   NEEDED_DEVICE_API_SRCS=""
+   NEEDED_BACKEND_LIBS=""
+   SD_BACKENDS_DIR="src/stored/backends"
+else
+   NEEDED_DEVICE_API_SRCS="\$(AVAILABLE_DEVICE_API_SRCS)"
+   NEEDED_BACKEND_LIBS="\$(AVAILABLE_BACKEND_LIBS)"
+   SD_BACKENDS_DIR=""
+fi
+AC_SUBST(NEEDED_DEVICE_API_SRCS)
+AC_SUBST(NEEDED_BACKEND_LIBS)
+AC_SUBST(SD_BACKENDS_DIR)
+
 dnl ---------------------------------------------------
 dnl Check for conio (Bareos readline substitute)(
 dnl ---------------------------------------------------
@@ -649,7 +693,6 @@ AC_ARG_ENABLE(conio,
        fi
    ]
 )
-
 
 dnl ---------------------------------------------------
 dnl Check for IPv6 support
@@ -4071,6 +4114,31 @@ AC_SUBST(BUILD_FD_PLUGINS)
 AC_SUBST(BUILD_SD_PLUGINS)
 AC_SUBST(BUILD_DIR_PLUGINS)
 
+dnl build a list of storage backend  we need to build.
+if test x$use_libtool != xno; then
+   BUILD_SD_BACKENDS="libbareossd-fifo.la libbareossd-gentape.la libbareossd-tape.la"
+
+   if test X"$have_glusterfs" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-gfapi.la"
+   fi
+
+   if test X"$have_droplet" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-object.la"
+   fi
+
+   if test X"$have_ceph_rados" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-rados.la"
+   fi
+
+   if test X"$have_cephfs" = "Xyes" ; then
+      BUILD_SD_BACKENDS="${BUILD_SD_BACKENDS} libbareossd-cephfs.la"
+   fi
+else
+   BUILD_SD_BACKENDS=""
+fi
+
+AC_SUBST(BUILD_SD_BACKENDS)
+
 dnl Insanity check
 if test "x${subsysdir}" = "x${sbindir}" ; then
    echo " "
@@ -4131,6 +4199,7 @@ src/dird/bareos-dir.conf \
 src/lib/Makefile \
 src/stored/Makefile \
 src/stored/bareos-sd.conf \
+src/stored/backends/Makefile \
 src/filed/Makefile \
 src/filed/bareos-fd.conf \
 src/cats/Makefile \
