bpipe-fd: cleanup small issues
- remove comments from config
- fix date in cmake list
- added incremental backup run
- write to individual files for Full and Inc
- do not read backup environment vars from restored data but
  from immediately written files
- verify plausibility of BareosSinceTime
- write to std log file names to be able to use check_two_logs()

diff --git a/systemtests/tests/bpipe-fd/writeprogram b/systemtests/tests/bpipe-fd/writeprogram
--- a/systemtests/tests/bpipe-fd/writeprogram
+++ b/systemtests/tests/bpipe-fd/writeprogram
@@ -1,23 +1,25 @@
 #!/bin/bash
 
-read_program_file="tmp/readprogram.out"
-write_program_file="tmp/writeprogram.out"
+read_program_data_file="tmp/readprogram.$BareosJobId.$BareosJobLevel.dat"
+write_program_log="tmp/writeprogram.env"
 
 # write restored data from readprogram to file
-touch "$read_program_file" || {
-  echo "Cannot write to $read_program_file"
+touch "$read_program_data_file" || {
+  echo "Cannot write to $read_program_data_file"
   exit 1
 }
-cat >"$read_program_file"
+cat >"$read_program_data_file"
 
 # write environment variables from writeprogram to file
-touch "$write_program_file" || {
-  echo "Cannot write to $write_program_file"
+touch "$write_program_log" || {
+  echo "Cannot write to $write_program_log"
   exit 1
 }
-echo "Environment variables:" >>"$write_program_file"
-echo "BareosClientName='$BareosClientName'" >>"$write_program_file"
-echo "BareosJobId='$BareosJobId'" >>"$write_program_file"
-echo "BareosJobLevel='$BareosJobLevel'" >>"$write_program_file"
-echo "BareosSinceTime='$BareosSinceTime'" >>"$write_program_file"
-echo "BareosJobType='$BareosJobType'" >>"$write_program_file"
+{
+  echo "# Environment variables:"
+  echo "BareosClientName='$BareosClientName'"
+  echo "BareosJobId='$BareosJobId'"
+  echo "BareosJobLevel='$BareosJobLevel'"
+  echo "BareosSinceTime='$BareosSinceTime'"
+  echo "BareosJobType='$BareosJobType'"
+} >"$write_program_log"
