systemtests: remove refactored local scripts
- remove autogenerated file in autochanger, block-size, scsicrypto
- block-size adapt test to refactored global scripts
- block-size split testrunner
- remove redirect_output in autochanger block-size
- adapt tests to use the one in scripts

diff --git a/systemtests/tests/block-size/test-setup b/systemtests/tests/block-size/test-setup
--- a/systemtests/tests/block-size/test-setup
+++ b/systemtests/tests/block-size/test-setup
@@ -1,6 +1,8 @@
+#!/bin/bash
+
 #   BAREOS® - Backup Archiving REcovery Open Sourced
 #
-#   Copyright (C) 2021-2026 Bareos GmbH & Co. KG
+#   Copyright (C) 2022-2026 Bareos GmbH & Co. KG
 #
 #   This program is Free Software; you can redistribute it and/or
 #   modify it under the terms of version three of the GNU Affero General Public
@@ -17,22 +19,33 @@
 #   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 #   02110-1301, USA.
 
-get_filename_component(BASENAME ${CMAKE_CURRENT_BINARY_DIR} NAME)
-if(AUTOCHANGER_TEST_ENABLED)
-  # IGNORE_CONFIG_WARNINGS: requires directive 'Maximum Block Size (Sd ->
-  # Device)'
-  create_systemtest(${SYSTEMTEST_PREFIX} ${BASENAME} IGNORE_CONFIG_WARNINGS)
-  # Make sure these tests run sequentially.
-  set_tests_properties(
-    ${SYSTEMTEST_PREFIX}block-size:setup
-    ${SYSTEMTEST_PREFIX}block-size:block-size
-    ${SYSTEMTEST_PREFIX}block-size:cleanup
-    PROPERTIES
-      RESOURCE_LOCK
-      autochanger_resource
-      DEPENDS
-      "${SYSTEMTEST_PREFIX}autochanger:cleanup;${SYSTEMTEST_PREFIX}scsicrypto:cleanup"
-  )
-else()
-  create_systemtest(${SYSTEMTEST_PREFIX} ${BASENAME} DISABLED)
-endif()
+set -e
+set -o pipefail
+set -u
+
+#shellcheck source=../../environment.in
+. ./environment
+
+#shellcheck source=../../scripts/functions
+. "${BAREOS_SCRIPTS_DIR}"/functions
+"${BAREOS_SCRIPTS_DIR}"/cleanup
+"${BAREOS_SCRIPTS_DIR}"/setup
+
+if ! "${BAREOS_SCRIPTS_DIR}"/invalidate_tapes.sh; then
+  echo "Could not invalidate tapes"
+  exit 1
+fi
+
+if ! "${BAREOS_SCRIPTS_DIR}"/create_autochanger_configs.sh; then
+  echo "Could not create autochanger configs"
+  exit 1
+fi
+
+# Fill ${BackupDirectory} with data.
+setup_data
+
+bin/bareos start
+bin/bareos status
+
+# make sure that the director is up and running.
+print_debug "$(bin/bconsole <<<"status dir")"
