systemtests: fix shellcheck paths

diff --git a/systemtests/tests/py3plug-fd-postgresql/testrunner-tablespace b/systemtests/tests/py3plug-fd-postgresql/testrunner-tablespace
--- a/systemtests/tests/py3plug-fd-postgresql/testrunner-tablespace
+++ b/systemtests/tests/py3plug-fd-postgresql/testrunner-tablespace
@@ -14,12 +14,11 @@ set -u
 #
 # It can be used for any PostgreSQL version >= 10.
 
-
 TestName="$(basename "$(pwd)")"
 export TestName
 
 JobName="backup-bareos-fd"
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 . ./database/setup_local_db.sh
 
@@ -32,12 +31,12 @@ PSQL="${POSTGRES_BIN_PATH}/psql --no-psqlrc --host ${TESTPGHOST}"
 mkdir -p "${TESTPGHOST}"
 [ $EUID -eq 0 ] && chown postgres "${TESTPGHOST}"
 
-pushd database > /dev/null
+pushd database >/dev/null
 setup_local_db "${TESTPGHOST}"
 setup_local_tablespace "${TESTPGHOST}"
-popd > /dev/null
+popd >/dev/null
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
 
 # Create Test DB with table and 1 statement
@@ -74,7 +73,7 @@ ${PSQL} ${DBNAME} -f "database/make_cluster_activity.sql" --output ${tmp}/cluste
 run_bconsole
 expect_grep "Backup OK" "${tmp}/tlog1.out" "Full Backup not found!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # Now add data to the database and run an incremental job
@@ -95,7 +94,7 @@ echo "First incremental backup stage"
 run_bconsole
 expect_grep "Backup OK" "${tmp}/tlog2.out" "First Incremental Backup not found!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # run another Incr without db changes - should result in empty backup job (only restore object)
@@ -113,11 +112,11 @@ echo "Second incremental backup stage"
 run_bconsole
 expect_grep "Backup OK" "${tmp}/tlog3.out" "2nd Incremental Backup not found!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 # Now stop database and try a restore
-pushd database/ > /dev/null
+pushd database/ >/dev/null
 echo "destroy pg_cluster"
 local_db_stop_server "$TESTPGHOST"
 # Save previous log
@@ -125,7 +124,7 @@ local_db_stop_server "$TESTPGHOST"
 rm -rf data wal_archive table_space index_space
 
 echo "------------ stopped"
-popd > /dev/null
+popd >/dev/null
 
 cat <<END_OF_DATA >${tmp}/bconcmds
 @$out ${NULL_DEV}
@@ -142,22 +141,22 @@ run_bconsole
 
 expect_grep "Restore OK" "${tmp}/tlog4.out" "Restore Backup not ok!"
 if [ ${estat} -ne 0 ]; then
-    exit ${estat}
+  exit ${estat}
 fi
 
 sleep 1
 
-pushd database > /dev/null
+pushd database >/dev/null
 #sometimes the pid file remains
-rm -f data/postmaster.pid ||:
+rm -f data/postmaster.pid || :
 # reset log file
-rm -f data/log/* ||:
-rm -f data/pg_wall/* ||:
+rm -f data/log/* || :
+rm -f data/pg_wall/* || :
 
 # use either recovery.conf or recovery.signal
 # Those files should exist after restore, the plugin create them
 # postgres 11 and lower
-if (( ${PG_VERSION} < 12 )); then
+if ((${PG_VERSION} < 12)); then
   echo "PG_VERSION is ${PG_VERSION} so lower than 12, using recovery.conf"
   recovery_file="${current_test_directory}/database/data/recovery.conf"
 else
@@ -166,39 +165,41 @@ else
   recovery_file="${current_test_directory}/database/data/recovery.signal"
 fi
 restore_command="restore_command = 'cp ${current_test_directory}/database/wal_archive/%f %p'"
-if [ ! -f "${recovery_file}" ];then
- echo "${TestName} ${recovery_file} is missing from restore"
- exit 1;
+if [ ! -f "${recovery_file}" ]; then
+  echo "${TestName} ${recovery_file} is missing from restore"
+  exit 1
 fi
-if (( ${PG_VERSION} < 12 )); then
-  echo "${restore_command}" >> "${recovery_file}"
+if ((${PG_VERSION} < 12)); then
+  echo "${restore_command}" >>"${recovery_file}"
 else
-  echo "${restore_command}" >> "${current_test_directory}/database/data/postgresql.conf"
+  echo "${restore_command}" >>"${current_test_directory}/database/data/postgresql.conf"
 fi
 
 echo "Restart restored pg_cluster"
 local_db_start_server "${TESTPGHOST}"
-popd > /dev/null
+popd >/dev/null
 
 i=0
-until ${PSQL} ${DBNAME} <<< "select * from t" | grep "for INCR"  > ${tmp}/sql.log  ; do
+until ${PSQL} ${DBNAME} <<<"select * from t" | grep "for INCR" >${tmp}/sql.log; do
   echo "waiting for query to succeed"
   sleep 1
-  i=$((i+1))
-  if [ $i -gt 10 ]; then echo "timeout waiting for query after recovery"; exit 1; fi
+  i=$((i + 1))
+  if [ $i -gt 10 ]; then
+    echo "timeout waiting for query after recovery"
+    exit 1
+  fi
 done
 
-pushd database/ > /dev/null
+pushd database/ >/dev/null
 local_db_stop_server "$TESTPGHOST"
-popd > /dev/null
+popd >/dev/null
 
 check_two_logs "${tmp}/tlog1.out" "${tmp}/tlog4.out"
-if (grep -q "for INCR" ${tmp}/sql.log)
-then
-   estat=0
+if (grep -q "for INCR" ${tmp}/sql.log); then
+  estat=0
 else
-   echo "Error: Database rows not found"
-   estat=1
+  echo "Error: Database rows not found"
+  estat=1
 fi
 
 end_test
diff --git a/systemtests/tests/tls-suites/testrunner-check-connections b/systemtests/tests/tls-suites/testrunner-check-connections
--- a/systemtests/tests/tls-suites/testrunner-check-connections
+++ b/systemtests/tests/tls-suites/testrunner-check-connections
@@ -1,7 +1,7 @@
 #!/bin/bash
 #   BAREOS® - Backup Archiving REcovery Open Sourced
 #
-#   Copyright (C) 2023-2024 Bareos GmbH & Co. KG
+#   Copyright (C) 2023-2025 Bareos GmbH & Co. KG
 #
 #   This program is Free Software; you can redistribute it and/or
 #   modify it under the terms of version three of the GNU Affero General Public
@@ -29,10 +29,10 @@ set -u
 TestName="$(basename "$(pwd)")"
 export TestName
 
-#shellcheck source=../environment.in
+#shellcheck source=../../environment.in
 . ./environment
 
-#shellcheck source=../scripts/functions
+#shellcheck source=../../scripts/functions
 . "${rscripts}"/functions
 #shellcheck source=functions
 . functions
@@ -44,8 +44,8 @@ function check_tls()
 {
   output=$(echo "exit" | ${BAREOS_BCONSOLE_BINARY} -c etc/bareos/"$1")
   if ! [ "$?" = "0" ]; then
-      echo "unexpected error while connecting with '$1'"
-      exit 3
+    echo "unexpected error while connecting with '$1'"
+    exit 3
   fi
   echo "$output" | grep "Encryption:" | sed 's/ Encryption: //'
 }
@@ -61,13 +61,13 @@ function test_con()
     tls=$(echo "$response" | cut -d' ' -f2 | tr -d '\r')
 
     if ! [ "$tls" = "TLSv1.3" ]; then
-        echo "expected 'TLSv1.3' got '$tls'"
-        exit 1
+      echo "expected 'TLSv1.3' got '$tls'"
+      exit 1
     fi
 
     if ! [ "$cipher" = "$1" ]; then
-        echo "expected '$1' got '$cipher'"
-        exit 2
+      echo "expected '$1' got '$cipher'"
+      exit 2
     fi
 
     no_test_was_ok=false
