bareos-ctl-funcs: test for execution issues
Its  possible for this command to fail completely (i.e. invalid
options passed to bareos), without it being a configuration issues.
These problems should still get caught however; even if the
configuration checking is supposed to be turned off.

diff --git a/systemtests/scripts/bareos-ctl-funcs b/systemtests/scripts/bareos-ctl-funcs
--- a/systemtests/scripts/bareos-ctl-funcs
+++ b/systemtests/scripts/bareos-ctl-funcs
@@ -184,12 +184,25 @@ check_config()
   log_file="${tmp}/bareos-$1-config-test.out"
   "$2" -t "${@:3}" &>"${log_file}"
 
-  if ! ${IGNORE_CONFIG_WARNINGS}; then
-    if grep -q "There are configuration warnings" "${log_file}"; then
-      echo "Fail: There are configuration warnings when running $2 -t ${*:3}, see below." >&2
-      cat "${log_file}"
-      return 7
-    fi
+  call_succeeded="$?"
+  config_warnings=false
+  if grep -q "There are configuration warnings" "${log_file}"; then
+    config_warnings=true
+  fi
+
+  if [ "${IGNORE_CONFIG_WARNINGS:-false}" != "true" ] && [ "${config_warnings}" = "true" ]; then
+    echo "Fail: There are configuration warnings when running $2 -t ${*:3}, see below." >&2
+    cat "${log_file}"
+    return 7
+  elif [ "${call_succeeded}" -ne 0 ] && ! [ "${config_warnings}" = "true" ]; then
+    # it is somewhat hard to correctly say when the call did not succeed
+    # vs it being a different issue.
+    # Its important to make sure that this branch is never taken, if there
+    # was a configuration issue & IGNORE_CONFIG_WARNINGS is set!
+    # Otherwise it would ruin the point of that variable!
+    echo "Fail: Could not run $2 -t ${*:3}, see below." >&2
+    cat "${log_file}"
+    return 7
   else
     cat "${log_file}"
   fi
