systemtests: run all systemtests with "bash -e"

diff --git a/systemtests/scripts/functions b/systemtests/scripts/functions
--- a/systemtests/scripts/functions
+++ b/systemtests/scripts/functions
@@ -243,8 +243,7 @@ set_debug()
 
 print_debug()
 {
-   echo "$*" | grep -q ERROR > /dev/null
-   if test $? -eq 0; then
+   if echo "$*" | grep -q ERROR > /dev/null; then
      echo "$*" >> "$tmp/err.log"
    fi
    if is_debug; then
@@ -552,28 +551,28 @@ change_jobname()
 
 check_two_logs()
 {
-   grep "^  Termination: *Backup OK" "${tmp}/log1.out" >/dev/null 2>&1
-   bstat=${bstat:-$?}
-   grep "^  Termination: .*Backup Error" "${tmp}/log1.out" >/dev/null 2>&1
-   if test $? -eq 0; then
+   if grep "^  Termination: *Backup OK" "${tmp}/log1.out" >/dev/null 2>&1; then
+     bstat=${bstat:-$?}
+   fi
+
+   if grep "^  Termination: .*Backup Error" "${tmp}/log1.out" >/dev/null 2>&1; then
       bstat=2
    fi
-   grep "^  Termination: *Restore OK" "${tmp}/log2.out" >/dev/null 2>&1
-   rstat=${rstat:-$?}
-   grep "^  Termination: .*Restore Error" "${tmp}/log2.out" >/dev/null 2>&1
-   if test $? -eq 0; then
+
+   if grep "^  Termination: *Restore OK" "${tmp}/log2.out" >/dev/null 2>&1; then
+     rstat=${rstat:-$?}
+   fi
+
+   if grep "^  Termination: .*Restore Error" "${tmp}/log2.out" >/dev/null 2>&1; then
       rstat=2
    fi
-   grep "^  Termination: *Restore OK -- warning file count mismatch" "${tmp}/log2.out" >/dev/null 2>&1
-   if test $? -eq 0; then
+   if grep "^  Termination: *Restore OK -- warning file count mismatch" "${tmp}/log2.out" >/dev/null 2>&1; then
       rstat=3
    fi
-   grep "^  Termination: .*Verify Differences" "${tmp}/log2.out" >/dev/null 2>&1
-   if test $? -eq 0; then
+   if grep "^  Termination: .*Verify Differences" "${tmp}/log2.out" >/dev/null 2>&1; then
       rstat=4
    fi
-   grep "Encoding error for database" "${tmp}/log1.out" > /dev/null
-   if test $? -eq 0; then
+   if grep "Encoding error for database" "${tmp}/log1.out" > /dev/null; then
       print_debug "Found database encoding error"
       bstat=2
    fi
