systemtests: skip mysql test if root
- Added a function skip_if_root in systemtests/scripts/functions
- Check running user and skip mysql test if root (podman)

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

diff --git a/systemtests/scripts/functions b/systemtests/scripts/functions
--- a/systemtests/scripts/functions
+++ b/systemtests/scripts/functions
@@ -1036,6 +1036,16 @@ if ! grep -q "${expected_result}" "${target_file}"; then
 fi
 }
 
+# Used by mysqltest 
+skip_if_root()
+{
+USER=$(whoami)
+if [ "$USER" == "root"  ]; then
+ echo "${TestName} test skipped: test cannot be run as user root."
+ exit 77;
+fi
+}
+
 REGRESS_DEBUG=${REGRESS_DEBUG:-0}
 if test "x${REGRESS_DEBUG}" = "x1"; then
    set_debug 1
