systemtests: support stdin for run_bconsole
this allows passing "-" as the file for run_bconsole to make it read the
script from stdin (you could also pass /dev/stdin for that).
This allows to write testrunners like this:
```
run_bconsole << EOT
status dir
``

diff --git a/systemtests/scripts/functions b/systemtests/scripts/functions
--- a/systemtests/scripts/functions
+++ b/systemtests/scripts/functions
@@ -594,18 +594,24 @@ traceback()
 
 run_bconsole()
 {
-  bconsole_file="${1:-${tmp}/bconcmds}"
+  local bconsole_file="${1:-${tmp}/bconcmds}"
   local error_code=0
-  local timeout=${BCONSOLE_TIMEOUT:-180s}
-  if [ -f "$bconsole_file" ]; then
-    check_config bconsole ${BAREOS_BCONSOLE_BINARY} -c ${BAREOS_CONFIG_DIR} || exit $?
+  local timeout="${BCONSOLE_TIMEOUT:-180s}"
+  if [ "${bconsole_file}" = - ]; then
+    bconsole_file=/dev/stdin
+  fi
+  if [ -f "${bconsole_file}" ]; then
+    check_config bconsole "${BAREOS_BCONSOLE_BINARY}" -c "${BAREOS_CONFIG_DIR}" || exit $?
     # 'cmd || ec=$?' is used to prevent "set -e" from killing the script
     # before we had the chance to kill the daemons (in case of timeout)
     if test "$debug" -eq 1; then
-      timeout "${timeout}" "${BAREOS_BCONSOLE_BINARY}" -c "${BAREOS_CONFIG_DIR}" <"$bconsole_file" || error_code=$?
+      timeout "${timeout}" "${BAREOS_BCONSOLE_BINARY}" -c "${BAREOS_CONFIG_DIR}" <"${bconsole_file}" || error_code=$?
     else
-      timeout "${timeout}" "${BAREOS_BCONSOLE_BINARY}" -c "${BAREOS_CONFIG_DIR}" <"$bconsole_file" 2>&1 >/dev/null || error_code=$?
+      timeout "${timeout}" "${BAREOS_BCONSOLE_BINARY}" -c "${BAREOS_CONFIG_DIR}" <"${bconsole_file}" 2>&1 >/dev/null || error_code=$?
     fi
+  else
+    echo "bconsole scriplet file ${bconsole_file} not found." >&2
+    return 1
   fi
   if ((error_code == 124)); then
     echo "+----------------------------------------+" >&2
