Rework database scripting.
Having the actual DDL (Data Definition Language) in scripts is not very
flexible so we move all DDL into seperate files. We also dropped all
database specific scripting and as such the generic script now knows
for all supported database types what to do on create/update/grant and
drop.

You can also have a read-only user on your database that is allowed
to select stuff but not anything else that might be interesting for
Management Queries.

The update script now can also upgrade from a database that is several
versions old. For now that means you can upgrade from a Bacula database
to the first Bareos database schema and also to the new Database schema
we are introducing with this patch. For the future it means the script
will perform all needed updates for you if its has the wanted so called
conversion available (e.g. the way to go from one version to an other.)

We also added more functionality to the bareos-config script and splitted
the function into a bareos-config-lib which can be included by scripts
so they can get config information like the working dir etc. This is
already used in all the new database scripts.

We also no longer use explicit absolute pathnames for database utilities
but make sure the utility can be found via the PATH, if your PATH already
provides the utility it will be used and otherwise the value will be used
that was determined at compile time.

Fixes #236: Hardcoded path for postgres (verison) in scripts

diff --git a/scripts/bareos-config.in b/scripts/bareos-config.in
--- a/scripts/bareos-config.in
+++ b/scripts/bareos-config.in
@@ -1,29 +1,12 @@
 #!/bin/sh
 
-DIR_CFG=@sysconfdir@
-CFG_DIR=${DIR_CFG}/bareos-dir.conf
-DIR_SCRIPTS=@scriptdir@
+LIB=@scriptdir@/bareos-config-lib.sh
 
-SEC_GROUPS="tape disk"
-
-WORKING_DIR="@working_dir@"
-FILE_DAEMON_USER="@fd_user@"
-FILE_DAEMON_GROUP="@fd_group@"
-STORAGE_DAEMON_USER="@sd_user@"
-STORAGE_DAEMON_GROUP="@sd_group@"
-DIRECTOR_DAEMON_USER="@dir_user@"
-DIRECTOR_DAEMON_GROUP="@dir_group@"
-
-PASSWORD_SUBST="\
-XXX_REPLACE_WITH_DIRECTOR_PASSWORD_XXX \
-XXX_REPLACE_WITH_CLIENT_PASSWORD_XXX \
-XXX_REPLACE_WITH_STORAGE_PASSWORD_XXX \
-XXX_REPLACE_WITH_DIRECTOR_MONITOR_PASSWORD_XXX \
-XXX_REPLACE_WITH_CLIENT_MONITOR_PASSWORD_XXX \
-XXX_REPLACE_WITH_STORAGE_MONITOR_PASSWORD_XXX \
-"
-
-os_type=`uname -s`
+if ! [ -r "$LIB" ]; then
+    echo "failed to read library $LIB"
+    exit 1
+fi
+. $LIB
 
 usage()
 {
@@ -38,253 +21,6 @@ help()
     usage
 }
 
-is_function()
-{
-    func=$1
-    test "$func" && type "$func" > /dev/null 2>&1
-    return $?
-}
-
-# does not work on all shells (only bash), 
-# therefore removed until a better solution is found
-# list_functions()
-# {
-#     if type typeset >/dev/null 2>&1; then
-#         # show available shell functions,
-#         # but exclude internal functions (name starts with "_" ...)
-#         typeset -F | cut -d " " -f 3 | grep "^[a-z]"
-#     else
-#         echo "function list not available"
-#     fi
-# }
-
-get_user_fd()
-{
-    echo "${FILE_DAEMON_USER}"
-}
-
-get_group_fd()
-{
-    echo "${FILE_DAEMON_GROUP}"
-}
-
-get_user_sd()
-{
-    echo "${STORAGE_DAEMON_USER}"
-}
-
-get_group_sd()
-{
-    echo "${STORAGE_DAEMON_GROUP}"
-}
-
-get_user_dir()
-{
-    echo "${DIRECTOR_DAEMON_USER}"
-}
-
-get_group_dir()
-{
-    echo "${DIRECTOR_DAEMON_GROUP}"
-}
-
-[ ${os_type} = Linux ] && \
-setup_sd_user()
-{
-    #
-    # guaranties that storage-daemon user and group exists
-    # and storage-daemon user belongs to the required groups.
-    #
-    # normally, storage-daemon user
-    # is already installed by the package preinstall script.
-    #
-
-    #
-    # See what secondary groups exist for the sd user to be added to.
-    #
-    ADD_GROUPS=""
-    for sec_group in ${SEC_GROUPS}; do
-        cnt=`getent group ${sec_group} | wc -l`
-        if [ ${cnt} -gt 0 ]; then
-            [ -z "${ADD_GROUPS}" ] && ADD_GROUPS="-G ${sec_group}" || ADD_GROUPS="${ADD_GROUPS},${sec_group}"
-        fi
-    done
-
-    getent group ${STORAGE_DAEMON_GROUP} > /dev/null || groupadd -r ${STORAGE_DAEMON_GROUP}
-
-    #
-    # If the user doesn't exist create a new one otherwise modify it to have the wanted secondary groups.
-    #
-    if [ "${STORAGE_DAEMON_USER}" != "root" ]; then
-        getent passwd ${STORAGE_DAEMON_USER} > /dev/null
-        if [ $? -ne 0 ]; then
-            # create a new storage_daemon_user
-            useradd -r --comment "bareos" --home ${WORKING_DIR} -g ${STORAGE_DAEMON_GROUP} ${ADD_GROUPS} --shell /bin/false ${STORAGE_DAEMON_USER}
-        fi
-
-        # if the user has already created before,
-        # make sure the correct primary group is set otherwise fix it.
-        if [ "`id -gn ${STORAGE_DAEMON_USER}`" != "${STORAGE_DAEMON_GROUP}" ]; then
-            usermod -g ${STORAGE_DAEMON_GROUP} ${STORAGE_DAEMON_USER}
-        fi
-
-        # add the storage_daemon_user to additional groups (if defined)
-        [ "${ADD_GROUPS}" ] && usermod ${ADD_GROUPS} ${STORAGE_DAEMON_USER}
-    fi
-}
-
-[ ${os_type} != Linux ] && \
-setup_sd_user()
-{
-   echo "setup_sd_user() is not supported on this platform"
-   exit 1
-}
-
-get_database_driver()
-{
-    if ! [ -r "${CFG_DIR}" ]; then
-        return
-    fi
-
-    # get dbdriver, that is defined in director configuration.
-    # If string is still set to default, return nothing
-    DBDRIVER=`sed -r -n 's/^\s*dbdriver\s*=\s*["]?([^"]*)["]?/\1/ip' "${CFG_DIR}" | grep -v "XXX_REPLACE_WITH_DATABASE_DRIVER_XXX"`
-
-    echo "$DBDRIVER"
-}
-
-get_databases_installed()
-{
-    #for i in `ls ${DIR_SCRIPTS}/create_*_database`
-    #do
-    #    sed -n -r 's#.*/create_([a-z]+)_database#\1#p' <<<$i | grep -v bareos
-    #done
-
-    # manually check different backends, to get the correct order
-    [ -e ${DIR_SCRIPTS}/create_postgresql_database ] && echo "postgresql"
-    [ -e ${DIR_SCRIPTS}/create_mysql_database ] && echo "mysql"
-    [ -e ${DIR_SCRIPTS}/create_sqlite3_database ] && echo "sqlite3"
-}
-
-get_database_driver_default()
-{
-    DBDRIVER=`get_database_driver`
-
-    if [ -z "$DBDRIVER" ]; then
-        DBDRIVER=`get_databases_installed | head -n 1`
-    fi
-
-    if [ -z "$DBDRIVER" ]; then
-        # fallback and first choice
-        DBDRIVER="postgresql"
-    fi
-
-    echo "$DBDRIVER"
-}
-
-initialize_database_driver()
-{
-    DBDRIVER=`get_database_driver_default`
-    replace "XXX_REPLACE_WITH_DATABASE_DRIVER_XXX" "${DBDRIVER}"
-}
-
-get_local_hostname()
-{
-    # put actual short hostname in configuration files
-    # try to get short hostname
-    hname=`hostname -s`
-    if [ -z "$hname" ]; then
-        # try to get long hostname
-        hname=`hostname|sed 's/\..*//g'`
-        if [ -z "$hname" ]; then
-            # set to "localhost"
-            hname='localhost'
-        fi
-    fi
-    echo "$hname"
-}
-
-replace()
-{
-    if ! [ $# -eq 2 ]; then
-        return 1
-    fi
-
-    SEARCH="$1"
-    REPLACE="$2"
-
-    for file in `grep -l ${SEARCH} ${DIR_CFG}/*.conf`
-    do
-        echo "replacing '${SEARCH}' with '${REPLACE}' in $file"
-        sed -i'' "s#${SEARCH}#${REPLACE}#g" ${file};
-    done
-    return 0
-}
-
-initialize_local_hostname()
-{
-    #
-    # Replace all XXX_REPLACE_WITH_LOCAL_HOSTNAME by the local hostname.
-    #
-    hname=`get_local_hostname`
-    replace "XXX_REPLACE_WITH_LOCAL_HOSTNAME_XXX-dir" "${hname}-dir"
-    replace "XXX_REPLACE_WITH_LOCAL_HOSTNAME_XXX-fd" "${hname}-fd"
-    replace "XXX_REPLACE_WITH_LOCAL_HOSTNAME_XXX-sd" "${hname}-sd"
-    replace "XXX_REPLACE_WITH_LOCAL_HOSTNAME_XXX-mon" "${hname}-mon"
-    replace "XXX_REPLACE_WITH_LOCAL_HOSTNAME_XXX" "${hname}"
-}
-
-replace_password()
-{
-    if ! [ $# -eq 2 ]; then
-        return 1
-    fi
-
-    SEARCH="$1"
-    REPLACE="$2"
-
-    for file in `grep -l ${SEARCH} ${DIR_CFG}/*.conf`
-    do
-        echo "replacing '${SEARCH}' in $file"
-        sed -i'' "s#${SEARCH}#${REPLACE}#g" ${file};
-    done
-    return 0
-}
-
-initialize_passwords()
-{
-    #
-    # See if we need to generate a set of random passwords.
-    #
-    if [ ! -f ${DIR_CFG}/.rndpwd ]; then
-        for string in ${PASSWORD_SUBST}
-        do
-           pass=`openssl rand -base64 33`
-           echo "${string}=${pass}" >> ${DIR_CFG}/.rndpwd
-        done
-        chmod 400 ${DIR_CFG}/.rndpwd
-    fi
-
-    # Source the passwords
-    . ${DIR_CFG}/.rndpwd
-
-    for string in ${PASSWORD_SUBST}
-    do
-        eval "pass=\${$string}"
-        if [ ! -z "${pass}" ]; then
-            replace_password "${string}" "${pass}"
-        fi
-    done
-}
-
-init()
-{
-    initialize_local_hostname
-    #initialize_director_hostname
-    initialize_passwords
-    initialize_database_driver
-}
-
 # number of args passed
 args=$#
 
@@ -294,7 +30,7 @@ args=$#
 if [ $args -ge 1 ]; then
     # executes given arguments
     if is_function $1; then
-        $*
+        "$@"
     else
         echo "failed to execute $*. Not found."
         #usage
diff --git a/src/cats/create_bareos_database.in b/src/cats/create_bareos_database.in
--- a/src/cats/create_bareos_database.in
+++ b/src/cats/create_bareos_database.in
@@ -1,11 +1,40 @@
 #!/bin/sh
 #
-# This routine creates the Bareos database
-# using PostgreSQL, Ingres, MySQL, or SQLite.
+# BAREOS® - Backup Archiving REcovery Open Sourced
+#
+# Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
+# Copyright (C) 2013-2014 Bareos GmbH & Co. KG
+#
+# This program is Free Software; you can redistribute it and/or
+# modify it under the terms of version three of the GNU Affero General Public
+# License as published by the Free Software Foundation and included
+# in the file LICENSE.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+# Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+#
+# This routine makes the appropriately configured
+# Bareos database for PostgreSQL, Ingres, MySQL, or SQLite.
 #
 
-default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
+#
+# Source the Bareos config functions.
+#
+. @scriptdir@/bareos-config-lib.sh
 
+db_name="${db_name:-@db_name@}"
+db_user="${db_user:-@db_user@}"
+dir_user=`get_user_dir`
+dir_group=`get_group_dir`
+default_db_type=`get_database_driver_default`
+working_dir=`get_working_dir`
 
 #
 # See if the first argument is a valid backend name.
@@ -13,24 +42,24 @@ default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
 #
 if [ $# -gt 0 ]; then
    case $1 in
-     sqlite3)
-       db_type=$1
-       shift
-       ;;
-     mysql)
-       db_type=$1
-       shift
-       ;;
-     postgresql)
-       db_type=$1
-       shift
-       ;;
-     ingres)
-       db_type=$1
-       shift
-       ;;
-     *)
-       ;;
+      sqlite3)
+         db_type=$1
+         shift
+         ;;
+      mysql)
+         db_type=$1
+         shift
+         ;;
+      postgresql)
+         db_type=$1
+         shift
+         ;;
+      ingres)
+         db_type=$1
+         shift
+         ;;
+      *)
+         ;;
    esac
 fi
 
@@ -42,4 +71,95 @@ if [ -z "${db_type}" ]; then
 fi
 
 echo "Creating ${db_type} database"
-@scriptdir@/create_${db_type}_database $*
+
+bindir=`get_database_utility_path ${db_type}`
+if [ ! -z "${bindir}" ]; then
+   PATH="$bindir:$PATH"
+fi
+
+case ${db_type} in
+   sqlite3)
+      sqlite3 $* ${working_dir}/${db_name}.db ".tables"
+      # Allow non root access
+      chown ${dir_user}:${dir_group} ${working_dir}/${db_name}.db
+      chmod 0640 ${working_dir}/${db_name}.db
+      retval=0
+      ;;
+   mysql)
+      mysql $* -e "CREATE DATABASE ${db_name};"
+      retval=$?
+      ;;
+   postgresql)
+      #
+      # use SQL_ASCII to be able to put any filename into
+      # the database even those created with unusual character sets
+      PSQLVERSION=`psql -d template1 -c 'SELECT version()' $* 2>/dev/null | \
+                   awk '/PostgreSQL/ { print $2 }' | \
+                   cut -d '.' -f 1,2`
+
+      if [ -z "${PSQLVERSION}" ]; then
+         echo "Unable to determine PostgreSQL version."
+         exit 1
+      fi
+
+      #
+      # Note, LC_COLLATE and LC_TYPE are needed on 8.4 and beyond, but are not implemented in 8.3 or below.
+      # This must be updated for future versions of PostgreSQL
+      #
+      case ${PSQLVERSION} in
+         9.*)
+	    ENCODING="ENCODING 'SQL_ASCII' LC_COLLATE 'C' LC_CTYPE 'C'"
+            ;;
+         8.[456789])
+	    ENCODING="ENCODING 'SQL_ASCII' LC_COLLATE 'C' LC_CTYPE 'C'"
+            ;;
+         *)
+	    ENCODING="ENCODING 'SQL_ASCII'"
+            ;;
+      esac
+
+      psql -f - -d template1 $* << END-OF-DATA
+\set ON_ERROR_STOP on
+CREATE DATABASE ${db_name} $ENCODING TEMPLATE template0;
+ALTER DATABASE ${db_name} SET datestyle TO 'ISO, YMD';
+END-OF-DATA
+      retval=$?
+
+      if psql -l ${dbname} | grep " ${db_name}.*SQL_ASCII" >/dev/null; then
+         echo "Database encoding OK"
+      else
+         echo " "
+         echo "Database encoding bad. Do not use this database"
+         echo " "
+      fi
+      ;;
+   ingres)
+      #
+      # Use SQL_ASCII to be able to put any filename into
+      # the database even those created with unusual character sets
+      #
+      ENCODING="ENCODING 'SQL_ASCII'"
+
+      #
+      # use UTF8 if you are using standard Unix/Linux LANG specifications
+      # that use UTF8 -- this is normally the default and *should* be
+      # your standard.  Bareos works correctly *only* with correct UTF8.
+      #
+      # Note, with this encoding, if you have any "weird" filenames on
+      # your system (names generated from Win32 or Mac OS), you may
+      # get Bareos batch insert failures.
+      #
+      #ENCODING="ENCODING 'UTF8'"
+
+      createdb -u${db_user} $* ${db_name}
+      retval=$?
+      ;;
+esac
+
+if [ ${retval} = 0 ]; then
+   echo "Creating of ${db_name} database succeeded."
+else
+   echo "Creating of ${db_name} database failed."
+fi
+
+exit ${retval}
diff --git a/src/cats/grant_bareos_privileges.in b/src/cats/grant_bareos_privileges.in
--- a/src/cats/grant_bareos_privileges.in
+++ b/src/cats/grant_bareos_privileges.in
@@ -1,11 +1,41 @@
 #!/bin/sh
 #
-# This routine makes the appropriately configured
-# Bareos tables for PostgreSQL or MySQL.
-# SQLite does not have permissions.
+# BAREOS® - Backup Archiving REcovery Open Sourced
+#
+# Copyright (C) 2000-2011 Free Software Foundation Europe e.V.
+# Copyright (C) 2013-2014 Bareos GmbH & Co. KG
+#
+# This program is Free Software; you can redistribute it and/or
+# modify it under the terms of version three of the GNU Affero General Public
+# License as published by the Free Software Foundation and included
+# in the file LICENSE.
+#
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+# Affero General Public License for more details.
+#
+# You should have received a copy of the GNU Affero General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
+# 02110-1301, USA.
+#
+# shell script to grant privileges to the bareos database
+# for PostgreSQL, Ingres, MySQL, or SQLite.
 #
 
-default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
+#
+# Source the Bareos config functions.
+#
+. @scriptdir@/bareos-config-lib.sh
+
+db_name="${db_name:-@db_name@}"
+db_user="${db_user:-@db_user@}"
+db_password="${db_password:-@db_password@}"
+db_version=`get_database_version`
+bareos_sql_ddl=`get_database_ddl_dir`
+temp_sql_grants="/tmp/grants.sql.$$"
+default_db_type=`get_database_driver_default`
 
 #
 # See if the first argument is a valid backend name.
@@ -13,24 +43,24 @@ default_db_type=`@scriptdir@/bareos-config get_database_driver_default`
 #
 if [ $# -gt 0 ]; then
    case $1 in
-     sqlite3)
-       db_type=$1
-       shift
-       ;;
-     mysql)
-       db_type=$1
-       shift
-       ;;
-     postgresql)
-       db_type=$1
-       shift
-       ;;
-     ingres)
-       db_type=$1
-       shift
-       ;;
-     *)
-       ;;
+      sqlite3)
+         db_type=$1
+         shift
+         ;;
+      mysql)
+         db_type=$1
+         shift
+         ;;
+      postgresql)
+         db_type=$1
+         shift
+         ;;
+      ingres)
+         db_type=$1
+         shift
+         ;;
+      *)
+         ;;
    esac
 fi
 
@@ -41,5 +71,53 @@ if [ -z "${db_type}" ]; then
    db_type="${default_db_type}"
 fi
 
-echo "Granting ${db_type} privileges"
-@scriptdir@/grant_${db_type}_privileges $*
+echo "Granting ${db_type} tables"
+
+if ! get_database_grant_priviliges "${db_type}" "${db_user}" "${db_password}" > ${temp_sql_grants}; then
+    echo "Error creating privileges."
+    exit 1
+fi
+
+bindir=`get_database_utility_path ${db_type}`
+if [ ! -z "${bindir}" ]; then
+   PATH="$bindir:$PATH"
+fi
+
+case ${db_type} in
+   sqlite3)
+      #
+      # Nothing to do for SQLite3
+      #
+      retval=0
+      ;;
+   mysql)
+      mysql $* -f < ${temp_sql_grants}
+
+      retval=$?
+      ;;
+   postgresql)
+      psql -f ${temp_sql_grants} -d ${db_name} $*
+
+      retval=$?
+      ;;
+   ingres)
+      sql iidbdb $* << END-OF-DATA
+      CREATE USER ${db_user} ${pass}
+      \g
+END-OF-DATA
+
+      sql -u${db_user} $* ${db_name} < ${temp_sql_grants}
+
+      retval=$?
+      ;;
+esac
+
+rm -f ${temp_sql_grants}
+
+if [ ${retval} = 0 ]; then
+   echo "Privileges for user ${db_user} granted ON database ${db_name}."
+else
+   echo "Error creating privileges."
+fi
+
+exit ${retval}
