Added new default configuration based on directory structure
Added a new default configuration under
  configs/BASE/

It contains a basic configuration for all components as configuration
directories (bareos >= 16.2.4).
It also uses TLS, as we expect that if the test succeeds with TLS it
would proberly also succeed without.

One major advantages of using the configuration subdirectory structure
is that it is now easy to added additional resources to the
configuration of a test.
Tests specific resoures that are defined in
  * configs/$TestName
extends (or overwrites) the configuration defined in configs/BASE.

Tests:
  * tests/tls-client-initiated-connection-backup-test
    * adapted to use the new configuration directory structure

  * tests/config-add-client-test
    * new test, that adds clients via configuration API

  * tests/1-example-test
    * example tests, including comments to give a basis for creating
      additional tests.

diff --git a/scripts/cleanup b/scripts/cleanup
--- a/scripts/cleanup
+++ b/scripts/cleanup
@@ -1,10 +1,16 @@
 #!/bin/sh
+
 #
 # Cleanup left over files -- both before and after test run
 #
 
 . ./config
 . scripts/functions
+
+if ! [ -f ${working}/CLEANUPMARKER ]; then
+    print_debug "SKIPPED: cleanup. Looks like it is already clean."
+    exit 0
+fi
 
 cwd=`pwd`
 
@@ -17,9 +23,15 @@ rm -rf ${working}/log ${tmp}/Backup-*
 rm -rf ${working}/*.bsr ${working}/log*.sd
 rm -rf ${working}/*.trace ${working}/*.traceback ${working}/*.bactrace
 rm -rf ${working}/*.state
+rm -rf ${working}/CLEANUPMARKER
 rm -rf ${tmp}disk-changer
 rm -f ${cwd}/bin/plugins/test-plugin-fd.so
 find . -name "gigaslam.gif" -exec rm -f {} \;
+# cleanup old config files
+rm -f  ${conf}/bareos-*.conf
+rm -rf ${conf}/bareos-*.d/
+rm -rf ${conf}/bareos-dir-export/
+
 
 # bin directory does not always exist
 if [ -d ${bin} ] ; then
diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -1,15 +1,56 @@
+#!/bin/sh
+
 #
 # A set of useful functions to be sourced in each test
 #
 
+copy_configs()
+{
+    COMPONENTS="bareos-dir bareos-sd bareos-fd bconsole"
+    CONFIGDIRS="BASE ${TestName} $@"
+    FOUND=""
+
+    for component in $COMPONENTS; do
+        # try to find a config file, store the most specific.
+        FOUND=""
+        for directory in $CONFIGDIRS; do
+            if [ -f ${rconfigs}/${directory}/${component}.conf ]; then
+                FOUND=${rconfigs}/${directory}/${component}.conf
+            fi
+        done
+        if [ "$FOUND" ]; then
+            /bin/cp ${FOUND} ${conf}
+        else
+            # copy all config files from subdirectories,
+            # start with the most generic.
+            for directory in $CONFIGDIRS; do
+                if [ -d ${rconfigs}/${directory}/${component}.d ]; then
+                    /bin/cp -r ${rconfigs}/${directory}/${component}.d ${conf}
+                fi
+            done
+        fi
+    done
+
+    # copy certificates
+    for directory in $CONFIGDIRS; do
+        if [ -d ${rconfigs}/${directory}/tls/ ]; then
+            /bin/cp -r ${rconfigs}/${directory}/tls ${conf}
+        fi
+    done
+}
 
 check_encoding()
 {
-   ${bin}/bareos-dir -d50 -t -c ${conf}/bareos-dir.conf 2>&1 | grep 'Wanted SQL_ASCII, got UTF8' >/dev/null
+   ${bin}/bareos-dir -d50 -t 2>&1 | grep 'Wanted SQL_ASCII, got UTF8' >/dev/null
    if [ $? = 0 ]; then
        echo "Found database encoding problem, please modify the database encoding (SQL_ASCII)"
        exit 1
    fi
+}
+
+cleanup()
+{
+    ${rscripts}/cleanup
 }
 
 start_test()
@@ -19,8 +60,10 @@ start_test()
    outf="${tmp}/sed_tmp"
    echo "s%  mail =%# mail = %g" >${outf}
    echo "s%  operator =%# operator =%g" >>${outf}
-   cp ${conf}/bareos-dir.conf ${tmp}/1
-   sed -f ${outf} ${tmp}/1 > ${conf}/bareos-dir.conf
+   if [ -f ${conf}/bareos-dir.conf ]; then
+      cp ${conf}/bareos-dir.conf ${tmp}/1
+      sed -f ${outf} ${tmp}/1 > ${conf}/bareos-dir.conf
+   fi
    echo " "
    echo " "
    echo " === Starting $TestName at `date +%R:%S` ==="
@@ -34,6 +77,8 @@ start_test()
    bstat=0
    rstat=0
    dstat=0
+   # marker for cleanup()
+   date > ${working}/CLEANUPMARKER
 }
 
 require_root()
@@ -111,6 +156,12 @@ print_debug()
    fi
 }
 
+set_error()
+{
+    estat=9
+    echo "ERROR: $@" >> $tmp/err.log
+}
+
 check_files_written()
 {
     LOG=$1
@@ -161,23 +212,24 @@ run_bareos()
      ${scripts}/bareos-ctl-sd start -m
      ${scripts}/bareos-ctl-fd start -m $1
      ${scripts}/bareos-ctl-dir start -m
-     cat ${tmp}/bconcmds | ${bin}/bconsole -c ${conf}/bconsole.conf
-     return $?
    else
      ${scripts}/bareos start >/dev/null 2>&1
-     cat ${tmp}/bconcmds | ${bin}/bconsole -c ${conf}/bconsole.conf >/dev/null 2>&1
-     return $?
    fi
+   run_bconsole
+   return $?
 }
 
 run_bconsole()
 {
    bconsole_file=${1:-${tmp}/bconcmds}
-   if test "$debug" -eq 1 ; then
-     cat $bconsole_file | ${bin}/bconsole -c ${conf}/bconsole.conf
-   else
-     cat $bconsole_file | ${bin}/bconsole -c ${conf}/bconsole.conf  2>&1 >/dev/null
+   if [ -f $bconsole_file ]; then
+      if test "$debug" -eq 1 ; then
+        cat $bconsole_file | ${bin}/bconsole
+      else
+        cat $bconsole_file | ${bin}/bconsole 2>&1 >/dev/null
+      fi
    fi
+   return $?
 }
 
 run_btape()
@@ -275,11 +327,12 @@ check_two_logs()
 
 check_restore_diff()
 {
+   dest=${1:-$src}
    if test "$debug" -eq 1 ; then
-      $rscripts/diff.pl -s ${src} -d ${tmp}/bareos-restores${src}
-      diff -ur ${src} ${tmp}/bareos-restores${src}
+      $rscripts/diff.pl -s ${dest} -d ${tmp}/bareos-restores/${dest}
+      diff -ur ${dest} ${tmp}/bareos-restores/${dest}
    else
-      diff -ur ${src} ${tmp}/bareos-restores${src} 2>&1 >/dev/null
+      diff -ur ${dest} ${tmp}/bareos-restores/${dest} 2>&1 >/dev/null
    fi
    dstat=$?
 }
