testrunner finish tools testing part.
add --director mandatory configuration parameter for tools to
precise which KEK has to be used.

diff --git a/systemtests/tests/scsicrypto/testrunner-backup-bscrypto b/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
--- a/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
+++ b/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
@@ -202,14 +202,6 @@ expect_grep "Restore OK" \
 
 check_restore_diff "${BackupDirectory}"
 
-# Check if crypto cache is there and readable.
-# Again clear the key from the drive
-if ! "${mybsc}" -d250 --dt --clear-encryption "${ltodrive}"; then
-  printf "Clearing KEK failed \n"
-  export estat=1
-  exit 1
-fi
-
 # Dump cache
 crypto_cache_log=$tmp/crypto_cache.log
 crypto_cache="${working_dir}/bareos-sd.${BAREOS_STORAGE_PORT}.cryptoc"
@@ -222,6 +214,14 @@ expect_grep "${volume}" \
             "${crypto_cache_log}" \
             "Volume ${volume} not found in cache dump".
 
+# Check if crypto cache is there and readable.
+# Again clear the key from the drive
+if ! "${mybsc}" -d250 --dt --clear-encryption "${ltodrive}"; then
+  printf "Clearing KEK failed \n"
+  export estat=1
+  exit 1
+fi
+
 # With wrapped key volume in crypto cache we should be able
 # to check the drive and volume encryption status
 
@@ -229,31 +229,24 @@ expect_grep "${volume}" \
 # then use the key to setup the drive and being then able to
 # to read back data from the volume 
 
-# the test should also check that when the drive as no key
-# no data can be read from the volume.
+# the test should also check that when the drive as no key,
+# then no data can be read from the volume.
 # Otherwise it mean we wrote clear data on it !!!
 
-# for the moment we don't have tools that works with encrypted tapes.
-# the drive and volume status by bscsicrypto after using bls.
-# show a key has been loaded by doesn't seems to work.
-
-# We need to fix this key loading compared to scscicrypto plugin.
-
-# when used by the tools the key in log output is not similar than during backup/restore
-# 29-fév-2024 13:36:39.422351 bareos-sd (200): scsicrypto/scsicrypto-sd.cc:359-2 scsicrypto-sd: Loading new crypto key [Eya3t/(z|3B+)5G8mAmAR2<Rfh4p(d#
-# versus
-# 29-fév-2024 14:09:47.125765 bls (200): scsicrypto/scsicrypto-sd.cc:359-0 scsicrypto-sd: Loading new crypto key ˯�TQ�����e�g���K�▒�(&v����������Bo
-# 29-fév-2024 14:14:11.315839 bextract (200): scsicrypto/scsicrypto-sd.cc:359-0 scsicrypto-sd: Loading new crypto key ˯�TQ�����e�g���K�▒�(&v����������Bo
+# beware to work the tools bls,bextract etc need the have
+# --director(-D) parameter to determined which KEK to use
+# (defined in bareos-sd.d/director resource)
 
 # Test volume content listing
-# export confdir for mtx-changer
+# export confdir for mtx-changer so mtx-changer find it.
 export confdir=$(pwd)/etc/bareos
 # load the tape into the drive
-/usr/sbin/mtx -f "${changer}" load 1 0 ||:
+slot=$(mtx -f $changer status | awk -F ":" "/VolumeTag=${volume}/ {gsub(\"Storage Element\",\"\",\$1);gsub(\" \",\"\",\$1); print \$1}")
+/usr/sbin/mtx -f "${changer}" load ${slot} 0 ||:
 /usr/bin/mt -f "${ltodrive}" rewind ||:
 bls_lj_log=$tmp/bls-label_job_output.log
 tape_device=$(awk -F '=' '/^ .*Name.*=.*tapedrive-0.*/ {gsub(" ","",$2);gsub("\"","",$2);print $2}' etc/bareos/bareos-sd.d/device/tape_devices.conf)
-sbin/bls-"${TestName}" -d250 -v -c "$(pwd)/etc/bareos" -L -j -V ${volume} ${tape_device} > "${bls_lj_log}"
+sbin/bls-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" --director "bareos-dir" -L -j -V ${volume} ${tape_device} > "${bls_lj_log}"
 
 expect_grep "Crypto cache read 1 entries" \
             "$bls_lj_log" \
@@ -264,8 +257,8 @@ expect_grep "JobId             : 1" \
             "BLS jobid not found."
 
 bls_log=$tmp/bls-full_output.log
-sbin/bls-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" -V ${volume} ${tape_device} > "${bls_log}"
-expect_grep "bls JobId 0: Ready to read from volume \"${volume}\" on device \"tapedrive-0-.dev.tape.by-id.scsi-350223344ab000100-nst\"" \
+sbin/bls-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" --director "bareos-dir" -V ${volume} ${tape_device} > "${bls_log}"
+expect_grep "bls JobId 0: Ready to read from volume \"${volume}\" on device \"${tape_device}\"" \
             "${bls_log}" \
             "BLS failed to read volume."
 
@@ -274,7 +267,7 @@ rm -rf "${restore_directory}"
 mkdir -p "${restore_directory}" ||:
 bextract_log="${tmp}/bextract-output.log"
 # Test volume extraction
-sbin/bextract-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" -V ${volume} ${tape_device} "${restore_directory}" > "${bextract_log}"
+sbin/bextract-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" --director "bareos-dir" -V ${volume} ${tape_device} "${restore_directory}" > "${bextract_log}"
 expect_grep "Crypto cache read 1 entries" \
             "${bextract_log}" \
             "bextract: no crypto cache entry found."
