add check on extracted value before using

diff --git a/systemtests/tests/scsicrypto/testrunner-backup-bscrypto b/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
--- a/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
+++ b/systemtests/tests/scsicrypto/testrunner-backup-bscrypto
@@ -252,6 +252,11 @@ slot=$(mtx -f $changer status | awk -F ":" "/VolumeTag=${volume}/ {gsub(\"Storag
 /usr/bin/mt -f "${ltodrive}" rewind || :
 bls_lj_log=$tmp/bls-label_job_output.log
 bareos_tape_device=$(awk -F '=' '/^ .*Name.*=.*tapedrive.*-0.*/ {gsub(" ","",$2);gsub("\"","",$2);print $2}' etc/bareos/bareos-sd.d/device/tape_devices.conf)
+if [ -z "${bareos_tape_device}" ]; then
+  printf "Failed to extract bareos_tape_device from config\n"
+  export estat=1
+  exit 1
+fi
 sbin/bls-"${TestName}" -d10 -v -c "$(pwd)/etc/bareos" --director "bareos-dir" -L -j -V ${volume} ${bareos_tape_device} >"${bls_lj_log}"
 
 expect_grep "Crypto cache read 1 entries" \
