systemtest proxmox: do backup and reover of one vm

diff --git a/systemtests/tests/py3plug-fd-proxmox/testrunner b/systemtests/tests/py3plug-fd-proxmox/testrunner
--- a/systemtests/tests/py3plug-fd-proxmox/testrunner
+++ b/systemtests/tests/py3plug-fd-proxmox/testrunner
@@ -10,18 +10,21 @@ set -u
 TestName="$(basename "$(pwd)")"
 export TestName
 
-JobName=backup-bareos-fd
+JobName=backup-proxmox-vm
 #shellcheck source=../environment.in
 . ./environment
 
 export PATH="${current_test_directory}/sbin:${current_test_directory}/bin:$PATH"
 
-JobName=backup-bareos-fd
+JobName=backup-proxmox-vm
 #shellcheck source=../scripts/functions
 . "${rscripts}"/functions
 "${rscripts}"/cleanup
 "${rscripts}"/setup
 
+VMID=999001
+qm destroy "${VMID}" || :
+qm create "${VMID}" --ostype l26 --memory 512 --name plugtestvm --scsi0 ZFS:2
 
 start_test
 
@@ -38,40 +41,53 @@ status storage=File
 wait
 messages
 
+END_OF_DATA
 
+run_bareos "$@"
 
-@#
-@# now do an incremental
-@#
-run job=$JobName yes
-wait
-messages
+qm destroy "${VMID}"
 
+# make sure VMID was destroyed
+qm list | grep -v "${VMID}"
 
+cat <<END_OF_DATA2 >$tmp/bconcmds
 @#
 @# now do a restore
 @#
 @$out $tmp/log2.out
 wait
-restore client=bareos-fd fileset=ProxmoxTest where=$tmp/bareos-restores pluginoptions=python:localvmdk=yes select all done
+restore client=bareos-fd fileset=ProxmoxTestVM where=/ select all done
 yes
 wait
 messages
 quit
-END_OF_DATA
+
+END_OF_DATA2
+
+# pluginoptions=python:localvmdk=yes 
 
 run_bareos "$@"
+
+# make sure VMID was  recovered
+qm list | grep -v "${VMID}"
+
+
+
 check_for_zombie_jobs storage=File
 
 check_two_logs
 
+
+
+
+
 # Check restored disk image content
-restored_disk_image=$(find $tmp/bareos-restores -type f  -name "*.vmdk" | tail -1)
-if file "$restored_disk_image" | grep "Proxmox4 disk image"; then
-    echo "Restored disk image type OK"
-else
-    echo "Restored disk image ERROR: is not Proxmox disk image"
-    dstat=1
-fi
+#restored_disk_image=$(find $tmp/bareos-restores -type f  -name "*.vmdk" | tail -1)
+#if file "$restored_disk_image" | grep "Proxmox4 disk image"; then
+#    echo "Restored disk image type OK"
+#else
+#    echo "Restored disk image ERROR: is not Proxmox disk image"
+#    dstat=1
+#fi
 
 end_test
