bareos-basic: fix check for non existing file on windows
dangling-link does not get created on windows, so we need to chose a
different file.

diff --git a/systemtests/tests/bareos-basic/testrunner-bls-autoxflate b/systemtests/tests/bareos-basic/testrunner-bls-autoxflate
--- a/systemtests/tests/bareos-basic/testrunner-bls-autoxflate
+++ b/systemtests/tests/bareos-basic/testrunner-bls-autoxflate
@@ -25,9 +25,10 @@ if [ $ret -ne 0 ]; then
   exit $ret
 fi
 
-if ! grep -q "weird-files/dangling-link" "$tmp/bls.out"; then
-  echo 'Expected string \"weird-files/dangling-link\" not found in  bls output'
-  stop_bareos
+FILE="weird-files/softlinkee"
+
+if ! grep -q "${FILE}" "$tmp/bls.out"; then
+  echo "Expected string \"${FILE}\" not found in bls output"
   exit 1
 fi
 
