introduce skip_if_windows function

diff --git a/systemtests/tests/bscan-bextract-bls-bcopy/testrunner b/systemtests/tests/bscan-bextract-bls-bcopy/testrunner
--- a/systemtests/tests/bscan-bextract-bls-bcopy/testrunner
+++ b/systemtests/tests/bscan-bextract-bls-bcopy/testrunner
@@ -55,8 +55,8 @@ if [ $ret -ne 0 ]; then
   exit $ret
 fi
 
-if ! grep -q "weird-files.*dangling-link" "$tmp/bls.out"; then
-  echo 'Expected string \"weird-files.dangling-link\" not found in  bls output'
+if ! grep -q "tests.bregtest.c" "$tmp/bls.out"; then
+  echo 'Expected string \"tests.bregtest.c\" not found in  bls output'
   stop_bareos
   exit 1
 fi
