refactor: apply shell format to core/scripts
also changed their indentation to 2 spaces.

diff --git a/core/scripts/bareos-config.in b/core/scripts/bareos-config.in
--- a/core/scripts/bareos-config.in
+++ b/core/scripts/bareos-config.in
@@ -21,22 +21,20 @@
 LIB="@scriptdir@/bareos-config-lib.sh"
 
 if ! [ -r "${LIB}" ]; then
-    echo "failed to read library ${LIB}"
-    exit 1
+  echo "failed to read library ${LIB}"
+  exit 1
 fi
 . "${LIB}"
 
-usage()
-{
-cat <<-EOT
+usage() {
+  cat <<-EOT
 usage: $0 <function>
 EOT
-    exit 1
+  exit 1
 }
 
-help()
-{
-    usage
+help() {
+  usage
 }
 
 # number of args passed
@@ -46,12 +44,12 @@ args=$#
 # this allows this script to be sourced
 # to use its functions
 if [ $args -ge 1 ]; then
-    # executes given arguments
-    if is_function "$1"; then
-        "$@"
-    else
-        echo "failed to execute $*. Not found."
-        #usage
-        exit 127
-    fi
+  # executes given arguments
+  if is_function "$1"; then
+    "$@"
+  else
+    echo "failed to execute $*. Not found."
+    #usage
+    exit 127
+  fi
 fi
