systemtests: fail if daemons have config warnings
Fixes #131: Add automated check for configuration issues in systemtest
configurations

One can disable this behaviour for each systemtest individually by
setting the IGNORE_DAEMON_CONFIG_WARNINGS (CACHE INTERNAL) to true at
the beginning of the systemtests CMakeLists.txt file.

diff --git a/core/scripts/bareos-ctl-dir.in b/core/scripts/bareos-ctl-dir.in
--- a/core/scripts/bareos-ctl-dir.in
+++ b/core/scripts/bareos-ctl-dir.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # bareos-ctl-dir This shell script takes care of starting and stopping
 #		 the Bareos Director daemon
@@ -43,11 +43,17 @@ case "$1" in
                 OPTIONS="${OPTIONS} -c ${BAREOS_CONFIG_DIR}"
             fi
 
-            checkcfg
-            if [ $? != 0 ]; then
-                exit 1
+            log_file="${tmp}/bareos-dir-config-test.out"
+            "${BAREOS_DIRECTOR_BINARY}" -t $2 $3 ${OPTIONS} &> "$log_file"
+            if ! ${IGNORE_DAEMON_CONFIG_WARNINGS}; then
+                if grep -q "There are configuration warnings" "$log_file"; then
+                    echo "Fail: There are configuration warnings for the director when running ${BAREOS_DIRECTOR_BINARY} -t $2 $3 ${OPTIONS}, see below." >&2
+                    cat "$log_file"
+                    exit 7
+                fi
+            else
+                cat "$log_file"
             fi
-
             "${BAREOS_DIRECTOR_BINARY}" -v $2 $3 ${OPTIONS}
         fi
         ;;
diff --git a/core/scripts/bareos-ctl-fd.in b/core/scripts/bareos-ctl-fd.in
--- a/core/scripts/bareos-ctl-fd.in
+++ b/core/scripts/bareos-ctl-fd.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # bareos-ctl-fd  This shell script takes care of starting and stopping
 #		 the Bareos File daemon.
@@ -43,6 +43,17 @@ case "$1" in
                 OPTIONS="${OPTIONS} -c ${BAREOS_CONFIG_DIR}"
             fi
 
+            log_file="${tmp}/bareos-fd-config-test.out"
+            "${BAREOS_FILEDAEMON_BINARY}" -t $2 $3 ${OPTIONS} &> "$log_file"
+            if ! ${IGNORE_DAEMON_CONFIG_WARNINGS}; then
+                if grep -q "There are configuration warnings" "$log_file"; then
+                    echo "Fail: There are configuration warnings for the file-daemon when running ${BAREOS_FILEDAEMON_BINARY} -t $2 $3 ${OPTIONS}, see below." >&2
+                    cat "$log_file"
+                    exit 7
+                fi
+            else
+                cat "$log_file"
+            fi
             if [ "x${VALGRIND_FD}" = "x1" ]; then
                 valgrind --leak-check=full ${BAREOS_FILEDAEMON_BINARY} -v $2 $3 ${OPTIONS}
             else
diff --git a/core/scripts/bareos-ctl-sd.in b/core/scripts/bareos-ctl-sd.in
--- a/core/scripts/bareos-ctl-sd.in
+++ b/core/scripts/bareos-ctl-sd.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 #
 # bareos-ctl-sd  This shell script takes care of starting and stopping
 #		 the Bareos Storage daemon
@@ -42,6 +42,17 @@ case "$1" in
                 OPTIONS="${OPTIONS} -c ${BAREOS_CONFIG_DIR}"
             fi
 
+            log_file="${tmp}/bareos-sd-config-test.out"
+            "${BAREOS_STORAGEDAEMON_BINARY}" -t $2 $3 ${OPTIONS} &> "$log_file"
+            if ! ${IGNORE_DAEMON_CONFIG_WARNINGS}; then
+                if grep -q "There are configuration warnings" "$log_file"; then
+                    echo "Fail: There are configuration warnings for the storage-daemon when running ${BAREOS_STORAGEDAEMON_BINARY} -t $2 $3 ${OPTIONS}, see below." >&2
+                    cat "$log_file"
+                    exit 7
+                fi
+            else
+                cat "$log_file"
+            fi
             if [ "x${VALGRIND_SD}" = "x1" ]; then
                 valgrind --leak-check=full ${BAREOS_STORAGEDAEMON_BINARY} -v $2 $3 ${OPTIONS}
             else
