systemtests: cleanup daemon control scripts
* Fix behavior of "bareos-ctl-* status". Only check own process.
* "bareos-ctl-* stop": output status. Wait up to 2 seconds, until process is really terminated.
* "bareos-ctl-*":  reduce differences between the scripts.
* Cleanup.

diff --git a/core/scripts/bareos-ctl-funcs b/core/scripts/bareos-ctl-funcs
--- a/core/scripts/bareos-ctl-funcs
+++ b/core/scripts/bareos-ctl-funcs
@@ -40,9 +40,25 @@ pidofproc() {
    fi
 
    # Finally try to extract it from ps
-   pid=`${PSCMD} | grep $1 | ${AWK} '{ print $1 }' | tr '\n' ' '`
+   pid=`${PSCMD} | grep $base | ${AWK} '{ print $1 }' | tr '\n' ' '`
    echo $pid
    return 0
+}
+
+checkPid()
+{
+    pid="$1"
+    wait="${2:-0}"
+
+    if [ -z "$pid" ]; then
+        return 1
+    fi
+    while [ $wait -gt 0 ] && ${PS} -p "$pid" >/dev/null 2>&1; do
+        sleep 1
+        wait=$(expr $wait - 1)
+    done
+    ${PS} -p "$pid" >/dev/null 2>&1
+    return $?
 }
 
 # A function to stop a program.
@@ -70,36 +86,27 @@ killproc() {
    pid=`pidofproc $base $2`
 
    # Kill it.
-   if [ "$pid" != "" ] ; then
+   if checkPid "$pid"; then
       if [ "$notset" = "1" ] ; then
-         if ${PS} -p "$pid">/dev/null 2>&1; then
-            # TERM first, then KILL if not dead
-            kill -TERM $pid 2>/dev/null
-            #sleep 0.1
-            if ${PS} -p "$pid" >/dev/null 2>&1 ; then
-               #sleep 0.1
-               if ${PS} -p "$pid" >/dev/null 2>&1 ; then
-                 #sleep 0.3
-                  if ${PS} -p "$pid" >/dev/null 2>&1 ; then
-                     kill -KILL $pid 2>/dev/null
-                  fi
-               fi
-            fi
+         # TERM first, then KILL if not dead
+         kill -TERM $pid 2>/dev/null
+         if checkPid "$pid" 1; then
+            kill -KILL $pid 2>/dev/null
          fi
-         ${PS} -p "$pid" >/dev/null 2>&1
-         RC=$?
-         [ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
-         #    RC=$((! $RC))
-         # use specified level only
+         if checkPid "$pid" 1; then
+            failure
+         else
+            success
+         fi
       else
-         if ${PS} -p "$pid" >/dev/null 2>&1; then
-            kill $killlevel $pid 2>/dev/null
-            RC=$?
-            [ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
+         if kill $killlevel $pid 2>/dev/null; then
+            success "sent signal $killlevel"
+         else
+            failure
          fi
       fi
    else
-      failure "$base shutdown"
+      success "already stopped"
    fi
    # Remove pid file if any.
    if [ "$notset" = "1" ]; then
@@ -123,7 +130,6 @@ checkcfg() {
 }
 
 status() {
-   pid=""
    # Test syntax.
    if [ $# = 0 ] ; then
       echo "Usage: status {program} {port}"
@@ -133,40 +139,17 @@ status() {
    # Get base program name
    base=`basename $1`
 
-   # First try "pidof"
-   if [ ! -z "${PIDOF}" -a -x "${PIDOF}" ] ; then
-      pid=`${PIDOF} $1`
-      if [ "$pid" != "" ] ; then
-         echo "$base (pid $pid) is running..."
-         return 0
-      fi
+   # Find pid.
+   pid=`pidofproc $base $2`
+
+   if checkPid "$pid"; then
+       echo "$base (pid $pid) is running..."
+       return 0
    fi
 
-   # Next try "pgrep"
-   if [ ! -z "${PGREP}" -a -x "${PGREP}" ] ; then
-      pid=`${PGREP} -f $base`
-      if [ "$pid" != "" ] ; then
-         echo "$base (pid $pid) is running..."
-         return 0
-      fi
-   fi
-
-   pid=`${PSCMD} | ${AWK} 'BEGIN { prog=ARGV[1]; ARGC=1 } \
-   { if ((prog == $2) || (("(" prog ")") == $2) ||        \
-      (("[" prog "]") == $2) ||                           \
-      ((prog ":") == $2)) { print $1 ; exit 0 } }' $1`
-   if [ "$pid" != "" ] ; then
-      echo "$base (pid $pid) is running..."
-      return 0
-   fi
-
-   # Next try the PID files
    if [ -f ${PIDDIR}/$base.$2.pid ] ; then
-      pid=`head -n 1 ${PIDDIR}/$base.$2.pid`
-      if [ "$pid" != "" ] ; then
-         echo "$base dead but pid file exists"
-         return 1
-      fi
+       echo "$base dead but pid file exists"
+       return 1
    fi
 
    # See if the subsys lock exists
@@ -174,16 +157,23 @@ status() {
       echo "$base dead but subsys locked"
       return 2
    fi
+
    echo "$base is stopped"
 
    return 3
 }
 
 success() {
+   MESSAGE="OK"
+   if [ "$1" ]; then
+     MESSAGE="OK ($1)"
+   fi
+   echo $MESSAGE
    return 0
 }
 
 failure() {
    rc=$?
+   echo "failed (rc=$rc)"
    return $rc
 }
