Improve documentation and helper scripts
- doc: better formulate capabilities introduction and systemd part
  Reorder helper set/unset/check presentation
- helper: reorder actions to chgrp, chmod, setcap

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>
(cherry picked from commit 45e22d0079ea8ba05ea36f9ea8621ae07022ffa3)

diff --git a/core/scripts/bareos-config-lib.sh.in b/core/scripts/bareos-config-lib.sh.in
--- a/core/scripts/bareos-config-lib.sh.in
+++ b/core/scripts/bareos-config-lib.sh.in
@@ -272,14 +272,18 @@ set_scsicrypto_capabilities()
       return 1
   fi
   for c in ${_scsicrypto_cmds};do
+    # Need to affect the bareos group (debian)
+    if ! r="$(chgrp "${STORAGE_DAEMON_GROUP}" "${BAREOS_SBIN_DIR}/${c}")"; then
+        error "Setting group to ${STORAGE_DAEMON_GROUP} failed on ${c}"
+        return 1
+    fi
+    if ! r="$(chmod o-rwx "${BAREOS_SBIN_DIR}/${c}")"; then
+        error "Setting chmod o-rwx failed on ${c}"
+        return 1
+    fi
     if ! r="$(setcap cap_sys_rawio=ep "${BAREOS_SBIN_DIR}/${c}")"; then
        error "setcap on ${c} has failed - ${r}"
        return 1
-    else
-      if ! r="$(chmod 0750 "${BAREOS_SBIN_DIR}/${c}")"; then
-         error "Adjusting chmod failed on ${c}"
-         return 1
-      fi
     fi
   done
   echo "cap_sys_rawio+ep capabilities enabled" > "${_scsicrypto_config_file}"
@@ -295,11 +299,14 @@ unset_scsicrypto_capabilities()
     if ! r="$(setcap -r "${BAREOS_SBIN_DIR}/${c}")"; then
        error "setcap -r on ${c} has failed - ${r}"
        return 1
-    else
-      if ! r="$(chmod 0755 "${BAREOS_SBIN_DIR}/${c}")"; then
-         error "Ajusting chmod failed on ${c}"
-         return 1
-      fi
+    fi
+    if ! r="$(chmod o+rx "${BAREOS_SBIN_DIR}/${c}")"; then
+        error "Restoring chmod o+rx failed on ${c}"
+        return 1
+    fi
+    if ! r="$(chgrp root "${BAREOS_SBIN_DIR}/${c}")"; then
+        error "Restoring group to root failed on ${c}"
+        return 1
     fi
   done
   rm -f "${_scsicrypto_config_file}"
