refactor: apply shell format to core/scripts
also changed their indentation to 2 spaces.

diff --git a/core/scripts/bareos-ctl-funcs b/core/scripts/bareos-ctl-funcs
--- a/core/scripts/bareos-ctl-funcs
+++ b/core/scripts/bareos-ctl-funcs
@@ -2,188 +2,187 @@
 
 # A function to find the pid of a program.
 pidofproc() {
-   pid=""
-   # Test syntax.
-   if [ $# = 0 ] ; then
-      echo "Usage: pidofproc {program} {port}"
-      return 1
-   fi
+  pid=""
+  # Test syntax.
+  if [ $# = 0 ]; then
+    echo "Usage: pidofproc {program} {port}"
+    return 1
+  fi
 
-   # Get base program name
-   base=`basename $1`
+  # Get base program name
+  base=$(basename $1)
 
-   # First try "pidof"
-   if [ ! -z "${PIDOF}" -a -x "${PIDOF}" ] ; then
-      pid=`${PIDOF} $1`
-      if [ "$pid" != "" ] ; then
-         echo $pid
-         return 0
-      fi
-   fi
+  # First try "pidof"
+  if [ ! -z "${PIDOF}" -a -x "${PIDOF}" ]; then
+    pid=$(${PIDOF} $1)
+    if [ "$pid" != "" ]; then
+      echo $pid
+      return 0
+    fi
+  fi
 
-   # Next try "pgrep"
-   if [ ! -z "${PGREP}" -a -x "${PGREP}" ] ; then
-      pid=`${PGREP} -f $base`
-      if [ "$pid" != "" ] ; then
-         echo $pid | cut -d' ' -f 1
-         return 0
-      fi
-   fi
+  # Next try "pgrep"
+  if [ ! -z "${PGREP}" -a -x "${PGREP}" ]; then
+    pid=$(${PGREP} -f $base)
+    if [ "$pid" != "" ]; then
+      echo $pid | cut -d' ' -f 1
+      return 0
+    fi
+  fi
 
-   # Finally try to extract it from ps
-   pid=$(ps | grep ${base} | awk '{print $1}' | head -n1)
-   echo $pid
-   return 0
+  # Finally try to extract it from ps
+  pid=$(ps | grep ${base} | awk '{print $1}' | head -n1)
+  echo $pid
+  return 0
 }
 
-checkPid()
-{
-    pid="$1"
-    wait="${2:-0}"
-    waittext="${3:-}"
-    output=""
+checkPid() {
+  pid="$1"
+  wait="${2:-0}"
+  waittext="${3:-}"
+  output=""
 
-    if [ -z "$pid" ]; then
-        return 1
+  if [ -z "$pid" ]; then
+    return 1
+  fi
+
+  start=$(date +%s)
+  end=$(expr $start + $wait)
+
+  while [ "$(date +%s)" -lt "$end" ] && ${PS} -p "$pid" >/dev/null 2>&1; do
+    if [ "${waittext}" ]; then
+      printf "%s" "$waittext"
+      output="yes"
     fi
-
-    start=$(date +%s)
-    end=$(expr $start + $wait)
-
-    while [ "$(date +%s)" -lt "$end" ] && ${PS} -p "$pid" >/dev/null 2>&1; do
-        if [ "${waittext}" ]; then
-            printf "%s" "$waittext"
-            output="yes"
-        fi
-        # not all systems offer floating point numbers as sleep parameter, therefore try both.
-        sleep 0.1 || sleep 1
-    done
-    if [ "${output}" ]; then printf " "; fi
-    ${PS} -p "$pid" >/dev/null 2>&1
-    return $?
+    # not all systems offer floating point numbers as sleep parameter, therefore try both.
+    sleep 0.1 || sleep 1
+  done
+  if [ "${output}" ]; then printf " "; fi
+  ${PS} -p "$pid" >/dev/null 2>&1
+  return $?
 }
 
 # A function to stop a program.
 killproc() {
-   RC=0
-   # Test syntax.
-   if [ $# = 0 ]; then
-      echo "Usage: killproc {program} {port} [signal]"
-      return 1
-   fi
+  RC=0
+  # Test syntax.
+  if [ $# = 0 ]; then
+    echo "Usage: killproc {program} {port} [signal]"
+    return 1
+  fi
 
-   notset=0
-   # check for third arg to be kill level
-   if [ "$3" != "" ] ; then
-      killlevel=$3
-   else
-      notset=1
-      killlevel="-9"
-   fi
+  notset=0
+  # check for third arg to be kill level
+  if [ "$3" != "" ]; then
+    killlevel=$3
+  else
+    notset=1
+    killlevel="-9"
+  fi
 
-   # Get base program name
-   base=`basename $1`
+  # Get base program name
+  base=$(basename $1)
 
-   # Find pid.
-   pid=`pidofproc $base $2`
+  # Find pid.
+  pid=$(pidofproc $base $2)
 
-   # Kill it.
-   if checkPid "$pid"; then
-      if [ "$notset" = "1" ] ; then
-         # TERM first, then KILL if not dead
-         kill -TERM $pid 2>/dev/null
-         if checkPid "$pid" 3 "."; then
-            kill -KILL $pid 2>/dev/null
-         fi
-         if checkPid "$pid" 3 "_"; then
-            failure
-         else
-            success
-         fi
-      else
-         if kill $killlevel $pid 2>/dev/null; then
-            success "sent signal $killlevel"
-         else
-            failure
-         fi
+  # Kill it.
+  if checkPid "$pid"; then
+    if [ "$notset" = "1" ]; then
+      # TERM first, then KILL if not dead
+      kill -TERM $pid 2>/dev/null
+      if checkPid "$pid" 3 "."; then
+        kill -KILL $pid 2>/dev/null
       fi
-   else
-      success "already stopped"
-   fi
-   return $RC
+      if checkPid "$pid" 3 "_"; then
+        failure
+      else
+        success
+      fi
+    else
+      if kill $killlevel $pid 2>/dev/null; then
+        success "sent signal $killlevel"
+      else
+        failure
+      fi
+    fi
+  else
+    success "already stopped"
+  fi
+  return $RC
 }
 
 # Checks if the Database can be connected to
 check_database() {
-   echo "Checking Database connection for $1"
-   log_file="${tmp}/bareos-$1-config-test.out"
-   "$2" -f -t "${@:3}" &> "$log_file"
-   
-   if grep -q "Could not open Catalog" "$log_file"; then
-      echo "Fail: Could not connect to the Catalog when running $2 -t ${*:3}, see below." >&2
-      cat "$log_file"
-      return 2
-   fi
-   return 0
+  echo "Checking Database connection for $1"
+  log_file="${tmp}/bareos-$1-config-test.out"
+  "$2" -f -t "${@:3}" &>"$log_file"
+
+  if grep -q "Could not open Catalog" "$log_file"; then
+    echo "Fail: Could not connect to the Catalog when running $2 -t ${*:3}, see below." >&2
+    cat "$log_file"
+    return 2
+  fi
+  return 0
 }
 # Checks if the configuration outputs warnings
 check_config() {
-   echo "Checking Configuration for $1"
-   log_file="${tmp}/bareos-$1-config-test.out"
-   "$2" -t "${@:3}" &> "$log_file"
+  echo "Checking Configuration for $1"
+  log_file="${tmp}/bareos-$1-config-test.out"
+  "$2" -t "${@:3}" &>"$log_file"
 
-   if ! ${IGNORE_CONFIG_WARNINGS}; then
-      if grep -q "There are configuration warnings" "$log_file"; then
-         echo "Fail: There are configuration warnings when running $2 -t ${*:3}, see below." >&2
-         cat "$log_file"
-         return 7
-      fi
-   else
+  if ! ${IGNORE_CONFIG_WARNINGS}; then
+    if grep -q "There are configuration warnings" "$log_file"; then
+      echo "Fail: There are configuration warnings when running $2 -t ${*:3}, see below." >&2
       cat "$log_file"
-   fi
-   return 0
+      return 7
+    fi
+  else
+    cat "$log_file"
+  fi
+  return 0
 }
 
 status() {
-   # Test syntax.
-   if [ $# = 0 ] ; then
-      echo "Usage: status {program} {port}"
-      return 1
-   fi
+  # Test syntax.
+  if [ $# = 0 ]; then
+    echo "Usage: status {program} {port}"
+    return 1
+  fi
 
-   # Get base program name
-   base=`basename $1`
+  # Get base program name
+  base=$(basename $1)
 
-   # Find pid.
-   pid=`pidofproc $base $2`
+  # Find pid.
+  pid=$(pidofproc $base $2)
 
-   if checkPid "$pid"; then
-       echo "$base (pid $pid) is running..."
-       return 0
-   fi
+  if checkPid "$pid"; then
+    echo "$base (pid $pid) is running..."
+    return 0
+  fi
 
-   # See if the subsys lock exists
-   if [ -f ${SUBSYSDIR}/$base ] ; then
-      echo "$base dead but subsys locked"
-      return 2
-   fi
+  # See if the subsys lock exists
+  if [ -f ${SUBSYSDIR}/$base ]; then
+    echo "$base dead but subsys locked"
+    return 2
+  fi
 
-   echo "$base is stopped"
+  echo "$base is stopped"
 
-   return 3
+  return 3
 }
 
 success() {
-   MESSAGE="OK"
-   if [ "$1" ]; then
-     MESSAGE="OK ($1)"
-   fi
-   echo $MESSAGE
-   return 0
+  MESSAGE="OK"
+  if [ "$1" ]; then
+    MESSAGE="OK ($1)"
+  fi
+  echo $MESSAGE
+  return 0
 }
 
 failure() {
-   rc=$?
-   echo "failed (rc=$rc)"
-   return $rc
+  rc=$?
+  echo "failed (rc=$rc)"
+  return $rc
 }
diff --git a/core/scripts/bareos-glusterfind-wrapper.in b/core/scripts/bareos-glusterfind-wrapper.in
--- a/core/scripts/bareos-glusterfind-wrapper.in
+++ b/core/scripts/bareos-glusterfind-wrapper.in
@@ -32,100 +32,94 @@ BACKUP_LEVEL="Full"
 SINCE_TIME="0"
 JOB_TYPE="Backup"
 
-usage()
-{
-   echo "Usage: $0 [-h] [-l <level>] [-s <since_time>] [-t <jobtype>] <action> <arguments...>"
+usage() {
+  echo "Usage: $0 [-h] [-l <level>] [-s <since_time>] [-t <jobtype>] <action> <arguments...>"
 }
 
-pre_backup()
-{
-   if [ $# -lt 2 ]; then
-      echo "pre_backup action needs 2 arguments"
-      exit 1
-   fi
+pre_backup() {
+  if [ $# -lt 2 ]; then
+    echo "pre_backup action needs 2 arguments"
+    exit 1
+  fi
 
-   #
-   # $1 - volumename
-   # $2 - outputfile
-   #
-   case ${BACKUP_LEVEL} in
-      Full)
-         ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME} --full
-         ;;
-      Incremental|Differential)
-         ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME}
-         ;;
-      *)
-         ;;
-   esac
+  #
+  # $1 - volumename
+  # $2 - outputfile
+  #
+  case ${BACKUP_LEVEL} in
+  Full)
+    ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME} --full
+    ;;
+  Incremental | Differential)
+    ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME}
+    ;;
+  *) ;;
+  esac
 }
 
-post_backup()
-{
-   if [ $# -lt 2 ]; then
-      echo "post_backup action needs 2 arguments"
-      exit 1
-   fi
+post_backup() {
+  if [ $# -lt 2 ]; then
+    echo "post_backup action needs 2 arguments"
+    exit 1
+  fi
 
-   #
-   # $1 - volumename
-   # $2 - outputfile
-   #
-   rm -f $2
+  #
+  # $1 - volumename
+  # $2 - outputfile
+  #
+  rm -f $2
 }
 
-main()
-{
-   #
-   # Parse options.
-   #
-   while getopts "hl:s:t:" arg
-   do
-      case ${arg} in
-         h|\?)
-            usage
-            exit 0
-            ;;
-         l)
-            BACKUP_LEVEL="${OPTARG}"
-            ;;
-         s)
-            SINCE_TIME="${OPTARG}"
-            ;;
-         t)
-            JOB_TYPE="${OPTARG}"
-            ;;
-         *)
-            usage
-            exit 1
-            ;;
-      esac
-   done
-   nr_shift=`expr $OPTIND - 1`
-   shift ${nr_shift}
-
-   if [ $# -lt 1 ]; then
+main() {
+  #
+  # Parse options.
+  #
+  while getopts "hl:s:t:" arg; do
+    case ${arg} in
+    h | \?)
+      usage
+      exit 0
+      ;;
+    l)
+      BACKUP_LEVEL="${OPTARG}"
+      ;;
+    s)
+      SINCE_TIME="${OPTARG}"
+      ;;
+    t)
+      JOB_TYPE="${OPTARG}"
+      ;;
+    *)
       usage
       exit 1
-   fi
+      ;;
+    esac
+  done
+  nr_shift=$(expr $OPTIND - 1)
+  shift ${nr_shift}
 
-   action=$1
-   shift
+  if [ $# -lt 1 ]; then
+    usage
+    exit 1
+  fi
 
-   case ${action} in
-      prebackup)
-         pre_backup $*
-         ;;
-      postbackup)
-         post_backup $*
-         ;;
-      *)
-         echo "Unknown action ${action}, aborting ..."
-         exit 1
-         ;;
-   esac
+  action=$1
+  shift
 
-   exit 0
+  case ${action} in
+  prebackup)
+    pre_backup $*
+    ;;
+  postbackup)
+    post_backup $*
+    ;;
+  *)
+    echo "Unknown action ${action}, aborting ..."
+    exit 1
+    ;;
+  esac
+
+  exit 0
 }
 
 main $*
diff --git a/core/scripts/disk-changer.in b/core/scripts/disk-changer.in
--- a/core/scripts/disk-changer.in
+++ b/core/scripts/disk-changer.in
@@ -85,41 +85,40 @@ wd=@working_dir@
 #
 dbgfile="$wd/disk-changer.log"
 debug() {
-    if test -f $dbgfile; then
-        echo "`date +\"%Y%m%d-%H:%M:%S\"` $*" >> $dbgfile
-    fi
+  if test -f $dbgfile; then
+    echo "$(date +\"%Y%m%d-%H:%M:%S\") $*" >>$dbgfile
+  fi
 }
-
 
 #
 # Create a temporary file
 #
 make_temp_file() {
-  TMPFILE=`mktemp -t mtx.XXXXXXXXXX`
+  TMPFILE=$(mktemp -t mtx.XXXXXXXXXX)
   if test x${TMPFILE} = x; then
-     TMPFILE="$wd/disk-changer.$$"
-     if test -f ${TMPFILE}; then
-        echo "Temp file security problem on: ${TMPFILE}"
-        exit 1
-     fi
+    TMPFILE="$wd/disk-changer.$$"
+    if test -f ${TMPFILE}; then
+      echo "Temp file security problem on: ${TMPFILE}"
+      exit 1
+    fi
   fi
 }
 
 # check parameter count on commandline
 #
 check_parm_count() {
-    pCount=$1
-    pCountNeed=$2
-    if test $pCount -lt $pCountNeed; then
-        echo "usage: disk-changer ctl-device command [slot archive-device drive-index]"
-        echo "  Insufficient number of arguments arguments given."
-        if test $pCount -lt 2; then
-            echo "  Mimimum usage is first two arguments ..."
-        else
-            echo "  Command expected $pCountNeed arguments"
-        fi
-        exit 1
+  pCount=$1
+  pCountNeed=$2
+  if test $pCount -lt $pCountNeed; then
+    echo "usage: disk-changer ctl-device command [slot archive-device drive-index]"
+    echo "  Insufficient number of arguments arguments given."
+    if test $pCount -lt 2; then
+      echo "  Mimimum usage is first two arguments ..."
+    else
+      echo "  Command expected $pCountNeed arguments"
     fi
+    exit 1
+  fi
 }
 
 #
@@ -127,13 +126,13 @@ check_parm_count() {
 #  that we are dealing with.
 #
 get_dir() {
-   bn=`basename $device`
-   dir=`echo "$device" | sed -e s%/$bn%%g`
-   if [ ! -d $dir ]; then
-      echo "ERROR: Autochanger directory \"$dir\" does not exist."
-      echo "       You must create it."
-      exit 1
-   fi
+  bn=$(basename $device)
+  dir=$(echo "$device" | sed -e s%/$bn%%g)
+  if [ ! -d $dir ]; then
+    echo "ERROR: Autochanger directory \"$dir\" does not exist."
+    echo "       You must create it."
+    exit 1
+  fi
 }
 
 #
@@ -141,19 +140,18 @@ get_dir() {
 #  the volslotn information.
 #
 get_vol() {
-   havevol=0
-   debug "vol=$volume"
-   if test "x$volume" != x && test "x$volume" != "x*NONE*" ; then
-      debug "touching $dir/$volume"
-      touch $dir/$volume
-      echo "$volume" >$dir/volslot${slot}
-      havevol=1
-   elif [ -f $dir/volslot${slot} ]; then
-      volume=`cat $dir/volslot${slot}`
-      havevol=1
-   fi
+  havevol=0
+  debug "vol=$volume"
+  if test "x$volume" != x && test "x$volume" != "x*NONE*"; then
+    debug "touching $dir/$volume"
+    touch $dir/$volume
+    echo "$volume" >$dir/volslot${slot}
+    havevol=1
+  elif [ -f $dir/volslot${slot} ]; then
+    volume=$(cat $dir/volslot${slot})
+    havevol=1
+  fi
 }
-
 
 # Setup arguments
 ctl=$1
@@ -169,162 +167,160 @@ maxslot=10
 
 # Pull in conf file
 if [ -f $ctl ]; then
-   . $ctl
+  . $ctl
 fi
-
 
 # Check for special cases where only 2 arguments are needed,
 #  all others are a minimum of 5
 #
 case $2 in
-    list|listall)
-        check_parm_count $# 2
-        ;;
-    slots)
-        check_parm_count $# 2
-        ;;
-    transfer)
-        check_parm_count $# 4
-        if [ $slot -gt $maxslot ]; then
-           echo "Slot ($slot) out of range (1-$maxslot)"
-           exit 1
-        fi
-        ;;
-    *)
-        check_parm_count $# 5
-        if [ $drive -gt $maxdrive ]; then
-           echo "Drive ($drive) out of range (0-$maxdrive)"
-           exit 1
-        fi
-        if [ $slot -gt $maxslot ]; then
-           echo "Slot ($slot) out of range (1-$maxslot)"
-           exit 1
-        fi
-        ;;
+list | listall)
+  check_parm_count $# 2
+  ;;
+slots)
+  check_parm_count $# 2
+  ;;
+transfer)
+  check_parm_count $# 4
+  if [ $slot -gt $maxslot ]; then
+    echo "Slot ($slot) out of range (1-$maxslot)"
+    exit 1
+  fi
+  ;;
+*)
+  check_parm_count $# 5
+  if [ $drive -gt $maxdrive ]; then
+    echo "Drive ($drive) out of range (0-$maxdrive)"
+    exit 1
+  fi
+  if [ $slot -gt $maxslot ]; then
+    echo "Slot ($slot) out of range (1-$maxslot)"
+    exit 1
+  fi
+  ;;
 esac
-
 
 debug "Parms: $ctl $cmd $slot $device $drive $volume $havevol"
 
 case $cmd in
-   unload)
-      debug "Doing disk -f $ctl unload $slot $device $drive $volume"
-      get_dir
-      if [ -f $dir/loaded${drive} ]; then
-         ld=`cat $dir/loaded${drive}`
-      else
-         echo "Storage Element $slot is Already Full"
-         exit 1
-      fi
-      if [ $slot -eq $ld ]; then
-         echo "0" >$dir/loaded${drive}
-         unlink $device 2>/dev/null >/dev/null
-         rm -f $device
-      else
-         echo "Storage Element $slot is Already Full"
-         exit 1
-      fi
-      ;;
+unload)
+  debug "Doing disk -f $ctl unload $slot $device $drive $volume"
+  get_dir
+  if [ -f $dir/loaded${drive} ]; then
+    ld=$(cat $dir/loaded${drive})
+  else
+    echo "Storage Element $slot is Already Full"
+    exit 1
+  fi
+  if [ $slot -eq $ld ]; then
+    echo "0" >$dir/loaded${drive}
+    unlink $device 2>/dev/null >/dev/null
+    rm -f $device
+  else
+    echo "Storage Element $slot is Already Full"
+    exit 1
+  fi
+  ;;
 
-   load)
-      debug "Doing disk $ctl load $slot $device $drive $volume"
-      get_dir
-      i=0
-      while [ $i -le $maxdrive ]; do
-         if [ -f $dir/loaded${i} ]; then
-            ld=`cat $dir/loaded${i}`
-         else
-            ld=0
-         fi
-         if [ $ld -eq $slot ]; then
-            echo "Drive ${i} Full (Storage element ${ld} loaded)"
-            exit 1
-         fi
-         i=`expr $i + 1`
-      done
-      # Check if we have a Volume name
+load)
+  debug "Doing disk $ctl load $slot $device $drive $volume"
+  get_dir
+  i=0
+  while [ $i -le $maxdrive ]; do
+    if [ -f $dir/loaded${i} ]; then
+      ld=$(cat $dir/loaded${i})
+    else
+      ld=0
+    fi
+    if [ $ld -eq $slot ]; then
+      echo "Drive ${i} Full (Storage element ${ld} loaded)"
+      exit 1
+    fi
+    i=$(expr $i + 1)
+  done
+  # Check if we have a Volume name
+  get_vol
+  if [ $havevol -eq 0 ]; then
+    # check if slot exists
+    if [ ! -f $dir/slot${slot} ]; then
+      echo "source Element Address $slot is Empty"
+      exit 1
+    fi
+  fi
+  if [ -f $dir/loaded${drive} ]; then
+    ld=$(cat $dir/loaded${drive})
+  else
+    ld=0
+  fi
+  if [ $ld -ne 0 ]; then
+    echo "Drive ${drive} Full (Storage element ${ld} loaded)"
+    exit 1
+  fi
+  echo "0" >$dir/loaded${drive}
+  unlink $device 2>/dev/null >/dev/null
+  rm -f $device
+  if [ $havevol -ne 0 ]; then
+    ln -s $dir/$volume $device
+    rtn=$?
+  else
+    ln -s $dir/slot${slot} $device
+    rtn=$?
+  fi
+  if [ $rtn -eq 0 ]; then
+    echo $slot >$dir/loaded${drive}
+  fi
+  exit $rtn
+  ;;
+
+list)
+  debug "Doing disk -f $ctl -- to list volumes"
+  get_dir
+  if [ -f $dir/barcodes ]; then
+    cat $dir/barcodes
+  else
+    i=1
+    while [ $i -le $maxslot ]; do
+      slot=$i
+      volume=
       get_vol
       if [ $havevol -eq 0 ]; then
-         # check if slot exists
-         if [ ! -f $dir/slot${slot} ] ; then
-            echo "source Element Address $slot is Empty"
-            exit 1
-         fi
-      fi
-      if [ -f $dir/loaded${drive} ]; then
-         ld=`cat $dir/loaded${drive}`
+        echo "$i:"
       else
-         ld=0
+        echo "$i:$volume"
       fi
-      if [ $ld -ne 0 ]; then
-         echo "Drive ${drive} Full (Storage element ${ld} loaded)"
-         exit 1
-      fi
-      echo "0" >$dir/loaded${drive}
-      unlink $device 2>/dev/null >/dev/null
-      rm -f $device
-      if [ $havevol -ne 0 ]; then
-         ln -s $dir/$volume $device
-         rtn=$?
-      else
-         ln -s $dir/slot${slot} $device
-         rtn=$?
-      fi
-      if [ $rtn -eq 0 ]; then
-         echo $slot >$dir/loaded${drive}
-      fi
-      exit $rtn
-      ;;
+      i=$(expr $i + 1)
+    done
+  fi
+  exit 0
+  ;;
 
-   list)
-      debug "Doing disk -f $ctl -- to list volumes"
-      get_dir
-      if [ -f $dir/barcodes ]; then
-         cat $dir/barcodes
-      else
-         i=1
-         while [ $i -le $maxslot ]; do
-            slot=$i
-            volume=
-            get_vol
-            if [ $havevol -eq 0 ]; then
-               echo "$i:"
-            else
-               echo "$i:$volume"
-            fi
-            i=`expr $i + 1`
-         done
-      fi
-      exit 0
-      ;;
+listall)
+  # ***FIXME*** must add new Volume stuff
+  make_temp_file
+  debug "Doing disk -f $ctl -- to list volumes"
+  get_dir
+  if [ ! -f $dir/barcodes ]; then
+    exit 0
+  fi
 
-   listall)
-      # ***FIXME*** must add new Volume stuff
-      make_temp_file
-      debug "Doing disk -f $ctl -- to list volumes"
-      get_dir
-      if [ ! -f $dir/barcodes ]; then
-          exit 0
-      fi
+  # we print drive content seen by autochanger
+  # and we also remove loaded media from the barcode list
+  i=0
+  while [ $i -le $maxdrive ]; do
+    if [ -f $dir/loaded${i} ]; then
+      ld=$(cat $dir/loaded${i})
+      v=$(awk -F: "/^$ld:/"' { print $2 }' $dir/barcodes)
+      echo "D:$i:F:$ld:$v"
+      echo "^$ld:" >>$TMPFILE
+    fi
+    i=$(expr $i + 1)
+  done
 
-      # we print drive content seen by autochanger
-      # and we also remove loaded media from the barcode list
-      i=0
-      while [ $i -le $maxdrive ]; do
-         if [ -f $dir/loaded${i} ]; then
-             ld=`cat $dir/loaded${i}`
-             v=`awk -F: "/^$ld:/"' { print $2 }' $dir/barcodes`
-             echo "D:$i:F:$ld:$v"
-             echo "^$ld:" >> $TMPFILE
-         fi
-         i=`expr $i + 1`
-      done
-
-      # Empty slots are not in barcodes file
-      # When we detect a gap, we print missing rows as empty
-      # At the end, we fill the gap between the last entry and maxslot
-      grep -v -f $TMPFILE $dir/barcodes | sort -n | \
-      perl -ne 'BEGIN { $cur=1 }
+  # Empty slots are not in barcodes file
+  # When we detect a gap, we print missing rows as empty
+  # At the end, we fill the gap between the last entry and maxslot
+  grep -v -f $TMPFILE $dir/barcodes | sort -n |
+    perl -ne 'BEGIN { $cur=1 }
        if (/(\d+):(.+)?/) {
          if ($cur == $1) {
            print "S:$1:F:$2\n"
@@ -338,45 +334,45 @@ case $cmd in
        }
        END { while ($cur < '"$maxslot"') { print "S:$cur:E\n"; $cur++; } } '
 
-      rm -f $TMPFILE
-      exit 0
-      ;;
-   transfer)
-      #  ***FIXME*** must add new Volume stuff
-      get_dir
-      make_temp_file
-      slotdest=$device
-      if [ -f $dir/slot{$slotdest} ]; then
-         echo "destination Element Address $slot is Full"
-         exit 1
-      fi
-      if [ ! -f $dir/slot${slot} ] ; then
-         echo "source Element Address $slot is Empty"
-         exit 1
-      fi
+  rm -f $TMPFILE
+  exit 0
+  ;;
+transfer)
+  #  ***FIXME*** must add new Volume stuff
+  get_dir
+  make_temp_file
+  slotdest=$device
+  if [ -f $dir/slot{$slotdest} ]; then
+    echo "destination Element Address $slot is Full"
+    exit 1
+  fi
+  if [ ! -f $dir/slot${slot} ]; then
+    echo "source Element Address $slot is Empty"
+    exit 1
+  fi
 
-      echo "Transfering $slot to $slotdest"
-      mv $dir/slot${slot} $dir/slot{$slotdest}
+  echo "Transfering $slot to $slotdest"
+  mv $dir/slot${slot} $dir/slot{$slotdest}
 
-      if [ -f $dir/barcodes ]; then
-         sed "s/^$slot:/$slotdest:/" >  $TMPFILE
-         sort -n $TMPFILE > $dir/barcodes
-      fi
-      exit 0
-      ;;
-   loaded)
-      debug "Doing disk -f $ctl $drive -- to find what is loaded"
-      get_dir
-      if [ -f $dir/loaded${drive} ]; then
-         cat $dir/loaded${drive}
-      else
-         echo "0"
-      fi
-      exit
-      ;;
+  if [ -f $dir/barcodes ]; then
+    sed "s/^$slot:/$slotdest:/" >$TMPFILE
+    sort -n $TMPFILE >$dir/barcodes
+  fi
+  exit 0
+  ;;
+loaded)
+  debug "Doing disk -f $ctl $drive -- to find what is loaded"
+  get_dir
+  if [ -f $dir/loaded${drive} ]; then
+    cat $dir/loaded${drive}
+  else
+    echo "0"
+  fi
+  exit
+  ;;
 
-   slots)
-      debug "Doing disk -f $ctl -- to get count of slots"
-      echo $maxslot
-      ;;
+slots)
+  debug "Doing disk -f $ctl -- to get count of slots"
+  echo $maxslot
+  ;;
 esac
