refactor: shfmt core/scripts, systemtests/scripts
using the flags
"--indent 2 --binary-next-line --case-indent --func-next-line" as in
issue #321

diff --git a/core/scripts/bareos-glusterfind-wrapper.in b/core/scripts/bareos-glusterfind-wrapper.in
--- a/core/scripts/bareos-glusterfind-wrapper.in
+++ b/core/scripts/bareos-glusterfind-wrapper.in
@@ -3,7 +3,7 @@
 # BAREOS® - Backup Archiving REcovery Open Sourced
 #
 # Copyright (C) 2015-2016 Planets Communications B.V.
-# Copyright (C) 2015-2016 Bareos GmbH & Co. KG
+# Copyright (C) 2015-2025 Bareos GmbH & Co. KG
 #
 # This program is Free Software; you can redistribute it and/or
 # modify it under the terms of version three of the GNU Affero General Public
@@ -32,11 +32,13 @@ BACKUP_LEVEL="Full"
 SINCE_TIME="0"
 JOB_TYPE="Backup"
 
-usage() {
+usage()
+{
   echo "Usage: $0 [-h] [-l <level>] [-s <since_time>] [-t <jobtype>] <action> <arguments...>"
 }
 
-pre_backup() {
+pre_backup()
+{
   if [ $# -lt 2 ]; then
     echo "pre_backup action needs 2 arguments"
     exit 1
@@ -47,17 +49,18 @@ pre_backup() {
   # $2 - outputfile
   #
   case ${BACKUP_LEVEL} in
-  Full)
-    ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME} --full
-    ;;
-  Incremental | Differential)
-    ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME}
-    ;;
-  *) ;;
+    Full)
+      ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME} --full
+      ;;
+    Incremental | Differential)
+      ${GLUSTERFIND} query $1 $2 --since-time ${SINCE_TIME}
+      ;;
+    *) ;;
   esac
 }
 
-post_backup() {
+post_backup()
+{
   if [ $# -lt 2 ]; then
     echo "post_backup action needs 2 arguments"
     exit 1
@@ -70,29 +73,30 @@ post_backup() {
   rm -f $2
 }
 
-main() {
+main()
+{
   #
   # Parse options.
   #
   while getopts "hl:s:t:" arg; do
     case ${arg} in
-    h | \?)
-      usage
-      exit 0
-      ;;
-    l)
-      BACKUP_LEVEL="${OPTARG}"
-      ;;
-    s)
-      SINCE_TIME="${OPTARG}"
-      ;;
-    t)
-      JOB_TYPE="${OPTARG}"
-      ;;
-    *)
-      usage
-      exit 1
-      ;;
+      h | \?)
+        usage
+        exit 0
+        ;;
+      l)
+        BACKUP_LEVEL="${OPTARG}"
+        ;;
+      s)
+        SINCE_TIME="${OPTARG}"
+        ;;
+      t)
+        JOB_TYPE="${OPTARG}"
+        ;;
+      *)
+        usage
+        exit 1
+        ;;
     esac
   done
   nr_shift=$(expr $OPTIND - 1)
@@ -107,16 +111,16 @@ main() {
   shift
 
   case ${action} in
-  prebackup)
-    pre_backup $*
-    ;;
-  postbackup)
-    post_backup $*
-    ;;
-  *)
-    echo "Unknown action ${action}, aborting ..."
-    exit 1
-    ;;
+    prebackup)
+      pre_backup $*
+      ;;
+    postbackup)
+      post_backup $*
+      ;;
+    *)
+      echo "Unknown action ${action}, aborting ..."
+      exit 1
+      ;;
   esac
 
   exit 0
diff --git a/systemtests/scripts/check_for_zombie_jobs b/systemtests/scripts/check_for_zombie_jobs
--- a/systemtests/scripts/check_for_zombie_jobs
+++ b/systemtests/scripts/check_for_zombie_jobs
@@ -12,10 +12,10 @@
 
 # check_for_zombie_jobs storage=STORAGE [client=localhost-fd]
 
-if [ $# = 2 ] ; then
-    client="$2"
+if [ $# = 2 ]; then
+  client="$2"
 else
-    client="client"
+  client="client"
 fi
 
 wait_for_jobs_to_terminate "${client}" 20
@@ -32,8 +32,7 @@ quit
 END_OF_DATA
 
 export zstat
-if ! grep "No Jobs running." "${tmp}"/dir.out >/dev/null 2>&1
-then
+if ! grep "No Jobs running." "${tmp}"/dir.out >/dev/null 2>&1; then
   echo " "
   echo "  !!!! Zombie Jobs in Director !!!!"
   echo "  !!!! Zombie Jobs in Director !!!!" >>test.out
@@ -43,8 +42,7 @@ then
   zstat=1
   exit 1
 fi
-if ! grep "No Jobs running." "${tmp}"/fd.out >/dev/null 2>&1;
-then
+if ! grep "No Jobs running." "${tmp}"/fd.out >/dev/null 2>&1; then
   echo " "
   echo "  !!!! Zombie Jobs in File daemon !!!!"
   echo "  !!!! Zombie Jobs in File daemon !!!!" >>test.out
@@ -54,8 +52,7 @@ then
   zstat=1
   exit 1
 fi
-if ! grep "No Jobs running." "${tmp}"/sd.out >/dev/null 2>&1
-then
+if ! grep "No Jobs running." "${tmp}"/sd.out >/dev/null 2>&1; then
   echo " "
   echo "  !!!! Zombie Jobs in Storage daemon !!!!"
   echo "  !!!! Zombie Jobs in Storage daemon !!!!" >>test.out
@@ -68,34 +65,34 @@ fi
 
 if ls "${tmp}"/log*.out >/dev/null 2>&1; then
 
-    if grep "ERROR" "${tmp}"/log*.out >/dev/null 2>&1; then
-        echo " "
-        echo "  !!!! ERROR in log output !!!!"
-        echo "  !!!! ERROR in log output !!!!" >>test.out
-        grep "ERROR" "${tmp}"/log*.out
-        echo " "
-        zstat=1
-        exit 1
-    fi
+  if grep "ERROR" "${tmp}"/log*.out >/dev/null 2>&1; then
+    echo " "
+    echo "  !!!! ERROR in log output !!!!"
+    echo "  !!!! ERROR in log output !!!!" >>test.out
+    grep "ERROR" "${tmp}"/log*.out
+    echo " "
+    zstat=1
+    exit 1
+  fi
 
-    if grep "Fatal Error" "${tmp}"/log*.out >/dev/null 2>&1; then
-        echo " "
-        echo "  !!!! Fatal Error in log output !!!!"
-        echo "  !!!! Fatal Error in log output !!!!" >>test.out
-        grep "Fatal Error" "${tmp}"/log*.out
-        echo " "
-        zstat=1
-        exit 1
-    fi
+  if grep "Fatal Error" "${tmp}"/log*.out >/dev/null 2>&1; then
+    echo " "
+    echo "  !!!! Fatal Error in log output !!!!"
+    echo "  !!!! Fatal Error in log output !!!!" >>test.out
+    grep "Fatal Error" "${tmp}"/log*.out
+    echo " "
+    zstat=1
+    exit 1
+  fi
 
-    if grep "glibc detected" "${tmp}"/log*.out >/dev/null 2>&1; then
-        echo " "
-        echo "  !!!! glibc detected Error in log output !!!!"
-        echo "  !!!! glibc detected Error in log output !!!!" >>test.out
-        grep "glibc detected" "${tmp}"/log*.out
-        echo " "
-        zstat=1
-        exit 1
-    fi
+  if grep "glibc detected" "${tmp}"/log*.out >/dev/null 2>&1; then
+    echo " "
+    echo "  !!!! glibc detected Error in log output !!!!"
+    echo "  !!!! glibc detected Error in log output !!!!" >>test.out
+    grep "glibc detected" "${tmp}"/log*.out
+    echo " "
+    zstat=1
+    exit 1
+  fi
 
 fi
diff --git a/systemtests/scripts/setup b/systemtests/scripts/setup
--- a/systemtests/scripts/setup
+++ b/systemtests/scripts/setup
@@ -4,18 +4,18 @@ set -e
 . "${rscripts}/functions"
 
 print_debug "drop database \"${db_name}\""
-"${scripts}/drop_bareos_database"   2>&1 > /dev/null ||\
-  echo "info: ${scripts}/drop_bareos_database failed"
+"${scripts}/drop_bareos_database" 2>&1 >/dev/null \
+  || echo "info: ${scripts}/drop_bareos_database failed"
 
 print_debug "creating database \"${db_name}\""
-"${scripts}/create_bareos_database"  2>&1 > /dev/null
+"${scripts}/create_bareos_database" 2>&1 >/dev/null
 
 print_debug "making tables  \"${db_name}\""
-"${scripts}/make_bareos_tables"  2>&1 > /dev/null
+"${scripts}/make_bareos_tables" 2>&1 >/dev/null
 
 print_debug "granting privileges database \"${db_name}\""
-"${scripts}/grant_bareos_privileges"  2>&1 > /dev/null ||\
-  echo "info: ${scripts}/grant_bareos_privileges failed"
+"${scripts}/grant_bareos_privileges" 2>&1 >/dev/null \
+  || echo "info: ${scripts}/grant_bareos_privileges failed"
 
 if lsof="$(command -v lsof)"; then
   for port in $BASEPORT $BAREOS_DIRECTOR_PORT $BAREOS_STORAGE_PORT \
