systemtests: abstract to method, also check for db

diff --git a/core/scripts/bareos-ctl-funcs b/core/scripts/bareos-ctl-funcs
--- a/core/scripts/bareos-ctl-funcs
+++ b/core/scripts/bareos-ctl-funcs
@@ -114,17 +114,26 @@ killproc() {
 }
 
 # Function that checks if the configuration is OK and the Database can be connected
-checkcfg() {
-   RC=0
-   echo "Checking Configuration and Database connection ... "
-   if [ ! -z "${DIR_USER}" -a "${DIR_USER}" != "${USER}" ]; then
-      su -s /bin/sh "${DIR_USER}" -c "${BAREOS_DIRECTOR_BINARY}" ${OPTIONS} -f -t
-      RC=$?
-   else
-      "${BAREOS_DIRECTOR_BINARY}" ${OPTIONS} -f -t
-      RC=$?
+check_daemon() {
+   echo "Checking Configuration and Database connection for $1"
+   log_file="${tmp}/bareos-$1-config-test.out"
+   "$2" -f -t "${@:3}" &> "$log_file"
+
+   if grep -q "Could not open Catalog" "$log_file"; then
+      echo "Fail: Could not connect to the Catalog, see below." >&2
+      cat "$log_file"
+      exit 2
    fi
-   return $RC
+   if ! ${IGNORE_DAEMON_CONFIG_WARNINGS}; then
+      if grep -q "There are configuration warnings" "$log_file"; then
+         echo "Fail: There are configuration warnings for the director when running $2 -t "${@:3}", see below." >&2
+         cat "$log_file"
+         return 7
+      fi
+   else
+      cat "$log_file"
+   fi
+   return 0
 }
 
 status() {
