systemtests: simplify ignore config warnings code

diff --git a/core/scripts/bareos-ctl-funcs b/core/scripts/bareos-ctl-funcs
--- a/core/scripts/bareos-ctl-funcs
+++ b/core/scripts/bareos-ctl-funcs
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 
 # A function to find the pid of a program.
 pidofproc() {
@@ -113,20 +113,28 @@ killproc() {
    return $RC
 }
 
-# Function that checks if the configuration is OK and the Database can be connected
-check_daemon() {
-   echo "Checking Configuration and Database connection for $1"
+# Checks if the Database can be connected to
+check_database() {
+   echo "Checking Database connection for $1"
+   log_file="${tmp}/bareos-$1-config-test.out"
+   "$2" -f -t "${@:3}" &> "$log_file"
+   
+   if grep -q "Could not open Catalog" "$log_file"; then
+      echo "Fail: Could not connect to the Catalog when running $2 -t ${*:3}, see below." >&2
+      cat "$log_file"
+      return 2
+   fi
+   return 0
+}
+# Checks if the configuration outputs warnings
+check_config() {
+   echo "Checking Configuration for $1"
    log_file="${tmp}/bareos-$1-config-test.out"
    "$2" -f -t "${@:3}" &> "$log_file"
 
-   if grep -q "Could not open Catalog" "$log_file"; then
-      echo "Fail: Could not connect to the Catalog, see below." >&2
-      cat "$log_file"
-      exit 2
-   fi
-   if ! ${IGNORE_DAEMON_CONFIG_WARNINGS}; then
+   if ! ${IGNORE_CONFIG_WARNINGS}; then
       if grep -q "There are configuration warnings" "$log_file"; then
-         echo "Fail: There are configuration warnings for the director when running $2 -t "${@:3}", see below." >&2
+         echo "Fail: There are configuration warnings for the director when running $2 -t ${*:3}, see below." >&2
          cat "$log_file"
          return 7
       fi
