scripts: mtx-changer replace perl usage by awk
- add max_wait_drive variable with a default of 300s
  which can be extended in the mtx-changer.conf file to larger value
  (maybe needed for LTO9 drive due to calibration)
- use awk expression if most cases
- unify the way we use awk (-F, double quotes, etc)
- shfmt -i2 -ci
- shellcheck code
- systemtests: add mtx-changer test
- trim trailing whitespace on list cmd
- improve readability of longer awk code use direct input in awk
  expression without variables

Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>

diff --git a/core/scripts/mtx-changer.in b/core/scripts/mtx-changer.in
--- a/core/scripts/mtx-changer.in
+++ b/core/scripts/mtx-changer.in
@@ -45,44 +45,46 @@
 #   the mtx exit code or a 0. If the script exits with a non-zero
 #   exit code, Bareos will assume the request failed.
 #
+# How long we should wait the drive
+# can be overriden in configuration file
+max_wait_drive=300
 
 # source our conf file
-if test ! -r ${confdir:-@confdir@}/mtx-changer.conf ; then
+if test ! -r "${confdir:-@confdir@}/mtx-changer.conf"; then
   echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   echo "ERROR: ${confdir:-@confdir@}/mtx-changer.conf file not found!!!!"
   echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
   exit 1
 fi
-. ${confdir:-@confdir@}/mtx-changer.conf
+. "${confdir:-@confdir@}/mtx-changer.conf"
 
 MTX=${MTX:-@MTX@}
-if test ! -x "$MTX" ; then
-  echo "ERROR: mtx program not found ($MTX)"
+if test ! -x "${MTX}"; then
+  echo "ERROR: mtx program not found (${MTX})"
   exit 1
 fi
 
 dbgfile="${logdir:-@logdir@}/mtx.log"
-if test ${debug_log} -ne 0 ; then
-  touch $dbgfile
+if test ${debug_log} -ne 0; then
+  touch "${dbgfile}"
 fi
 debug() {
-    if test -f $dbgfile; then
-        echo "`date +\"%Y%m%d-%H:%M:%S\"` $*" >> $dbgfile
-    fi
+  if test -f "${dbgfile}"; then
+    echo "$(date +"%Y%m%d-%H:%M:%S") $*" >>"${dbgfile}"
+  fi
 }
-
 
 #
 # Create a temporary file
 #
 make_temp_file() {
-  TMPFILE=`mktemp ${working_dir:-@working_dir@}/mtx.XXXXXXXXXX`
-  if test x${TMPFILE} = x; then
-     TMPFILE="${working_dir:-@working_dir@}/mtx.$$"
-     if test -f ${TMPFILE}; then
-	echo "ERROR: Temp file security problem on: ${TMPFILE}"
-	exit 1
-     fi
+  TMPFILE=$(mktemp "${working_dir:-@working_dir@}/mtx.XXXXXXXXXX")
+  if test "x${TMPFILE}" = "x"; then
+    TMPFILE="${working_dir:-@working_dir@}/mtx.$$"
+    if test -f "${TMPFILE}"; then
+      echo "ERROR: Temp file security problem on: ${TMPFILE}"
+      exit 1
+    fi
   fi
 }
 
@@ -98,16 +100,15 @@ make_temp_file() {
 #  thus we sometimes get better changer results.
 #
 make_err_file() {
-  ERRFILE=`mktemp ${working_dir:-@working_dir@}/mtx.err.XXXXXXXXXX`
-  if test x${ERRFILE} = x; then
-     ERRFILE="${working_dir:-@working_dir@}/mtx.err.$$"
-     if test -f ${ERRFILE}; then
-	echo "ERROR: Temp file security problem on: ${ERRFILE}"
-	exit 1
-     fi
+  ERRFILE=$(mktemp ${working_dir:-@working_dir@}/mtx.err.XXXXXXXXXX)
+  if test "x${ERRFILE}" = "x"; then
+    ERRFILE="${working_dir:-@working_dir@}/mtx.err.$$"
+    if test -f "${ERRFILE}"; then
+      echo "ERROR: Temp file security problem on: ${ERRFILE}"
+      exit 1
+    fi
   fi
 }
-
 
 #
 # The purpose of this function to wait a maximum
@@ -122,7 +123,7 @@ make_err_file() {
 #
 wait_for_drive() {
   i=0
-  while [ $i -le 300 ]; do  # Wait max 300 seconds
+  while [ ${i} -le ${max_wait_drive} ]; do
     debug "Doing mt -f $1 status ..."
     drivestatus=$(mt -f "$1" status 2>&1)
     if echo "${drivestatus}" | grep "${ready}" >/dev/null 2>&1; then
@@ -131,45 +132,44 @@ wait_for_drive() {
     debug "${drivestatus}"
     debug "Device $1 - not ready, retrying ..."
     sleep 1
-    i=`expr $i + 1`
+    i=$(expr ${i} + 1)
   done
 }
 
 # check parameter count on commandline
 #
 check_parm_count() {
-    pCount=$1
-    pCountNeed=$2
-    if test $pCount -lt $pCountNeed; then
-	echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
-	echo "	Insufficient number of arguments given."
-	if test $pCount -lt 2; then
-	    echo "  Mimimum usage is first two arguments ..."
-	else
-	    echo "  Command expected $pCountNeed arguments"
-	fi
-	exit 1
+  pCount=$1
+  pCountNeed=$2
+  if test ${pCount} -lt ${pCountNeed}; then
+    echo "ERROR: usage: mtx-changer ctl-device command [slot archive-device drive-index]"
+    echo "	Insufficient number of arguments given."
+    if test ${pCount} -lt 2; then
+      echo "  Mimimum usage is first two arguments ..."
+    else
+      echo "  Command expected ${pCountNeed} arguments"
     fi
+    exit 1
+  fi
 }
 
 # Check for special cases where only 2 arguments are needed,
 #  all others are a minimum of 5
 #
 case $2 in
-    list|listall)
-	check_parm_count $# 2
-	;;
-    slots)
-	check_parm_count $# 2
-	;;
-    transfer)
-	check_parm_count $# 4
-	;;
-    *)
-	check_parm_count $# 5
-	;;
+  list | listall)
+    check_parm_count $# 2
+    ;;
+  slots)
+    check_parm_count $# 2
+    ;;
+  transfer)
+    check_parm_count $# 4
+    ;;
+  *)
+    check_parm_count $# 5
+    ;;
 esac
-
 
 # Setup arguments
 ctl=$1
@@ -178,119 +178,148 @@ slot=$3
 device=$4
 drive=$5
 
-debug "Parms: $ctl $cmd $slot $device $drive"
+debug "Parms: ${ctl} ${cmd} ${slot} ${device} ${drive}"
 
-case $cmd in
-   unload)
-      debug "Doing mtx -f $ctl unload $slot $drive"
+case "${cmd}" in
+  unload)
+    debug "Doing mtx -f ${ctl} unload ${slot} ${drive}"
 
-      if test ${offline} -eq 1 ; then
-        mt -f $device offline
-      fi
-      if test ${offline_sleep} -ne 0 ; then
-        sleep ${offline_sleep}
-      fi
-      make_err_file
-      ${MTX} -f $ctl unload $slot $drive 2>${ERRFILE}
-      rtn=$?
-      cat ${ERRFILE}
-      rm -f ${ERRFILE} >/dev/null 2>&1
-      exit $rtn
-      ;;
+    if test ${offline} -eq 1; then
+      mt -f "${device}" offline
+    fi
+    if test ${offline_sleep} -ne 0; then
+      sleep ${offline_sleep}
+    fi
+    make_err_file
+    ${MTX} -f "${ctl}" unload ${slot} ${drive} 2>"${ERRFILE}"
+    rtn=$?
+    cat "${ERRFILE}"
+    rm -f "${ERRFILE}" >/dev/null 2>&1
+    exit $rtn
+    ;;
 
-   load)
-      debug "Doing mtx -f $ctl load $slot $drive"
-      make_err_file
-      ${MTX} -f $ctl load $slot $drive 2>${ERRFILE}
-      rtn=$?
-      if test ${load_sleep} -ne 0 ; then
-        sleep ${load_sleep}
-      fi
-      wait_for_drive $device
-      cat ${ERRFILE}
-      rm -f ${ERRFILE} >/dev/null 2>&1
-      exit $rtn
-      ;;
+  load)
+    debug "Doing mtx -f ${ctl} load ${slot} ${drive}"
+    make_err_file
+    ${MTX} -f "${ctl}" load ${slot} ${drive} 2>"${ERRFILE}"
+    rtn=$?
+    if test ${load_sleep} -ne 0; then
+      sleep ${load_sleep}
+    fi
+    wait_for_drive ${device}
+    cat "${ERRFILE}"
+    rm -f "${ERRFILE}" >/dev/null 2>&1
+    exit $rtn
+    ;;
 
-   list)
-      debug "Doing mtx -f $ctl -- to list volumes"
-      make_temp_file
-      if test ${inventory} -ne 0 ; then
-        ${MTX} -f $ctl inventory
-      fi
-      ${MTX} -f $ctl status >${TMPFILE}
-      rtn=$?
-      if test ${vxa_packetloader} -ne 0 ; then
-        cat ${TMPFILE} | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
-      else
-	cat ${TMPFILE} | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
-      fi
-      cat ${TMPFILE} | grep "^Data Transfer Element [0-9]*:Full (Storage Element [0-9]" | awk '{printf "%s:%s\n",$7,$10}'
-      rm -f ${TMPFILE} >/dev/null 2>&1
-      exit $rtn
-      ;;
+  list)
+    debug "Doing mtx -f ${ctl} -- to list volumes"
+    make_temp_file
+    if test ${inventory} -ne 0; then
+      ${MTX} -f "${ctl}" inventory
+    fi
+    ${MTX} -f "${ctl}" status >"${TMPFILE}"
+    rtn=$?
+    #if test ${vxa_packetloader} -ne 0 ; then
+    #  cat "${TMPFILE}" | grep " *Storage Element [0-9]*:.*Full" | sed "s/ Storage Element //" | sed "s/Full :VolumeTag=//"
+    #else
+    #  cat "${TMPFILE}" | grep " Storage Element [0-9]*:.*Full" | awk "{print \$3 \$4}" | sed "s/Full *\(:VolumeTag=\)*//"
+    #fi
+    # We shouldn't have a difference with this pattern
+    awk -F ":" -f - "${TMPFILE}" << '_EOT_'
+    /^ .*Storage Element .*[0-9]:.*Full/ {
+      gsub("[ ].*Storage Element ","",$1)
+      gsub("VolumeTag=","",$3)
+      gsub(/ *$/, "", $3)
+      print $1 ":" $3
+    }
+_EOT_
 
-   listall)
-#  Drive content:	  D:Drive num:F:Slot loaded:Volume Name
-#  D:0:F:2:vol2        or D:Drive num:E
-#  D:1:F:42:vol42
-#  D:3:E
-#
-#  Slot content:
-#  S:1:F:vol1		  S:Slot num:F:Volume Name
-#  S:2:E	       or S:Slot num:E
-#  S:3:F:vol4
-#
-#  Import/Export tray slots:
-#  I:10:F:vol10 	  I:Slot num:F:Volume Name
-#  I:11:E	       or I:Slot num:E
-#  I:12:F:vol40
+    awk -f - "$TMPFILE" << '_EOT_'
+    /^Data Transfer Element [0-9]*:Full \(Storage Element [0-9]/ {
+      printf "%s:%s\n",$7,$10
+    }
+_EOT_
+    rm -f "${TMPFILE}" >/dev/null 2>&1
+    exit $rtn
+    ;;
 
-      debug "Doing mtx -f $ctl -- to list all"
-      make_temp_file
-      if test ${inventory} -ne 0 ; then
-        ${MTX} -f $ctl inventory
-      fi
-      ${MTX} -f $ctl status >${TMPFILE}
-      rtn=$?
-      # can be converted to awk+sed+cut, see below
-      perl -ne '
-/Data Transfer Element (\d+):Empty/ && print "D:$1:E\n";
-/Data Transfer Element (\d+):Full \(Storage Element (\d+) Loaded\)(:VolumeTag =\s*(.+))?/ && print "D:$1:F:$2:$4\n";
-/Storage Element (\d+):Empty/ && print "S:$1:E\n";
-/Storage Element (\d+):Full( :VolumeTag=(.+))?/ && print "S:$1:F:$3\n";
-/Storage Element (\d+) IMPORT.EXPORT:Empty/ && print "I:$1:E\n";
-/Storage Element (\d+) IMPORT.EXPORT:Full( :VolumeTag=(.+))?/ && print "I:$1:F:$3\n";' ${TMPFILE}
-      # If perl isn't installed, you can use by those commands
-#cat ${TMPFILE} | grep "Data Transfer Element" | awk "{print \"D:\"\$4 \$7 \$9 \$10}" | sed "s/=/:/" | sed "s/Full/F:/" | sed "s/Empty/E/"
-#cat ${TMPFILE} | grep -v "Data Transfer Element" | grep "Storage Element" | grep -v "IMPORT/EXPORT" | awk "{print \"S:\"\$3 \$4 \$5}" | sed "s/IMPORT\/EXPORT//" | sed "s/Full *:VolumeTag=/F:/" | sed "s/Empty/E/"
-#cat ${TMPFILE} | grep -v "Data Transfer Element" | grep "Storage Element" | grep "IMPORT/EXPORT" | awk "{print \"I:\"\$3 \$4 \$5}" | sed "s/IMPORT\/EXPORT//" | sed "s/Full *:VolumeTag=/F:/" | sed "s/Empty/E/"
+  listall)
+    #  Drive content:	  D:Drive num:F:Slot loaded:Volume Name
+    #  D:0:F:2:vol2        or D:Drive num:E
+    #  D:1:F:42:vol42
+    #  D:3:E
+    #
+    #  Slot content:
+    #  S:1:F:vol1		  S:Slot num:F:Volume Name
+    #  S:2:E	       or S:Slot num:E
+    #  S:3:F:vol4
+    #
+    #  Import/Export tray slots:
+    #  I:10:F:vol10 	  I:Slot num:F:Volume Name
+    #  I:11:E	       or I:Slot num:E
+    #  I:12:F:vol40
 
-      rm -f ${TMPFILE} >/dev/null 2>&1
-      exit $rtn
-      ;;
+    debug "Doing mtx -f $ctl -- to list all"
+    make_temp_file
+    if test ${inventory} -ne 0; then
+      ${MTX} -f "${ctl}" inventory
+    fi
+    ${MTX} -f "${ctl}" status >"${TMPFILE}"
+    rtn=$?
+    awk -F ":" -f - "${TMPFILE}" << '_EOT_'
+    /^Data Transfer Element .*[0-9]:/ {
+      gsub("Data Transfer Element ","",$1)
+      F=gensub(/Full \(Storage Element ([0-9]{1,}) Loaded\)/,":F:\\1",1,$2)
+      gsub("Empty",":E",F)
+      gsub("VolumeTag = ",":",$3)
+      print "D:" $1 F $3
+    }
+_EOT_
+    awk -F ":" -f - "${TMPFILE}" << '_EOT_'
+    /^ .*Storage Element .*[0-9]:/ {
+      gsub("[ ].*Storage Element ","",$1)
+      gsub("Full ",":F",$2)
+      gsub("Empty",":E",$2)
+      gsub("VolumeTag=",":",$3)
+      print "S:" $1  $2  $3
+    }
+_EOT_
+    awk -F ":" -f - "${TMPFILE}" << '_EOT_'
+    /^ .*Storage Element .*[0-9] IMPORT\/EXPORT:/ {
+      gsub("[ ].*Storage Element ","",$1)
+      gsub(" IMPORT/EXPORT","",$1)
+      gsub("Full ",":F",$2)
+      gsub("Empty",":E",$2)
+      gsub("VolumeTag=",":",$3)
+      print "I:"$1 $2 $3
+    }
+_EOT_
+    rm -f "${TMPFILE}" >/dev/null 2>&1
+    exit $rtn
+    ;;
 
-   transfer)
-      slotdest=$device
-      debug "Doing transfer from $slot to $slotdest"
-      ${MTX} -f $ctl transfer $slot $slotdest
-      rtn=$?
-      exit $rtn
-      ;;
+  transfer)
+    slotdest=$device
+    debug "Doing transfer from ${slot} to ${slotdest}"
+    ${MTX} -f "${ctl}" transfer ${slot} ${slotdest}
+    rtn=$?
+    exit $rtn
+    ;;
 
-   loaded)
-      debug "Doing mtx -f $ctl $drive -- to find what is loaded"
-      make_temp_file
-      ${MTX} -f $ctl status >${TMPFILE}
-      rtn=$?
-      cat ${TMPFILE} | grep "^Data Transfer Element $drive:Full" | awk "{print \$7}"
-      cat ${TMPFILE} | grep "^Data Transfer Element $drive:Empty" | awk "{print 0}"
-      rm -f ${TMPFILE} >/dev/null 2>&1
-      exit $rtn
-      ;;
+  loaded)
+    debug "Doing mtx -f $ctl ${drive} -- to find what is loaded"
+    make_temp_file
+    ${MTX} -f "${ctl}" status >"${TMPFILE}"
+    rtn=$?
+    awk "/^Data Transfer Element ""${drive}"":Full/ {print \$7}" "$TMPFILE"
+    awk "/^Data Transfer Element ""${drive}"":Empty/ {print 0}" "$TMPFILE"
+    rm -f "${TMPFILE}" >/dev/null 2>&1
+    exit $rtn
+    ;;
 
-   slots)
-      debug "Doing mtx -f $ctl -- to get count of slots"
-      ${MTX} -f $ctl status | grep " *Storage Changer" | awk "{print \$5}"
-      ;;
+  slots)
+    debug "Doing mtx -f ${ctl} -- to get count of slots"
+    ${MTX} -f "${ctl}" status | awk "/^  Storage Changer .*:/ {print \$5}"
+    ;;
 esac
